### ISSUE TITLE
Pattern:Runecloth Cloak/Robe/Boots

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#100]
These should be available from Darnall in Moonglade (made available by training in a later patch).  Cloak I believe was a limited supply, bop, but none are shown at Darnall.

Only reference I can find is: http://www.aowow.org/?npc=7940#wh-comments

**Comment by brues-code** [comment]
Fix has been submitted

**Comment by Skylark14** [comment]
Ty Brues
