### ISSUE TITLE
Crumpled/Ripped/Torn notes

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#101]
Name: Breena
Account Name (for vote points rewards): Skylark
Map & Area: Arathi Highlands
How to replicate the bug: Kill Raptors
What happens: They drop items that should be in bottles on the STV beach where the bloodsail are.
What should happen: These should not drop from raptors.
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

![image](https://f.cloud.github.com/assets/4540036/1064756/44913532-134d-11e3-8e06-597bdbe0f05b.png)

These items are dropping from raptors in Arathi Highlands.

**Comment by brues-code** [comment]
http://www.wowhead.com/item=4100#comments:id=683376
Not bugged

**Comment by Skylark14** [comment]
Weird, I remember these always dropping from the green bottles in stv in retail vanilla.

**Comment by brues-code** [comment]
Yeah they drop from both

**Comment by CravenEsq** [comment]
Closed.
