### ISSUE TITLE
Dire Maul

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#102]
Name: Dhanae
Account Name (for vote points rewards): Skylark
Map & Area: Dire Maul
How to replicate the bug: Start Pusillin, and do the Ironbark Event.
What happens: Pusillin still bugged. Get to where he should then resets? as he disappears. Ironbark event, you can't open door.
What should happen: Pusillin should not reset.  Ironbark event should allow you to open the door on completion.
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by brues-code** [comment]
Tested Pusillin earlier. We found that he wouldn't disappear if you cleared the trash before the ledge you fight him on.
Ironbark event was ingame, but Ironbark the Redeemed wasn't spawning after Zanzil's death. Fix has been submitted.
The door after the final boss (Alzzin) wasn't opening after his death. Fix has been submitted
