### ISSUE TITLE
Onyxia questline

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#104]
Name: Dhanae
Account Name (for vote points rewards): Skylark
Map & Area: Stormwind - Stormwind Keep
How to replicate the bug: Speak to Lady Prestor
What happens: She just says Greetings etc
What should happen: You should be able to speak to her before the next part
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: Have 2 guild members on this part, Vainzki and Dris, they cannot progress further as Lady Prestor will not speak to them.  Three members have done this part and had no problem but this was before the server crash so not sure if maybe something got bugged.

**Comment by brues-code** [comment]
Our script library is missing which is bugging this out

**Comment by Skylark14** [comment]
kk Brues, thks for the info

**Comment by brues-code** [comment]
Should be fixed now

**Comment by scotty0100** [comment]
Talked with Dris after reboot - confirmed working after SD2 recompiled. Closing.
