### ISSUE TITLE
Quest - Jailbreak

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#108]
Name: Dhanae
Account Name (for vote points rewards): Skylark
Map & Area: BRD - Detention Block
How to replicate the bug: 
What happens: Seems if someone has the quest in their log - Jailbreak - it won't complete properly even though they get Windsor safely to the entrance
What should happen: it should complete whether you have the quest in yr log or retake it
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:  Completed for all the party except Dhanae, who had the quest in her log. Log title says failed, but it says compete if you open the quest, so confused but couldn't hand in anyway.  Also Windsor starts off friendly then once he gets his armor, goes neutral so if you aoe he will attack you.  He should be green to the party so aoe won't affect him. 

![jailbreak](https://f.cloud.github.com/assets/4540036/1102682/df8880a2-184a-11e3-8222-02cfc0f411b3.jpg)

**Comment by kamicolo** [comment]
NPC marshall windsor uopn gear equipment faction state neutral instead of friendly

**Comment by scotty0100** [comment]
Marshall Windsor part of this bug report is now fixed. I can not replicate it not completely properly. Has it only happened to you or others too?

**Comment by Deviastarix** [comment]
No idea how I missed this when I looked a couple of days ago, but anyway, we just did the quest with 3 people in the group on it. Windsor stayed friendly throughout, as he should, and all 3 on the quest got it completed. Seems fine now.
