### ISSUE TITLE
Line of Sight

### ISSUE THREAD

**Issue by vainzki** [scotty0100/wowascension-issues#113]
Account Name (for vote points rewards): Vainzki
Map & Area: All dungeons
How to replicate the bug: Pull a caster mob, run behind a corner.
What happens: Caster mob stays where it was when you pulled it and will not move unless you run further away than its cast range is.
What should happen: Mob should follow you behind the corner and then try casting spells.
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by scotty0100** [comment]
Tested & approved. +10VP.

**Comment by kamicolo** [comment]
CLOSING https://github.com/scotty0100/wowascension-issues/issues/44
