### ISSUE TITLE
Hunter pets Disappeared.

### ISSUE THREAD

**Issue by Raewhen** [scotty0100/wowascension-issues#119]
Odin, lvl 40 Dwarf hunter 10:00 AM Central Time U.S.A. I logged in an my pet is gone and wont summon when i use summon pet. It tells me i completely do not have a pet. This appears to have happened with other hunters as well, I assume it happened with all hunters. This is the second time it has happened to me.

What should happen: Hunter pets do not disappear forever when servers get reset

Im going to go tame and level a new pet.... ..  -Odin

**Comment by Skylark14** [comment]
Same thing happened to me on Breena, was reported at the time.  First time it happened, I wasn't sure it was completely happy so thought maybe that was the reason, second time I was sure it was completely happy but when I logged in the next day it had completely gone.

**Comment by scotty0100** [comment]
Ended as duplicate https://github.com/scotty0100/wowascension-issues/issues/125
