### ISSUE TITLE
Crown of the Earth

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#12]
Reported by Skylark:

"Name: Skylark
Map & Area: Teldrassil -Dolanaar
How to replicate the bug: Accept the quest Crown of the Earth (part of the chain)
What happens: When accepting this quest, Corithras Moonrage actually gives you another quest with the same objective.  You receive two items one is called filled Amethyst Phial and the other Vial of Blessed Water.
What should happen: This should only be given once and the objective should only be Filled Amethyst Vial.
Located on WoWHead Map (if applicable): http://www.wowhead.com/maps
Source (proof, if applicable): Just accept this part of the chain.

When you complete this, you hand in both and get given the last part to hand in to Staghelm which then reverts back to how it should be with one hand in."

**Comment by scotty0100** [comment]
This is fixed.
