### ISSUE TITLE
Frostsaber Provisions

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#121]
Name: Dhanae
Account Name (for vote points rewards): Azrash
Map & Area: Frostsaber Rock - Winterspring
How to replicate the bug: Try to take the quest
What happens: He acts as if your on a repeat quest. The quest he offers is a yellow ? instead of a ! and has continue on the bottom left button instead of accept as if you already have the quest and are handing in so you actually do not get the quest if you try to get the required meat it doesn't drop.
What should happen: He should offer the quest so you have it in your log and then the meat should drop
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: Originally informed by Azrash who tried this so I said I would test it so any points should go to him

**Comment by Skylark14** [comment]
Update - now has a yellow ! but the quest still acts as if you are already on it with a grey continue so you cannot actually pick up the starter quest.

![frostsaber](https://f.cloud.github.com/assets/4540036/1320066/7ddbbc0c-3334-11e3-85dd-5f7c7205c341.jpg)

**Comment by scotty0100** [comment]
Fixed and on Starix.
