### ISSUE TITLE
Scholomance

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#122]
Name: Dhanae
Account Name (for vote points rewards): Skylark
Map & Area: Scholomance -WPL
How to replicate the bug: enter the instance
What happens: Theres a construct who paths in the whelp room
What should happen: It should stay in Rattlegores room
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: Also found some ghouls and Reanimated Corpse on the floor above where they should be (Janice Barov's room).  They appeared to fall from the ceiling when in fact the room is below.  Scholomance Occultists in Instructor Malica's room - these should change to dark shade's and be immune to melee so the casters have to kill them but they didn't.  Los issues also here, mainly on casters. The Reanimated Corpse's do not reanimate as they should and the skeleton's - Risen's Abberations in Janice Barov's room should only be able to be killed by melee  but I was able to kill them with spells and they should cast fixate but they didn't.
Kirtonos the Herald does not do his knockback and fear.

Chamber of Summoning - a group by the next room's door aggro's when you are on the group on the opposite side.  A summoner appears to summon from the opposite group.

Had some serious FPS issues in the room with the Tutors. (27/9) May have had something to do with the server going down twice but not sure.

A lot of the bosses aren't dropping anything apart from a scourgestone.

Will update with further info on this as we spot them.

**Comment by kamicolo** [comment]
closing: https://github.com/scotty0100/wowascension-issues/issues/423
