### ISSUE TITLE
Framerate bug

### ISSUE THREAD

**Issue by vainzki** [scotty0100/wowascension-issues#124]
Account Name (for vote point rewards): Vainzki
Map & Area: Theramore (Jaina's tower)
How to replicate the bug: Run inside Jaina's tower
What happens: Before half way running up the framerate will drop to 0.5 FPS and stays there until client restart.
What should happen: Nothing.
Located on WoWHead Map (if applicable): http://www.wowhead.com/maps
Source (proof, if applicable):

Extra Information:

**Comment by CravenEsq** [comment]
Already reported by Skylark.

https://github.com/scotty0100/wowascension-issues/issues/96

**Comment by scotty0100** [comment]
Tested this and Scholo Tutors room and can't replicate on

Nvidia GTX680 with 314.07 drivers.

**Comment by Skylark14** [comment]
1.06am 1/10/13: Zoram Strand:

![framerate1zoram](https://f.cloud.github.com/assets/4540036/1259566/cbde744c-2bed-11e3-8ab5-13a2264b4c3e.jpg)

**Comment by Skylark14** [comment]
14.14pm 1/10/13: by magetower in Theramore:

![framerate2 magetower](https://f.cloud.github.com/assets/4540036/1259572/06cd00e6-2bee-11e3-9207-6c2202c0ff36.jpg)

**Comment by Skylark14** [comment]
13/10/13 - 09.29 - 09.31 Magetower Theramore twice had fps issues trying to get in the tower.

Again at 09.33 trying to get out:

![framerate3magetower](https://f.cloud.github.com/assets/4540036/1321761/91fccbf2-33ea-11e3-97b5-366e7158f8fd.jpg)

**Comment by Skylark14** [comment]
This seems to affect different video cards.  Both myself and a friend, who have different video cards, were in Theramore on 25/11/13 and both had this problem at the same time having to alt f4 to reload the game.

**Comment by Skylark14** [comment]
Happened again today after going to the new server

![magetower](https://cloud.githubusercontent.com/assets/4540036/2800035/86b4384c-cc6b-11e3-914b-50fb9a9eee17.jpg)

**Comment by Skylark14** [comment]
and again when trying to leave Theramore

![magetower2](https://cloud.githubusercontent.com/assets/4540036/2800338/91b17f10-cc71-11e3-93cc-a1a1a7a3ed01.jpg)
