### ISSUE TITLE
Hunter pet disappeared

### ISSUE THREAD

**Issue by vainzki** [scotty0100/wowascension-issues#125]
Account Name (for vote point rewards): Vainzki
Map & Area: Ironforge
How to replicate the bug: Make a hunter, leave it to Ironforge with pet and log out.
What happens: Overnight the pet runs away. Loyalty with the pet at the time was level 4.
What should happen: Nothing, the pet shouldn't disappear while logged out.
Located on WoWHead Map (if applicable): http://www.wowhead.com/maps
Source (proof, if applicable):

Extra Information: This is a difficult one to replicate as the pet does not always disappear but it is also annoying.

**Comment by CravenEsq** [comment]
Already reported by Raewhen.

**Comment by Skylark14** [comment]
So far this has happened to four hunters.  One lost their pet twice, one three times.

**Comment by scotty0100** [comment]
Try and keep all instances of this logged in this bug report and it will help me track down the problem; I've had a look and can't see why it's happening. Try and track days/time of incident etc as much information as you can and there might be a trend to all this.

**Comment by Skylark14** [comment]
Only common thing for most, if not all of these pets, is that the hunters was logged out in IF or another city. 

Just had it confirmed from Holmski that both his pets disappeared, one was in the stable. Date unsure as wasn't on for a few days.

**Comment by fortehlulz** [comment]
My pet ran away in Orgrimmar

confirmed as 2/3 October.  Logged out on 2nd.  Logged in on 3rd to find it gone.

**Comment by Skylark14** [comment]
Odin confirmed his pet disappeared at Swamp of Sorrows.  Day unknown as he was offline for a few days.

**Comment by Skylark14** [comment]
Player (Nysix) reported that he logged out earlier (17/10), pet was happy, logged in later and pet was gone.  This was in Darnassus.

**Comment by Skylark14** [comment]
30/10/2013:

Player Nysix reported logged out in IF yesterday.  2 Pets disappeared, one in use and the one in the stables

**Comment by Skylark14** [comment]
Hunter Breena, both pets disappeared last night/this morning 3-4 Nov in IF.  One was stabled.  Had stabled it at Menethil thinking it wouldn't be affected but it is.

**Comment by Skylark14** [comment]
Player Twang lost pet out in the world in Teldrassil.  Not logged on for a few days so unsure when it happened.

**Comment by scotty0100** [comment]
Any more recent events of these? I optimized the mySQL tables about 4-5 days ago, wondered if that helped at all.

**Comment by Skylark14** [comment]
Well tbh I've been logging out at Menethil but will log out in IF and see what happens.

**Comment by Skylark14** [comment]
I lost both pets after logging out in IF to test and see what happens.  One was in stables in menethil. This was around 2nd Jan.

**Comment by Skylark14** [comment]
Toska, (Horde hunter called Nazgrel) lost pet while logging out in world in Barrens.  Logged on site 21.1.14.  So optimization has not fixed this issue.

**Comment by Skylark14** [comment]
Tested on the gm hunter char, tamed pet in feralas, tele to darn and pet disappeared so tamed anather in darn, logged out, pet gone when got back at 15.45.

**Comment by Skylark14** [comment]
Logged onto Breena  around 18.45.  She was logged out in menethil. pet disappeared.

**Comment by Skylark14** [comment]
Nysix logged onto hunter today, hadn't logged for a while, pet gone.  Logged outside of IF.

**Comment by Skylark14** [comment]
Logged onto Breena this morning (23/2/4), pet disappeared.  Had logged out in Burning Steppes yesterday afternoon.  Pet was at full loyalty and level 60.

**Comment by Nelway** [comment]
Same here. Logged out yesterday, lvl 60 Rakshiri-type aqua saber at Best friend loyalty, gone. Along with the lvl 59 Frostsaber and lvl 37 Broken Tooth in my stables.

Character: Nayden (60 Nelf Hunter)
Location: Inside Gadgetzan but outside the tavern.

Logout date: 2014.02.22. - 17:29 GMT+1

Login date: 2014.02.23. - 18:32 GMT+1

(Even made a screenshot with my pet out, just before logging out)

**Comment by Skylark14** [comment]
player Dubrul lost both pets (one stable) between 16/3-17/3/14.  Was logged out in Feralas

**Comment by Skylark14** [comment]
Player Nysix logged on today 23/3/14 - pet gone. Disappeared either sat or early sun am.

Also had a report of a Horde hunter losing their pet same time span.

**Comment by Skylark14** [comment]
28/3/14 - Player Leocryst lost his pet (sometime between logging 27/3-28/3)

**Comment by Skylark14** [comment]
Appears to be fixed
