### ISSUE TITLE
Uldaman

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#126]
Name: Tootsie
Account Name (for vote points rewards): Skylark
Map & Area: Uldaman - Badlands

Revelosh:
He does not drop the staff piece. He should as its 100% droprate and a part that is needed to gain access to Ironaya.

Altar of the Stonekeeper:
Stone Keepers are animated, they should be statues until you use the altar and then reanimate. We killed 2 and then 2 more spawned in their place and then we killed them.  Other two remained in place. - fixed

Archaedas:
Mobs in the room were animated and hostile, they should be statues until the event is started where Archaedas summons a group at a time. - fixed

Discs of Norgannon:
Stone Watcher is not there so one part of the quests (43+ The Platinum Discs) is unable to be done.   The other quest was able to be handed in at IF with no problem.  However, I think it should be done in two parts, you get one quest, speak to the stonewatcher then he tells you to pick up the discs and you take them back to IF.  Atm both are offered at the same time.

Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by scotty0100** [comment]
Fixed this part:

Revelosh:
He does not drop the staff piece. He should as its 100% droprate and a part that is needed to gain access to Ironaya.

Will be in on next reboot.
