### ISSUE TITLE
Shaman's far sight

### ISSUE THREAD

**Issue by toogi1** [scotty0100/wowascension-issues#127]
Name: toogi
Account Name (for vote points rewards): toogi
Map & Area: 
How to replicate the bug: Try to use far sight
What happens: It works for 0.5 seconds giving you view of the targeted area. Then the channeling ends. 
What should happen: far sight should give you view of the area for longer time
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by CravenEsq** [comment]
Rejected and confirmed with my own shaman, as Toogie reported it was working after all.
