### ISSUE TITLE
Zul Gurub

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#128]
Name: Dhanae
Account Name (for vote points rewards): Skylark
Map & Area: Zul Gurub - STV
How to replicate the bug: Get feared by the Gurubashi Berserker
What happens: he fears some people through the ground
What should happen: You should not go through the ground, just run around
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: Axe throwers didn't appear to use their spinning attack

**Comment by kamicolo** [comment]
closing: https://github.com/scotty0100/wowascension-issues/issues/73
