### ISSUE TITLE
Quest - Tears of the Moon

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#13]
Reported by Skylark:

"Name: Skylark
Area: Teldrassil

This quest should be offered by Priestess A'moora in the temple.

Objective: Kill Lady Sathrah and recover her silvery spinnerets which then leads to "Sathrah's Sacrifice", in which you had to travel to the Temple of the Moon in Darnassus and sacrifice the Silvery Spinnerets from this quest before the statue of Elune. The (friendly) Spirit of Sathrah would appear, walk a lap around the statue and then despawn.

This is offered at level 10 but the priestess is not offering this even though I am above the level requirements.

The 'breadcrumb' quest which is offered by Sister Aquinne in the Temple Gardens is however working but this should be optional and is not a prequisite for the Tears of the Moon but is acting as if it is."

Thread: http://wowascension.com/forum/index.php?topic=160.0

**Comment by Orcozzio** [comment]
Cannot find the quest into the database http://db.wowascension.com/?quests=1.141

**Comment by scotty0100** [comment]
This starts in Darnassus doesn't it so it wouldn't be under Teldrassil.

**Comment by Orcozzio** [comment]
Good to know because when I searched for quests in Teldrassil I was also thinking about those that start in Darnassus but need stuff to be done in Teldrassil

**Comment by scotty0100** [comment]
Fixed today and will be pushed into Starix tonight.
