### ISSUE TITLE
Warlock Dots/curses

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#131]
Name: Toots
Account Name (for vote points rewards): Skylark
Map & Area: general
How to replicate the bug: have 2 warlocks apply curses etc
What happens: they will not stack
What should happen: they should stack 
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: Seems to apply to curses and corruption and possibly immolate

**Comment by scotty0100** [comment]
After some research it looks like the same rank DoTs stack, if you try and use a lower rank that is already applied on the NPC. It will not stack.

However, the issue remains that SHOULD a lower rank DoT apply regardless of which rank is already on an NPC?

Will need some research to find that out, so leaving this report open.

**Comment by Skylark14** [comment]
Post from Shalymar might help with regard to Curse of Agony:

http://wowmb.net/forums/f9/7377-do_all_curses_stack/

and Corruption:
http://wowmb.net/forums/f9/3530-does_corruption_stack/

**Comment by kamicolo** [comment]
Quick comment: Curse's should not aswell fro anby other debuff as vanilla it's limited to 16 debuffs max on a boss. In past we had classmasters appointing some warlocks who would do which curse and who would drop corruption etc. all otherswould not use these dots and just plain shadowbolt.

For the moment this 1 is rejected although i'd still like to confirm myself that above statement is correct.
