### ISSUE TITLE
Hunter Pet Death Bug

### ISSUE THREAD

**Issue by oggsfml** [scotty0100/wowascension-issues#133]
Name: Oggra
Account Name (for vote points rewards): Oggsfml
Map & Area: Everywhere
How to replicate the bug: Pet dies, unable to rez or call
What happens: When your pet dies you are unable to resurrect or call it, you get the message either you do not have a pet or you have a pet not allowing you to do either.  The only way I could fix it was by relogging.
What should happen: Should be able to resurrect your pet.
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by kamicolo** [comment]
Old server status never happend on new server closing this
