### ISSUE TITLE
Rotting Slime Loot Bug

### ISSUE THREAD

**Issue by oggsfml** [scotty0100/wowascension-issues#134]
Name: Oggra
Account Name (for vote points rewards): Oggsfml
Map & Area: Nightsong Woods near Fallen Sky Lake
How to replicate the bug: Kill a Rotting Slime
What happens: When you kill some of the Rotting Slimes, they spawn a Rusty Chest which has loot similar to the practice chests rogues are meant to skill up on
What should happen: Should just die and if anything have a slimy bag to open on corpse.
Located on WoWHead Map (if applicable):Nightsong Woods near Fallen Sky Lake
Source (proof, if applicable): 

Extra Information:

**Comment by Skylark14** [comment]
As far as I know these always do drop these boxes.  They contain an item for a allied quest 'Raene's Cleansing'.

**Comment by oggsfml** [comment]
Fair enough, I'd killed them a fair amount on live and had never seen this drop, and I played from Beta to MoP, I guess I had just never seen it drop before on live.  Was the chance to spawn the box always this high?  Or is this another case of me being extremely unlucky lol.

**Comment by Skylark14** [comment]
I believe they did.  From what I remember they had a chance to contain the quest item, otherwise it was mostly grey junk.
