### ISSUE TITLE
Hunter Pet Attack Bug

### ISSUE THREAD

**Issue by oggsfml** [scotty0100/wowascension-issues#135]
Name: Oggra
Account Name (for vote points rewards): Oggsfml
Map & Area: Everywhere
How to replicate the bug: Attack a mob with your pet
What happens: Pet appears to stand beside you but the mob acts as if the pet is attacking it where it is standing.
What should happen: Pet should run to the mob and attack.
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by Skylark14** [comment]
Tested this and seemed fine.  Only thing I can think of is if there was some lag at the time.

Occasionally if you put your pet on passive and then change it to defensive it sometimes bugs it so the pet doesn't move when you click on attack.  A relog usually sorts this out.

**Comment by scotty0100** [comment]
This has been fixed.
