### ISSUE TITLE
NPC - Razormane Hunter

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#137]
Name: Oggra
Account Name (for vote point rewards): Oggsfml
Map & Area: Thorn Hill, The Barrens
How to replicate the bug: Ongoing, all Razormane Hunter's have two pets
What happens:  Razormane Hunters control two wolf pets, if you kill the hunter and one of the pets they will leave bodies.  The extra pet after it is killed leaves no corpse and has no death animation, it just vanishes.
What should happen:  The hunters should only have one pet
Located on WoWHead Map (if applicable): Thorn Hill

**Comment by Skylark14** [comment]
Checked on wowhead.  Should have only 1 wolf pet.

**Comment by scotty0100** [comment]
This is fixed and has been for a while. Closing.
