### ISSUE TITLE
Class - Shaman - Talent: Mana Tide Totem

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#138]
Name: Dhanae
Account Name (for vote points rewards): Ghito
Map & Area: general
How to replicate the bug: cast Mana Tide Totem
What happens: doesn't give any mana
What should happen: it should give mana
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by Skylark14** [comment]
confirmed by two players

**Comment by Skylark14** [comment]
Lighthawk reported this on forums yesterday (March 30th) as still not working.

**Comment by scotty0100** [comment]
Found fix for this, works on Zeus test server but needs a little bit more testing before commiting to Starix.

**Comment by scotty0100** [comment]
Fixed.
