### ISSUE TITLE
A Taste of Flame

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#139]
Name: Vainzki
Account Name (for vote points rewards): Vainzki
Map & Area: BRD
How to replicate the bug: Use the altered Black Dragonflight Moult on Bael'Gar's remains
What happens: it uses the molt but then nothing happens
What should happen: you should receive the item Encased Fiery Essence
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://db.valkyrie-wow.com/?item=11230#created-by

Extra Information:

**Comment by Skylark14** [comment]
Tested - does not work as it uses the molt but you don't get the essence

**Comment by scotty0100** [comment]
Duplicate closing https://github.com/scotty0100/wowascension-issues/issues/7
