### ISSUE TITLE
Scarlet Diversions

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#14]
Reported by Scarlet:

"Quest "Scarlet Diversions" (http://db.valkyrie-wow.com/?quest=5096) does not work.
It is impossible to plant "Scourge Banner" (http://db.valkyrie-wow.com/?item=12807), it always says "Requires Scarlet Crusade Forward Camp" even if you stand near/in the tent. I also tested it with and without the tent burned, the result is the same."

**Comment by Skylark14** [comment]
Fixed.
