### ISSUE TITLE
Quest - Shy-Rotam 

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#142]
Name: Dhanae
Account Name (for vote points rewards): Skylark
Map & Area: Frostsaber Rock
How to replicate the bug: see below
What happens: 
What should happen: 
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://www.wowhead.com/npc=10737#comments

The quest for this was Horde only.  Allied couldn't do this until patch 2.3

Also both Shy-Rotam and her mate Sian-Rotam should be tameable npc's.  Atm they're showing as untameable.

Extra Information:

**Comment by scotty0100** [comment]
This is now fixed.
