### ISSUE TITLE
Quest - Gordunni cobalt

### ISSUE THREAD

**Issue by toogi1** [scotty0100/wowascension-issues#143]
Name: toogi
Account Name (for vote points rewards): toogi
Map & Area: Feralas
How to replicate the bug: Take the quest from Camp Mojache and go north to the Gordunni outpost. Then try to use the quest item where the blue circles are
What happens: nothing
What should happen: Using the quest item in circles should reveal collectable quest items.
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: Horde only quest

**Comment by kamicolo** [comment]
https://github.com/scotty0100/wowascension-issues/issues/167

**Comment by scotty0100** [comment]
This is now fixed. Closing.
