### ISSUE TITLE
No Dark Iron Deposits in Burning Steppes

### ISSUE THREAD

**Issue by vainzki** [scotty0100/wowascension-issues#145]
Account Name (for vote points rewards): Vainzki
Map & Area: Burning Steppes
How to replicate the bug: Travel around in Burning Steppes
What happens: There is no Dark Iron Deposits - or any ore.
What should happen: Burning Steppes should have the most Dark Iron Deposits out of any zones.
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by Skylark14** [comment]
I can confirm this as I used to mine it in retail at burning steppes and searing gorge also:

http://db.valkyrie-wow.com/?object=165658

Dark Iron Ore wasn't taken away from the zones until the shattering therefore they should be there as normal.

**Comment by Skylark14** [comment]
marking this as critical as dark iron ore is needed for fire resis gear for plate wearers to enter molten core.

**Comment by scotty0100** [comment]
http://www.wowascension.com/wowhead/?object=165658

Shows for us being there too - maybe they are all underground because of a bad Z axis. I'll check later today after work.

**Comment by kamicolo** [comment]
There are spawns now so closing this
