### ISSUE TITLE
Quest - In Dreams

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#146]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Mardenholde Keep in Hearthglen - WPL
How to replicate the bug: accept the quest In Dreams
What happens: nothing, Taelan does not move
What should happen: you should escort Taelan to the tower further down the road
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: abandoned it and tried again but no result.  This quest is part of a long chain.

**Comment by Deviastarix** [comment]
This quest is no longer bugged. Taelan moves as he should, and the event at the Scarlet Tower can be completed.
