### ISSUE TITLE
UBRS

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#147]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Hall of Binding - UBRS
How to replicate the bug: use the altar to break the adds link with the Pyroguard
What happens: Once you kill the adds, Pyroguard Emberseer does not engage nor does the emotes he is gaining strength appear
What should happen: He should engage once he'll fully empowered
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: Could not get any further as the door won't open till he's killed.

**Comment by scotty0100** [comment]
Fixed.

**Comment by Skylark14** [comment]
Seal of Ascension does not open the door to UBRS, had to get Craven to open the door

Just some patrols don't actually patrol but aside from that a smooth run
