### ISSUE TITLE
Neeru Fireblade

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#15]
Reported by Mad:

"I'm a level 17 Orc Warrior. I have just turned in 'Burning Shadows' and have Hidden Enemies (Part 2) and Path of Defense in my quest log. Neeru Fireblade currently won't let me talk to him to complete Hidden Enemies. He also does not offer the quest 'Ak'Zeloth' and only offers 'Slaying the Beast.' There should also have been a breadcrumb quest from 'Margoz' labeled 'Neeru Fireblade' but that isn't currently implemented either. Here is some screenie proof of the bug.

http://imgur.com/SJZ4dze

Cheers
Mad"

Thread: http://wowascension.com/forum/index.php?topic=169.0

**Comment by scotty0100** [comment]
Fixed and VP were added.
