### ISSUE TITLE
Quest - Lord Banehollow

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#151]
Name: Toots
Account Name (for vote points rewards): Skylark
Map & Area: Altar of Storms - Burning Steppes
How to replicate the bug: try to purchase Shadowy Potions for the quest
What happens: he does not have an option to buy anything
What should happen: he should offer the potions for sale
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://db.vanillagaming.org/?quest=7623#wh-comments
http://db.vanillagaming.org/?npc=14437

Extra Information:

**Comment by scotty0100** [comment]
This is now fixed. Closing.
