### ISSUE TITLE
Suntara Stones

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#153]
Name: Xanedra
Account Name (for vote points rewards): Skylark
Map & Area: Digsite - Searing Gorge
How to replicate the bug: accept the quest
What happens: he just lays there
What should happen: you are supposed to escort him out of the camp
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by scotty0100** [comment]
Duplicate
