### ISSUE TITLE
General - StableMasters

### ISSUE THREAD

**Issue by Raewhen** [scotty0100/wowascension-issues#156]
I can stable a summoned pet as normal. The bug happens when i wish to stable a dismissed pet. The icon in the stable master menu disappears as if the pet is gone. I can use Call Pet and resummon my pet. And the icon reappears in the Stable Master  Menu.

Odin, in Ironfogre. Approx 10:50 central time USA.

This might lead to accidental overwriting of a pet with another pet as well as a number of other, more serious, issues. I am not testing it further at this time.

**Comment by kamicolo** [comment]
you need an active pet to stable closing
