### ISSUE TITLE
Paladin Blessing of Light Buff

### ISSUE THREAD

**Issue by shaz1300** [scotty0100/wowascension-issues#157]
Name: Nallyra
Account Name (for vote points rewards): shaz1300
Map & Area: Everywhere
How to replicate the bug: The Blessing of light should increase the heal of my flash of light and holy light, but it does nothing.
What happens:nothing 
What should happen: depending upon the rank of the buff should increase the healing done by flash of light and holy light, but no change in healing
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: did tests on myself and daemion healing vainzki with and without the buff and the healing amount did not change at all.

**Comment by scotty0100** [comment]
Now fixed and pushed to Starix server.
