### ISSUE TITLE
Paladin Holy Light spell

### ISSUE THREAD

**Issue by shaz1300** [scotty0100/wowascension-issues#158]
Name: Nallyra
Account Name (for vote points rewards): shaz1300
Map & Area: everywhere
How to replicate the bug: cast holy light
What happens: when the spell is casted, it takes the game around 1-2 seconds to aknowledge the heal and heal the target
What should happen: should heal as soon as the cast finishes.
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by scotty0100** [comment]
Fixed in previous patch
