### ISSUE TITLE
Paladin Healing Broken

### ISSUE THREAD

**Issue by shaz1300** [scotty0100/wowascension-issues#159]
Name: nallyra
Account Name (for vote points rewards): shaz1300
Map & Area: everywhere
How to replicate the bug: just heal
What happens: paladin healing spells are uneffected by +healing on gear or any gear in general
What should happen: healing should increase with gear
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: tested with myself nallyra healing vainzki with all gear on for an average of 420 with flash of light and 1.5k with holy light. took all gear off on nallyra and average healing was unaffected indicated that paladin heals aren't interacting with other spells and effects properly, which might also explain the BoL bug.

**Comment by meladath** [comment]
Potential fix for this. Got it working in my testing.

**Comment by kamicolo** [comment]
CLOSING https://github.com/scotty0100/wowascension-issues/issues/32
