### ISSUE TITLE
Field Duty - Silithus 

### ISSUE THREAD

**Issue by vainzki** [scotty0100/wowascension-issues#162]
Name: Vainzki
Account Name (for vote point rewards): Vainzki
Map & Area: Silithus, Hive Zora
How to replicate the bug: Pick up the quest Field Duty from Windcaller Kaldon in Cenarion Hold
What happens: Captain Blackanvil does not appear in Hive Zora Alliance Camp.
What should happen: Captain Blackanvil should be standing at the camp so you can hand in the quest.
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by cardk** [comment]
Hey,

About 50% of the time, when getting an assignment, the letter is empty, rather than having a quest in it. This seems to happen regardless of the type (Tactical, Logistic, Combat) and also affects follow-up assignments.

Regards Sammi

**Comment by kamicolo** [comment]
closing this has been fixed
