### ISSUE TITLE
Quest - Silithus - Glyph Chasing

### ISSUE THREAD

**Issue by vainzki** [scotty0100/wowascension-issues#163]
Name: Vainzki
Account Name (for vote point rewards): Vainzki
Map & Area: Silithus
How to replicate the bug: Pick up the quest Glyph Chasing from Rutgar Glyphshaper in Bronzebeard's Encampment. Go to Hive Zora and try to use the crystal to get the rubbing.
What happens: When you get to the Crystal it says "Greetings Vainzki."
What should happen: You should be able to get the rubbing by clicking the crystal.
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by scotty0100** [comment]
This is now fixed. Will be pushed live later today or tomorrow.

**Comment by Skylark14** [comment]
Re-opened - does not work.  Tried 17/4/14,  clicking on the crystal but it just says greetins .... even though you have the quest and the item in your bag.

**Comment by scotty0100** [comment]
Now fixed and pushed to Starix.
