### ISSUE TITLE
Quest - Divino-matic Rod

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#166]
Name: Breena
Account Name (for vote points rewards): Skylark
Map & Area: Zul Farrak

Witch Doctor Zum'rah:

Did not drop any loot at all.  Should drop either Jumanza Grips or Zum'rah's Vexing Cane.

Pyramid Event:

Activates and goes smoothly until you have to speak to Sergeant Bly but there is no dialogue, then nothing happens, they just hearth out.

They should activate when you speak to Sergeant Bly and then turn hostile, you then kill them and Sergeant Bly drops the quest item Divino-matic Rod so at the moment this quest is unable to be done.

The goblin, when you speak to him just says you need to kill more trolls.  We cleared all the trolls and he still said that.  You should be able to speak to him for him to blow up the door to the last boss area.

http://db.vanillagaming.org/?quest=2768#wh-comments

Extra Information:

**Comment by Skylark14** [comment]
Fixed

**Comment by Skylark14** [comment]
Pyramid event is still buggy.  Once event is completed, Sergeant Bly should have the  dialogue but he doesn't so they stand there for a few moments and then just hearth out thus you are unable to complete the quest Divino-matic Rod.

**Comment by kamicolo** [comment]
Fixed: http://wowascension.com/forum/showthread.php?tid=916
