### ISSUE TITLE
General - Gameobject: Blackhoof Cages

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#168]
Name: Toots
Account Name Skylark
Map & Area: North Dustwallow Marsh

Some Blackhoof cages aren't placed correctly, one is in the air, one is halfway in the ground.

Campfire floating in the air

There should also apparently be the village there but only cages and the campfire.

Source (proof, if applicable): 

Extra Information:

**Comment by scotty0100** [comment]
Don't think we need these. This village was added in 2.3.0 patch. So solution will be to just delete these game objects.

**Comment by Tobschinski** [comment]
They have been removed.
