### ISSUE TITLE
Escape Through Force

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#169]
Name: Xanedra
Account Name (for vote points rewards): Skylark
Map & Area: Darkshore
How to replicate the bug: Accept the quest
What happens: Volcor jumps all over the place during this escort, you get him to the road, quest shows complete onscreen yet when you open the  quest log it shows complete and failed at the same time.
What should happen: You escort Volcor to the road, quest completes and shows it in the log correctly.
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Could not hand this in as Terenthis will not speak to me. Strange as it worked for my friend the first time even though I accepted the quest and his completed but mine didn't.

![escapethroughforce](https://f.cloud.github.com/assets/4540036/1509480/5e9f9888-4a4d-11e3-92df-f2a031f182ca.jpg)

If you are in a party, although it comes up if you also want to do the quest it does not complete for anyone other than the person who spoke to him.

Extra Information:

**Comment by scotty0100** [comment]
Fixed today.
