### ISSUE TITLE
Bitter Rivals

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#17]
Reported by Hundano:

"Character Name: Falcerodin
Location: Dun Morogh, Thunderbrew Distillery
Quest Name: Bitter Rivals  
Quest giver: Marleth Barleybrew
1. What happens: You right click the barrel in the basement, it lets you click "complete".  
What should happen: It should say something about being guarded.
1. What happens: You give Jarven Thunderbrew his Thunder Ale, he disappears, and the quest is completed.
   What should happen: You give Jarven his Thunder Ale, he walks up the stairs and says something, and the quest is ready to complete by right clicking the barrel again.
2. What happens: A second barrel appears after Jarven disappears. This barrel gives you the next quest in the chain.
   What should happen: The first barrel gives you the second quest as soon as you've finished the first one.
   
   I may be wrong on the last 2 points, but I do believe I assume correctly. At least that's how I remember the quest to work. I'll make a second character to find the quest texts, and fill them in here (eventually)."

Extra notes by me:
1. It does say it's guarded, or more something like: "You have to find a way to lure away the guard.", can't remember precisely.
2. This 'bug' didn't occur with me. However, instead of walking upstairs, he was 'lagging' and warping every 2-3 seconds till he ended up at the barkeeper.
3. Confirmed, the first barrel should only change state that would allow the player to finish the quest. It is possible that the first barrel should have despawned and the second barrel is only positioned wrongly.

**Comment by scotty0100** [comment]
Fixed the 'lagging' movement of this quest. But can't find any sources to back up the despawn of the chest. I will close this for now - may update the barrels at a later date.
