### ISSUE TITLE
Quest - Hive in the Tower

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#170]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Southwind Village - Silithus
How to replicate the bug: loot the Hive'Ashi pod
What happens: nothing
What should happen: once you loot it, two Hive'Ashi Ambushers should appear, you need to kill them for the Encrusted Silithid Object to drop
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: Looted 8 times to see if it would work but nothing.

**Comment by kamicolo** [comment]
Fixed: http://wowascension.com/forum/showthread.php?tid=916
