### ISSUE TITLE
Electropellers

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#173]
Name: Dhanae
Account Name (for vote points rewards): Daemion
Map & Area: Darkshore
How to replicate the bug: accept the quest
What happens: player reported to me that despite fishing for over 45mins for these they do not drop.
What should happen: they should drop alongside fish when fishing
Located on WoWHead Map (if applicable):http://db.vanillagaming.org/?quest=1580#wh-comments
Source (proof, if applicable): 

Extra Information:

Confirmed - I tried this, I have max fishing skill yet did not catch any at any of the commented places in over 2 hours of fishing.  Are these even on the loot list?

**Comment by scotty0100** [comment]
Should now be fixed, marking as fixed. Please close when fully tested on Starix.

**Comment by Skylark14** [comment]
Tested on Starix - Working fine
