### ISSUE TITLE
NPC - Warsong Outrider

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#175]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Nightsong Woods - Ashenvale
How to replicate the bug: 
What happens: 
What should happen: 
Located on WoWHead Map (if applicable):
Source (proof, if applicable): http://db.vanillagaming.org/?npc=12864#wh-comments
http://www.wowhead.com/npc=12864

Extra Information:  Warsong Outrider should be Female, not Male

**Comment by scotty0100** [comment]
She is now a female now!

**Comment by kamicolo** [comment]
closing as this has been fixed
