### ISSUE TITLE
Quest - Stinky's Escape

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#179]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Dustwallow Marsh
How to replicate the bug: accept the quest
What happens: nothing
What should happen: you sohuld escort him for him to escape the raptors area
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by kamicolo** [comment]
NPC escort path still seems odd minor issue but it works

**Comment by scotty0100** [comment]
Tested today. Working, going up the hills his pathing isn't perfect. But 99% working so gonna close this.
