### ISSUE TITLE
Druid of the Claw

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#18]
Reported by Skylark:

"Name: Skylark
Area: Ban'ethil Barrow Den
Ojective: kill Rageclaw and use the voodoo charm on him to release his spirit.

What happens: nothing, you use the charm after killing him and the charm disappears but the quest does not complete.  However, if you go back to the questgiver Oben Rageclaw, its shows as complete."

**Comment by scotty0100** [comment]
Now fixed, tested and working.
