### ISSUE TITLE
Quest: Raene's Cleansing

### ISSUE THREAD

**Issue by Hushness** [scotty0100/wowascension-issues#181]
Name: Hush
Account Name (for vote points rewards): Hush
Map & Area: Ashenvale
How to replicate the bug: Hand in Raene's Cleansing at Krolg the furbolg
What happens: You do not get Ran Bloodtooths skull back
What should happen: You should get his skull back to deliver to Raene in Astranaar
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

After killing Ran Bloodtooth and looting his skull you complete the quest at Krolg the furbolg. He doesn't give you the skull back however, so in order for you to complete the last part at Raene in Astranaar you have to go kill Ran again and get a new skull.

**Comment by Skylark14** [comment]
This is how it was till a later patch when they changed it to just kill him and get the skull at the same time, guess it was blizz's way of keeping us 'busy' lol

**Comment by Hushness** [comment]
Really? I can't remember that far back, haha. But anyway, when you hand in to Krolg he specifically says that I should go back to my "tribe" and show them the trophy, so logic suggests he shouldn't nick the skull from you.

**Comment by Skylark14** [comment]
Thats true, it could be classed as a 'bug' as was suggested on this post: http://db.vanillagaming.org/?item=5388#wh-comments but as the part of the quest doesn't mention you get his skull when you actually kill him for the first time just the next part it does suggest you have to kill him again, I agree it would be better to get his skull when you first kill him but blizzard did have an odd sense of humour so maybe that was intented.  I do remember that later in vanilla it was done so you just get his skull on the first kill though.

**Comment by Hushness** [comment]
But since the part of the quest doesn't mention the skull it makes no sense that Krolg takes it either then, does it? It drops when you kill him the first time, so it should still be in your bag when you get the part where you go back to Astranaar, especially since Krolg comments on it in the next part he gives you. Makes no sense otherwise, odd Blizz humour or not. Sorry, I'm nitpicking but only cause I was tired and didn't notice the skull was gone before I was back in Astranaar.. Haha.. It's a BUG! :p

**Comment by Skylark14** [comment]
lol thats ok, it didn't drop when both me and Moh did this quest again for the guide nor for my druid.  I remember several quests that were streamlined a bit later, the previous part of this with the rod and pommel are the same where you get one part at a time but was later changed so you could get both parts before returning to Shael'Dryn.  I'll mark up the quest anyway so it can be checked out :)

**Comment by kamicolo** [comment]
has been fixed closing
