### ISSUE TITLE
Tooga's Quest

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#182]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Steamwheedle Port
How to replicate the bug: accept the quest in a party
What happens: quest does not complete when you get Tooga back to Torta if your in a party, the person who started it does get it complete
What should happen: it should complete whether your in a party or not
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by kamicolo** [comment]
Closing this and place in under a new issue as this issue is general and affecting more quests.
