### ISSUE TITLE
Quest - Cuergo's Gold

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#185]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Land's End Beach - Tanaris
How to replicate the bug: click on the mast
What happens: nothing
What should happen: once you click on the mast, pirates should appear, you kill them for Cuergo's Key and the chest should appear
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://db.vanillagaming.org/?quest=2882#wh-comments

Extra Information:

**Comment by Matten123** [comment]
still bugged

**Comment by kamicolo** [comment]
Fixed: http://wowascension.com/forum/showthread.php?tid=976
