### ISSUE TITLE
Quest - Crew Under Fire

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#194]
Name: Dhanae
Account Name (for vote points rewards): Moh
Map & Area: The Ruined Reaches - Azshara
How to replicate the bug: Accept the quest
What happens: nothing
What should happen: You should defend Captain Vanessa Beltis from the waves of Naga
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://db.vanillagaming.org/?quest=3382#wh-comments

Extra Information:

**Comment by scotty0100** [comment]
This is fixed now and has been for a few months. Tested today on Starix and all working OK. Closing.
