### ISSUE TITLE
Quest - Badlands Reagent Run II

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#197]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Thelsamar - Loch Modan
How to replicate the bug: accept the quest
What happens: you only get 1 vessel
What should happen: you should get 3 vessels to get 3 bloods in them
Located on WoWHead Map (if applicable):
Source (proof, if applicable):  http://db.vanillagaming.org/?quest=2501

Extra Information:

marked this as critical since its a profession quest and is for a recipe that cannot be got any other way

Also tried abandoning it and retaking but still only 1 vessel was got from the box

**Comment by Sarbarly** [comment]
Adding that the vessel doesn't seem to work on the Scorched Guardians, it channels for the duration then goes on a 1min CD, but doesn't change into a filled vessel.
The singular vessel problem isn't too bad, as it can be gotten around by abandoning the quest and re-accepting it twice, thus obtaining three vessels
This broken quest is rather a shame as the potion it teaches is very useful.

**Comment by Tobschinski** [comment]
This quest works.
