### ISSUE TITLE
Uniting the Shattered Amulet

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#198]
Name: Dhanae
Account Name (for vote points rewards): Daemion
Map & Area: Serpents Coil - Blasted Lands
How to replicate the bug: use the weapon on the named mob
What happens: nothing, just says invalid target- you can get the mob down to 1% but no further
What should happen: You should be able to use the weapon to kill the mob
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://db.vanillagaming.org/?quest=3627#wh-comments

Extra Information:

**Comment by killerduki** [comment]
says invalid target when i try to use the weapon on them and mobs hit like truck

**Comment by scotty0100** [comment]
Fixed. Will be in next reboot.

**Comment by scotty0100** [comment]
Did find a fix for this; but needs a little bit more testing before going to Starix, so reopening for now

**Comment by scotty0100** [comment]
Fixed and pushed to Starix.
