### ISSUE TITLE
Quest - Beached Sea Creature / Beached Sea Turtle

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#20]
Reported by Skylark:

"Name: Skylark
Area Twilight Shore-Darkshore

On coming across either a turtle or sea creature you can take the quest, it will give you an item which you hand in at Darkshore.  I collected all the remaining ones south of Darkshore and when I got back to Gwennyth Bly'Leggonde to hand in, it shows them complete but the items are missing.  When I took the quest I checked each creature after as when you have the quest it just greets you which is what happened.  I had plenty of bagspace so I know its not that I ran out of room.  

http://imageshack.com/scaled/large/90/q51a.jpg"

**Comment by kamicolo** [comment]
These quests givin will result in a couple creatures giving a duplicate item thus whil you completed 1 quest you cannot complete others and will need to re-pickup the quests which requierd the same item.

**Comment by kamicolo** [comment]
Fixed: http://wowascension.com/forum/showthread.php?tid=941
