### ISSUE TITLE
The Attack

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#200]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Stormwind Keep
How to replicate the bug: accept the quest
What happens: nothing 
What should happen: the robot should be disguised and go into the keep to get Lescovar outside into the garden.
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by scotty0100** [comment]
Fixed and pushed to Starix.
