### ISSUE TITLE
Quest - The Only Cure is More Green Glow

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#201]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Gnomeregan Dun Morogh
How to replicate the bug: use the vial to try to get the High Potency Radioactive fallout
What happens: nothing, you continually just get radiation poisoning
What should happen: you should after a few tries get the High Potency Radioactive fallout
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

Tried on all mobs in the room, even reset the instance and tried again.

**Comment by scotty0100** [comment]
This now works, tested on Irradiated Slime (out of combat when you click, not on a corpse..)
