### ISSUE TITLE
Hints of a new plague

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#203]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: Go'Shek Farm - Arathi Highlands
How to replicate the bug: accept the quest to escort Kinelory
What happens: nothing - it auto completes and you can hand in to Quae
What should happen: you should escort her while she goes through the camp to steal  research Jorell still hasn't sent to Tarren Mill.
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

http://db.vanillagaming.org/?quest=660#wh-comments
Extra Information:

while marked as broken, you can in fact still complete this even though the escort does not take place so not marked as critical.

**Comment by scotty0100** [comment]
This works now.
