### ISSUE TITLE
OOX-09/HL Distress Beacon

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#206]
Name: Dhanae
Account Name (for vote points rewards): Skylark19
Map & Area: The Hinterlands
How to replicate the bug: try to get the beacon
What happens: 
What should happen: according to scource below, some mobs should have 100% droprate.  Despite after about 2 hours of farming for these and doing the quests in the area that also has some of the mobs in them these are not dropping.  Are they on the loottable at all?
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

http://db.vanillagaming.org/?item=8704

Extra Information:

**Comment by scotty0100** [comment]
Checked this out yesterday, and your right it doesn't drop. As with the one in Feralas (OOX-22).

Found the fix for both of these and will be pushed to Starix soon. Adding a fixed tag.
