### ISSUE TITLE
Suntara Stones

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#207]
Name: Moh
Account Name (for vote points rewards): Moh
Map & Area: Grimsilt Dig Site - Searing Gorge
How to replicate the bug: accept the quest
What happens: nothing
What should happen: you should escort Dorius out of the site
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://db.vanillagaming.org/?quest=3367

Extra Information:

**Comment by scotty0100** [comment]
Now scripted and pushed to Starix.

**Comment by Skylark14** [comment]
The RiseObsidian part of this questchain does not work.  You are supposed to place the twilight artifact on the altar and when you click it, it will spawn Lathoric the Black and Obsidian should animate, he does not.  You can kill Lathoric but cannot kill obsidian as it just lays there and although red you get invalid target come up.  As you need both Lathoric's Head and Obsidian's Heart you cannot complete this part.

**Comment by kamicolo** [comment]
Closing this has been fixed
