### ISSUE TITLE
Fish resists efforts to put it back into the water!

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#211]
Name: Moh
Account Name (for vote points rewards): Moh
Map & Area: Fray Island - The Barrens
How to replicate the bug: see picture

What happens: 
What should happen: 
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

![flying fish](https://f.cloud.github.com/assets/4540036/1845259/ae76a370-757b-11e3-8d78-b5087d809f6b.jpg)

Extra Information:

**Comment by kamicolo** [comment]
Closing : https://github.com/scotty0100/wowascension-issues/issues/423
