### ISSUE TITLE
Witherbark Axe Throwers

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#218]
Name: Tootsie
Account Name (for vote points rewards): Skylark
Map & Area: Witherbark Village - Arathi Highlands
How to replicate the bug: engage one of the Witherbark Axe Throwers
What happens: it emotes the wrong text and throw blue check boxes at you instead of axes.
What should happen: 
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

Emotes the text for Gnolls- More bones to gnaw on......

**Comment by scotty0100** [comment]
Both of these have been fixed.
