### ISSUE TITLE
Stranglethorn Fever & The Captain's Chest

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#22]
Reported by Holmie:

"Hello, my name ingame is Holmski and I play a dwarf hunter! 

Found out that Stranglethorn Fever is bugged, I got the 10 gorilla fangs but I can't talk to the troll npc to have him summon the gorilla boss!

Also you can pick up the quest called "the captains chest"x2 at the same time. Guess its some bugged involing a split between horde/alliance here

cya!"

**Comment by Skylark14** [comment]
Fixed.
