### ISSUE TITLE
Paladin Charger Quest

### ISSUE THREAD

**Issue by shaz1300** [scotty0100/wowascension-issues#220]
This is fixed. simply drop and re-take the quest if you don't get your barding from shadowbreaker.

**Comment by Skylark14** [comment]
Ancient Equine Spirit part does not spawn the spirit horse when Tendris Warpwood is killed.  It should be running around beside where you kill Tendris, therefore it is impossible to proceed with this quest.

**Comment by Nelway** [comment]
This is still the case.

What should happen: When you kill Tendris Warpwood (first boss in Dire Maul West) with a paladin in the group that has the quest "Ancient Equine Spirit", the Ancient Equine Spirit should spawn to accept/end that quest and start the one titled "Blessed Arcanite Barding".

What happens: You kill TW but the spirit doesn't spawn.

**Comment by scotty0100** [comment]
Should be fixed now. Please confirm and I will close issue.
