### ISSUE TITLE
UBRS

### ISSUE THREAD

**Issue by shaz1300** [scotty0100/wowascension-issues#222]
Nallyra
shaz1300
Upper-Blackrock Spire
During the raid tonight, one of our party members died and the encounter reset even though the rest of the group were alive and we were fighting mobs at the time.
when the encounter reset, 2 waves of mobs had not de-spawned, i had to log directline and kill the mobs to reset the encounter. then when the rend encounter started he spawned twice. I procceded to kill one on directline so only the proper boss was left, howver once glyth was killed, rend did not spawn and dropped no loot.
Non of the above

**Comment by kamicolo** [comment]
Closing as this aint happening might be related to old server
