### ISSUE TITLE
Mining nodes not spawning

### ISSUE THREAD

**Issue by Nelway** [scotty0100/wowascension-issues#225]
Area: Alterac Mountains & the Burning Steppes

There are no mining nodes spawning at these areas. Alterac should be full of iron, mithril and truesilver nodes while the Burning Steppes should have plenty of small and rich thorium veins, plus some mithril and dark iron as well.

(Account name for vote point rewards: Nelway)

**Comment by Skylark14** [comment]
Mining nodes (along with herbs) have been noted to be low in some areas therefore a thorough compilation by area was done to address areas which have a shortfall etc with Burning Steppes being highlighted as one of those for ores along with some other areas that were noticeably short.  Also respawn times were taken into account.  Until this can be addressed, I would suggest that if you are leveling mining please ask ingame as there are players, who whilst leveling mining, have found the best areas to go or perhaps look at the guide on the forums.

**Comment by kamicolo** [comment]
there are enough nodes laying around closing this
