### ISSUE TITLE
Paladin protection talent - Reckoning not stacking/storing charges

### ISSUE THREAD

**Issue by Nelway** [scotty0100/wowascension-issues#230]
Name: Danrell
Map & Area: Everywhere
How to replicate the bug: Get the Reckoning talent, engage a mob, keep sitting down and don't attack until you received 5 critical hits. At that point, attack the mob and check the combat log for the number of hits you delivered.

What happens: You deliver only 1 extra attack + your base swing

What should happen: Reckoning should store up to 5 charges of extra swings, so after getting critically hit 5 times (without retaliating), your next swing should deliver your base attack + 5 extra attacks, unleashing the built up charge.

Source (proof, if applicable): http://www.wowwiki.com/Reckoning_Bomb

(Account Name (for vote points rewards): Nelway)

**Comment by kamicolo** [comment]
This is the original Intention of the spell. to only have 1 attack refering to the tooltip text. It wasn't intented to stack endless with no duration they made a new mechanic and make it stack to a limit of 5 times but they reworked the whole talent spell when they did so. rejecting this issue due the fact paladins will abuse a mechanic what was not blizzards intention as they realized and fixed straith after. when it was known
