### ISSUE TITLE
BRD - Quest for Dark Iron Ore Smelting - Gloom'rel

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#231]
Name: Moh
Account Name (for vote points rewards): Moh
Map & Area: BRD - Summoner's Tomb
How to replicate the bug: speak to Gloom'rel 
What happens: nothing, you cannot hand in the required items
What should happen: you should be able to hand in the required items and get taught how to smelt dark iron
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://db.vanillagaming.org/?npc=9037#wh-comments

Extra Information:

marked critical as Dark Iron bars are needed for fire resis gear.

**Comment by scotty0100** [comment]
Fixed today. Chalice was spawning in wrong spot, confirmed with Moh that it's fixed.
