### ISSUE TITLE
The Missing Diplomat Quest 

### ISSUE THREAD

**Issue by Krysa** [scotty0100/wowascension-issues#236]
Name: Krysa
Account Name (for vote points rewards): Isole
Map & Area: Menethil Harbor

How to replicate the bug: After speaking to Mikhail in Menethil, he asks you to defeat Tapoke Jahn.  Accept quest, catch Tapoke, and defeat him and his friend.  Complete quest with Mikhail.

What happens: After talking to Mikhail, nothing happens.  There is no further quest line.  Tapoke Jahn is still where I defeated him and will not talk to me, and Mikhail has no other quests for me.

What should happen: Tapoke should tell me they took the King of Stormwind, so I can go back to tell Mikhail.

Update: Looks like just an excessively long reset. I stuck around for 10-20 minutes, and nothing changed above, but came back a couple hours later and Tapoke was back in the inn and talked to me.

**Comment by kamicolo** [comment]
closing - https://github.com/scotty0100/wowascension-issues/issues/97
