### ISSUE TITLE
Dwarf mount vendor at Amberstill Ranch

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#237]
Name: Skylark
Account Name (for vote points rewards): Skylark
Map & Area: Amberstill Ranch - Dun Morogh
How to replicate the bug: try to buy a dwarf mount
What happens: the text is missing for can I buy from you
What should happen: it should be there
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

only text there is the exchange for the original mounts

**Comment by scotty0100** [comment]
Fixed in previous patch.
