### ISSUE TITLE
Quest - Enchanted Gold Bloodrobe

### ISSUE THREAD

**Issue by Krysa** [scotty0100/wowascension-issues#238]
Name: Krysa
Account Name (for vote points rewards): Isole
Map & Area: Booty Bay
How to replicate the bug: I'm at the second to last step of the quest where I need to get the fine gold thread from Xizk in Booty Bay (plus the soul shard and smoldering coal - got those) to bring back to Menara in Ratchet.  I already brought a gold bar to Xizk in a previous step, and he told me to come back later.
What happens: Xizk has a white exclamation mark over him.  He won't give me my gold thread.  My research says the minimum quest lvl is 31, and I'm 34.  Also, I've done everything else in the main quest chain, so this subchain shouldn't be different.
What should happen:  Xizk should give me the fine gold thread to complete my quest items.

External link to quest: http://db.valkyrie-wow.com/?quest=4784

**Comment by Skylark14** [comment]
could have the wrong level tag on this as it should be level 31 to complete, it does say requires level 31 to complete but says level 38 on the quest so its possible that the requires is tagged at 38 as well.

**Comment by Krysa** [comment]
I visited Xizk at level 49 and he had the gold thread for me.  So it looks like the quest level for Xizk's part is set incorrectly, at somewhere between level 37ish (the last time I remember being in BB, and he had no thread) and 49.

**Comment by Tobschinski** [comment]
The minimum level for each step is (now) 31.
