### ISSUE TITLE
Dodge And Parry and Block

### ISSUE THREAD

**Issue by shaz1300** [scotty0100/wowascension-issues#239]
Name: Directline
Account Name (for vote points rewards):  N/A
Map & Area: N/A
How to replicate the bug: Spoke to Omler and it seems that after i completed his transfer and boosted him to level 60, when he trained dodge and parry and block they were stuck at 0 and wouldn't increase. verified on 2 level 56 elite mobs, weapon skill and defence were increasing but not dodge, parry or block. i manually changed the values to 300.
What happens: 
What should happen: 
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by scotty0100** [comment]
This issue can now be fixed by the player using the 'Character Skill Fixer' service on the website.
