### ISSUE TITLE
Extinguishing the Idol

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#24]
Reported by Skylark:

"Name: Skylark
Area: Razorfen Downs
Objective: Escort and defend Belnistrasz while he works.
What happens: Only completed for some of the party when he had finished while all had accepted the quest.  The guy then died so we had to reset to hand in for those it had completed for.
What should happen: It should complete for all the party."

**Comment by kamicolo** [comment]
closing: https://github.com/scotty0100/wowascension-issues/issues/428
