### ISSUE TITLE
Warrior sunder being overwritten

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#242]
Name: Moh
Account Name (for vote points rewards): Moh
Map & Area: general
How to replicate the bug: get two tanks apply sunder
What happens: one is being overwritten, it should not be reapplied by another warrior and the original sunder stack(s) lost.
What should happen:an enemy target can have a sunder up to 5 times stacked from a tank, if another warrior uses sunder armor it either adds a stack unless its stacked up to 5 times already in that case case it will just refresh the duration on the target. This isn't happening.

Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

This would apply to all types of dots

**Comment by scotty0100** [comment]
Fix applied on Zeus and was tested. Will hopefully get pushed to Starix soon.
Added Fixed tag but not closing until on Starix.

**Comment by kamicolo** [comment]
https://github.com/scotty0100/wowascension-issues/issues/328
