### ISSUE TITLE
Deep Run Roundup

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#25]
Reported by Skylark:

"Name: Skylark
Area: Deeprun Tram

Objective: Use the flute to enthrall 5 rats and take them back to Monty

5 rats are enthralled but when you take them back to Monty the quest does not complete.

What should happen: Once you get all 5 rats to Monty, quest should complete."

**Comment by scotty0100** [comment]
Applied fix, testing next patch before closing.

**Comment by Skylark14** [comment]
Fixed

**Comment by scotty0100** [comment]
Completed today and worked fine. Closing.
