### ISSUE TITLE
Missing Hunter Pet

### ISSUE THREAD

**Issue by dubrul** [scotty0100/wowascension-issues#251]
I logged in today and cannot summon the pet. I deleted the WDB and nothing. I also don't have my second pet in the stable.

**Comment by dubrul** [comment]
Name: Dubrul
Account Name (for vote points rewards): Dubrul
Map & Area: Feathermoon Stronghold
How to replicate the bug: 
I logged in today and cannot summon the pet. I deleted the WDB and nothing. I also don't have my second pet in the stable.
What should happen: get a pet
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

Extra Information:

**Comment by Skylark14** [comment]
moved this to current thread https://github.com/scotty0100/wowascension-issues/issues/125
