### ISSUE TITLE
NPC - Firebrand Darkweaver

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#255]
Name: Moh
Account Name (for vote points rewards): Moh
Map & Area: LBRS
How to replicate the bug: engage the above
What happens: see screenshot - Damage output is far too high on Curse of the Firebrand and Mark of Flames
What should happen: output should be as per abilities shown on the dbase
![firebrand mark of flames](https://cloud.githubusercontent.com/assets/4540036/2535817/933073c6-b594-11e3-9ebc-adca0c8ce190.jpg)

Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://wowascension.com/wowhead/?npc=9261#abilities

Extra Information:

**Comment by kamicolo** [comment]
didn't happen anymore during new server
