### ISSUE TITLE
Plagued Lands

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#26]
Reported by Skylark:

"Name: Skylark
Area: Darkshore
Quest objective: Place a trap and lay it on the ground.  Any Rabid Thistle Bear that crosses the light shall become docile for a short while, you must lead it back to Tharnarium.

What happens:  Bear does not become docile after walking over the trap and stays hostile.

Also if you fail to capture a bear and lose the trap you are supposed to be able to request another one from Tharnarium.  He does not give you that option."

**Comment by scotty0100** [comment]
Should be fixed next patch. Thanks.

**Comment by Skylark14** [comment]
Trap now works except you have no timer to show time left to get the bear to Treetender so it despawns if you've got one further out.  Also on getting to Treetender, bear just despawns and the quest does not complete.  Treetender should let you hand in the quest and then kill the bear and then give you the follow up to kill rabid thistle bears and then the den mother. Being unable to do this quest means you cannot complete the chain of them.

**Comment by scotty0100** [comment]
Now works tested on Starix today.
