### ISSUE TITLE
[7] Twisted Hatred (Dolanaar, Teldrassil)

### ISSUE THREAD

**Issue by Orcozzio** [scotty0100/wowascension-issues#261]
Name: Gnocca
Account Name (for vote points rewards): Orcozzio
Map & Area: Teldrassil, Dolanaar, Fel Rock

How to replicate the bug: just try to enter the cave with a low level char
What happens: 4-5 mobs come out the walls aggroing you right away... trying to escape outside you can see them coming out of the side of the hill... like it was open field... I managed to kill the first group and a new one went in short after going deeper into the cave... keeping to the left... the tunnel that goes where the boss is was empty so I think all mobs that was there got aggroed in 2 pulls. I could not venture deeper because my pet (I'm hunter) stopped following me and started running to the exit...
Tryed again 2 times... sometimes the pet looks like levitate over the floor, walking into the air... also the respawn rate of mobs is pretty fast... 

What should happen: mobs should not aggro you from inside the cave and you should be able to pull them 1-2 each time... 

Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: the issue having more mobs than was expected into all caves and dens is known already, but inside this one mobs take also strange routes not following the cave profile... as I said... almost like it was open field...

**Comment by Orcozzio** [comment]
EDIT: I managed to finish the quest taking different paths while inside the cavern... also when pet stopped to follow me I selected a target and pulled a mob that was further inside... using the "Pet Attack" ability... even following strange routes, half running, half swimming in the air, the pets was able to reach the target... most of the times... I found also a couple of mobs in evade

**Comment by Skylark14** [comment]
This was already report in an earlier report #59.  Please add comments to that one.
