### ISSUE TITLE
hunter's pet happyness

### ISSUE THREAD

**Issue by Orcozzio** [scotty0100/wowascension-issues#262]
Name: Gnocca
Account Name (for vote points rewards): Orcozzio
Map & Area: 
How to replicate the bug: feed the pet using proper level food and see how much time it stay "happy" (125% dps, gaining loyalty) before it become "content"

What happens: in poor words you need really too much food to keep pet happy

What should happen: I don't know the exact timers on the feeding pets mechanic, but for a pet level 60 one stack of food was more than enough to keep him "happy" during a raid of 4 hours, so I should say 1 piece of food of his level should keep him happy for at last 15-20 minutes

Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by Nelway** [comment]
When your pet is newly tamed and its loyalty level is still low, it'll keep growing unhappy very quickly and consume a lot of food (especially at rebellious level) until it reaches higher loyalty levels. 

That's normal and working as intended. But don't worry, pets do consume very little food at higher loyalty levels.

**Comment by Orcozzio** [comment]
You are right... I went checking old forums on hunters and was about to delete this post... This is how pets worked in vanilla and maybe in TBC too...
