### ISSUE TITLE
[10] The Temple of the Moon (Darnassus)

### ISSUE THREAD

**Issue by Orcozzio** [scotty0100/wowascension-issues#263]
Cannot find the quest into the database http://db.wowascension.com/?quests=1.141

As already reported in https://github.com/scotty0100/wowascension-issues/issues/13 this quest originally was optional and I found old forums describing the chain... In my opinion is better if the quest starts this way so you cannot miss the 1st (optional) step getting full rewards from completing the whole chain.

**Comment by Skylark14** [comment]
Duplicate - please post comment on the original report.

**Comment by Orcozzio** [comment]
done... closing
