### ISSUE TITLE
Moonkins in Darkshore skinnable

### ISSUE THREAD

**Issue by Orcozzio** [scotty0100/wowascension-issues#264]
Name: Gnocca
Account Name (for vote points rewards): Orcozzio
Map & Area: Darkshore

How to replicate the bug: being a skinner, kill any Moonkin

What happens: you are able to skin them

What should happen: They are classified as humanoids and cannot be skinned... 
http://www.wowhead.com/npc=10158
http://www.wowwiki.com/Humanoids "Cannot be skinned, with the exception of yetis and worgen."

Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by Skylark14** [comment]
There are some versions of moonkin that are skinnable and are classfied as monsters. http://db.wowascension.com/?npc=10158#skinning.

Wowhead and wowwiki entrys were updated in cata so its not always helpful using these for reference.

**Comment by Orcozzio** [comment]
Well... I'm not saying that this is a "bug", but since I played vanilla almost half of my toons was skinners and I never was able to skin a Moonkin... I don't mind to skin them in Ascension... let's see if anyone else also remember about this...
