### ISSUE TITLE
Carnivous the Breaker - Darkshore - rare level 16

### ISSUE THREAD

**Issue by Orcozzio** [scotty0100/wowascension-issues#265]
Name: Gnocca
Account Name (for vote points rewards): Orcozzio
Map & Area: Darkshore

How to replicate the bug: is a rare mob, Furbolg type, level 16.

What happens: I found him walking on the road to Ameth'Aran. I was on hunter lvl 15, my pet is a cat lvl 14 with 470 hp. I have almost 300 hp at level 15. It killed my pet in a matter of seconds and me in 2 hits...

What should happen: As far as I can remember rare mobs was not stronger than normal ones... just rare spawn with better drops... this one hits very hard... too hard for its level and too hard to be only a "rare" mob... maybe even an elite mob at its level doesn't hit that hard

Located on WoWHead Map (if applicable):
on wowhead you can see the new version of this mob... probably changed with cata...
http://www.wowhead.com/npc=2186#comments

Source (proof, if applicable): 

Extra Information:

**Comment by Skylark14** [comment]
He was always a tough one in early vanilla.  He uses the ability thrash which gives him 'two swing's. His damage is listed as: 156 - 186 so if you imagine him swinging twice on you at almost 300hp then killing you in two blows would be correct. He is also listed as elite at this time in vanilla. There are a lot of rares out in the world that are tougher than others (blackmoss the Fetid being one).  It wasn't until later when some elite rares were untagged elite and so were easier to kill.
http://db.wowascension.com/?npc=2186#abilities

**Comment by Orcozzio** [comment]
Ok so the only way to know what type of rare is to check wiki before trying...
