### ISSUE TITLE
[17] The People's Militia - Dagger Hill - pet's glitches

### ISSUE THREAD

**Issue by Orcozzio** [scotty0100/wowascension-issues#267]
Name: Gnocca
Account Name (for vote points rewards): Orcozzio
Map & Area: Westfall - Dagger Hill

How to replicate the bug: playing hunter with pet

What happens: after a kill, sometimes the pet looks like starting running in a random direction... sometimes it disappear running in the air... they are only graphical glitches very similar to those, already reported, that happens when you use Pet Command: STAY. So far, questing in Westfall, I saw this happening only onto Dagger Hill. There are only humanoids type mobs here and they often try to flee when low on health... when this happens, often you see them running into a direction, but they are really running in the opposite direction... using a pet you can see where they are really going because the pet keep following them...

What should happen: What You See Should Be What Is Happening

Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by Faraday1** [comment]
This is a issue we're aware of and has been reported earlier. https://github.com/scotty0100/wowascension-issues/issues/45
