### ISSUE TITLE
Improved Shield Block doesn't work

### ISSUE THREAD

**Issue by tardmonkey** [scotty0100/wowascension-issues#268]
Name: Tardmonkey
Account Name (for vote points rewards): tardmonkey
Map & Area: general
How to replicate the bug: Get a warrior with Improved Shield Block and try it on some Raid
What happens: Improved Shield Block's buff display that you can block 2 attacks but it removes after only 1 attack taken
What should happen: Improved Shield Block should block 2 attacks
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

Only tested with 3/3 Improved Shield Block

**Comment by Hushness** [comment]
Did some extensive testing on both low and high level mobs. Both stacks are consumed on damage after activation, only works when you do a full block. Partial blocks cancels out both charges of Improved Shield Block.

**Comment by Skylark14** [comment]
Previously reported https://github.com/scotty0100/wowascension-issues/issues/56
