### ISSUE TITLE
Warlock skill: Health Funnel

### ISSUE THREAD

**Issue by Hushness** [scotty0100/wowascension-issues#279]
Name: Hush
Account Name (for vote points rewards): Hush
Map & Area: -

How to replicate the bug: Activate Health Funnel on any pet out of combat

What happens: The pet keeps doing circles around you while funneling

What should happen: Pet should stand still while funnel is active

Located on WoWHead Map (if applicable): -
Source (proof, if applicable): -

Extra Information: This happen only out of combat, in combat this works as it should be. Seems to have appeared after the migration to the new server. The pet stops doing circles if you keep your right mouse button pressed down for a second.

**Comment by kamicolo** [comment]
closing this is fixed
