### ISSUE TITLE
Teldrassil, Fel Rock cave NPC aggro

### ISSUE THREAD

**Issue by dewhound** [scotty0100/wowascension-issues#281]
Name: Paul
Account Name (for vote points rewards): dewhound
Map & Area: Fel Rock cave in Teldrassil
How to replicate the bug: Enter cave
What happens: NPC's from cave center run out and attack (5-7 NPC's)
What should happen: only the NPC's at the enterance should attack
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by Faraday1** [comment]
Greetings, Paul. This issue has been reported before in https://github.com/scotty0100/wowascension-issues/issues/59 so please add further comments to that report.
