### ISSUE TITLE
AQ20 - Rajaxx

### ISSUE THREAD

**Issue by Hushness** [scotty0100/wowascension-issues#283]
Name: Hush
Account Name (for vote points rewards): Hush
Map & Area: AQ20
How to replicate the bug: Start the Rajaxx encounter by talking to Andorov
What happens: Andorov and his men follows the script, but when the waves come they don't attack
What should happen: They should attack the incoming mobs
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

Extra Information: They're just standing there, doing nothing. Apparently, the healers can't heal them either.

**Comment by kamicolo** [comment]
https://github.com/scotty0100/wowascension-issues/issues/291
