### ISSUE TITLE
ZG - Jeklik

### ISSUE THREAD

**Issue by Hushness** [scotty0100/wowascension-issues#284]
Name: Hush
Account Name (for vote points rewards): Hush
Map & Area: ZG
How to replicate the bug: Engage Jeklik
What happens: She only summons 1-2 bats all in all, the bomb bats don't leave a mark on the ground where they throw their fire..stuff either
What should happen: She should summon waves of bats and there should be a visible area on the ground where the bomb bats throw their fire..stuff.
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

Extra Information:

**Comment by Hushness** [comment]
Will create a own thread for each raid, so closing this one.

**Comment by kamicolo** [comment]
https://github.com/scotty0100/wowascension-issues/issues/287
