### ISSUE TITLE
ZG - Bloodlord Mandokir

### ISSUE THREAD

**Issue by Hushness** [scotty0100/wowascension-issues#285]
Name: Hush
Account Name (for vote points rewards): Hush
Map & Area: ZG
How to replicate the bug: Kill Mandokir and then raptor
What happens: Raptor keeps respawning
What should happen: Raptor should stay dead
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

Extra Information: Raptor keeps respawning after a few seconds, we've only tried this when killing Mando first. Not sure if the same thing happens if you kill the raptor first.

**Comment by Hushness** [comment]
Will create a own thread for each raid, so closing this one.

**Comment by kamicolo** [comment]
https://github.com/scotty0100/wowascension-issues/issues/287
