### ISSUE TITLE
ZG - Gurubashi Blood Drinkers

### ISSUE THREAD

**Issue by Hushness** [scotty0100/wowascension-issues#286]
Name: Hush
Account Name (for vote points rewards): Hush
Map & Area: ZG
How to replicate the bug: Engage Blood Drinkers
What happens: They don't heal themselves when melee is close
What should happen: They should do an aoe blood drinking effect, healing an amount based on melee around the mob. 
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

Extra Information:

http://db.wowascension.com/?npc=11353

**Comment by Hushness** [comment]
Will create a own thread for each raid, so closing this one.

**Comment by kamicolo** [comment]
https://github.com/scotty0100/wowascension-issues/issues/287
