### ISSUE TITLE
Pets don't swim

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#29]
Reported by Raewhen:

"Pets Dont Swim
Area: Anywhere with water deeper than knee deep
How to Replicate: Be a Hunter, Tame a pet (specifically mine is a bear), Go swimming
What happens: Bear refuses to swim, instead runs along the bottom of the ocean regardless of deapth or even mobs agroing me.
What should happen: Pet stays near me at my current deapth."

**Comment by scotty0100** [comment]
This is now fixed on a recent patch a week or so ago. The pets swim by your side, but some pets have a bit buggy swimming animations. Not sure if that's really fixable.
