### ISSUE TITLE
Taming the Beast

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#290]
Name: Legs
Account Name (for vote points rewards): Hush
Map & Area: Teldrassil
How to replicate the bug: try to tame a Nightsaber Stalker
What happens: nothing - it comes up invalid target
What should happen: you should be able to tame it for the second part of the questline
Located on WoWHead Map (if applicable):
Source (proof, if applicable):
http://www.wowhead.com/npc=2043#comments

Extra Information: This creature has no tag.  It should be tagged beast and be tameable

**Comment by Skylark14** [comment]
This creature was tameable before as I did this quest on my hunter, somehow the tag has been removed so now makes this quest/questline broken as you need to tame this specific creature to carry on the questline.

**Comment by scotty0100** [comment]
Just tested this on Zeus and Starix and it works?

**Comment by Skylark14** [comment]
didn't yesterday, I went over on my hunter gm char and the nightsaber was untagged - it should be beast,  and  I was getting invalid target

**Comment by Hushness** [comment]
Hello, I just went back and tried to tame one normally. They don't have their proper classification, doesn't show up on my enhanced tooltip like every other mob and the result is still this:

<a target="_blank" href="https://imageshack.com/i/ndojt3bj"><img src="http://imagizer.imageshack.us/v2/1024x768q90/841/ojt3b.jpg" border="0"></a>

**Comment by scotty0100** [comment]
Unable to replicate on my client. Tested quite extensively with Skylark and we can't figure out why it's working for me and not you two. We tried with no addons as well. But the database is correct.

**Comment by Hushness** [comment]
Deleting the WDB folder sorted this.

**Comment by Skylark14** [comment]
I only had to delete the creature.wdb file
