### ISSUE TITLE
AQ Bugs

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#292]
Boss - Kurinnax

Name: Xanestra
Account Name (for vote points rewards): Skylark
Map & Area: AQ20
How to replicate the bug: Engage Kurinnax
What happens: The Sand Traps appear and instantly apply the silence debuff
What should happen: The Sand Traps should grow slowly over a few seconds and once grown should thenapply the silence debuff
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

Extra Information:

**Comment by kamicolo** [comment]
https://github.com/scotty0100/wowascension-issues/issues/291
