### ISSUE TITLE
Class - Paladin - Spell: Seal of Command (inline - Talent: Vengeance)

### ISSUE THREAD

**Issue by Legendary2008** [scotty0100/wowascension-issues#294]
Name: Legendary
Account Name (for vote points rewards): Garfield
How to replicate the bug: Vengeance talent (retribution) does'nt work correctly
What happens: When Seal of Command crit, Vengeance doesnt proc
What should happen: After any spell or meelee crit Vengeance should proc
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by kamicolo** [comment]
tested this it does proc so reject and closing
