### ISSUE TITLE
Craftsman's Writ - Eastern Plagelands

### ISSUE THREAD

**Issue by Emayn** [scotty0100/wowascension-issues#295]
Name: Estyn
Account Name (for vote point rewards): Emayen
Map & Area: EPL, Lights Hope Chapel
How to replicate the bug: Pick up the quest Craftman's Writ from Dispatch Commander Metz in Lights Hope Chapel
What happens: After abandoning the accepted quest a golden question mark remains over the npc head asking for documents you no longer have (from abandoning the quest).
What should happen: You should be able to retake the quest after handing in another valor token.
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by Tobschinski** [comment]
Do you have any more detailed information about the quest's name? I couldn't reproduce the reported issue.

**Comment by Emayn** [comment]
Hi there,Here's the link for the quest. http://db.valkyrie-wow.com/?quest=9142Basically I took the quest, received a writ for 20 x thorium boots and thought 'no way'. Abandoned quest, destroyed the Sealed craftsmans writ and attempted to retake to get a different quest. http://db.valkyrie-wow.com/?item=22568 shows the other 'Writs' you can get.The npc Dispatch Commander Metz has a golden question mark over his head but I do not have the Writ needed to hand in as I have destroyed/abandoned the quest and items.Let me know if you need more info, I could try to take a screenshot if it helps.
Date: Thu, 15 May 2014 05:08:09 -0700

**Comment by Tobschinski** [comment]
Yes please, any information, especially screenshots and videos, are appreciated. I've taken and abandoned every single quest and have yet to see the reported issue.

P.S. There is no quest for 20 Thorium Boots : )

**Comment by Emayn** [comment]
Alright, I'll try to dig out the screenies. Also, I'll just quickly re-attempt this quest to see where I get. I've been busy and not online for a week but I'll jump on it first chance I get.Thanks for all your hard work :)

Date: Fri, 16 May 2014 08:40:47 -0700
