### ISSUE TITLE
Paladin bugs

### ISSUE THREAD

**Issue by Legendary2008** [scotty0100/wowascension-issues#296]
Name: Legendary
Account Name (for vote points rewards): Garfield

How to replicate the bug: Reckoning (prot tree)
What happens: Gives extra-atack after being the victim of a critical strike, doesn't matter how many critical strike u got, anyway Paladin make just 1 extra-atack

What should happen:Reckoning should stack till 5 extra-atacks

**Comment by Faraday1** [comment]
Greetings, Legendary. This has already been reported in https://github.com/scotty0100/wowascension-issues/issues/230
