### ISSUE TITLE
[H] Eitrigg's Wisdom Quest

### ISSUE THREAD

**Issue by Kerafyrm** [scotty0100/wowascension-issues#298]
Name: Kerafyrm
Account Name: Kerafyrm
Map & Area: Orgrimmar - Thrall's Throne Room
How to replicate the bug: Talk to Eitrigg after you've completed the quest [H] Warlord's Command (for the Onyxia Attunement Quest Chain)

Extra Information:
Ahoy!~

The quest Eitrigg's Wisdom is the 2nd quest for the Onyxia Key Chain for the Horde.  The quest says to "seek wisdom from Eitrigg" who is in Orgrimmar near Thrall.  
His chat bubbles are there in the dialogue window, but when you click them all, you instead "learn how to make Polar Bracers" rather than completing the quest to next talk to Thrall.

Just giving you guys a quick headsup.  Maybe the Polar Bracers will help you be able to Ctrl F and zoom in on the problem. 

Best of luck,

Kerafyrm <3

**Comment by scotty0100** [comment]
Found fix, will be pushed to Starix soon. :)

**Comment by Skylark14** [comment]
Comment from Tatu after the fix:

Hey guys, had time before the game to test Eitrigg's Wisdom. Talked to him, ended the dialog clicks, nothing happened, not even polar bracers. Abandoned quest, went to Badlands and got it again, returned to Org, same thing, nothing happened, Thrall still has his grey question mark over him.

So still needs fixing to move onto the next step.

**Comment by scotty0100** [comment]
Don't know if it was live then. Tested just now and works fine. Closing
