### ISSUE TITLE
NPC - Tinkerer Gizlock Bug

### ISSUE THREAD

**Issue by Kerafyrm** [scotty0100/wowascension-issues#301]
Name: Kerafyrm
Account Name: Kerafyrm
Map & Area: Desolace - Maraudon 
How to replicate the bug: Fight Tinkerer Gizlock

Extra Information: When engaging Tinkerer Gizlock, you can run out of sight and he will not pursue you.  This gives you time to simply wait and replenish mana.This may end up being a universal boss bug; not entirely sure.

Kerafyrm <3

**Comment by Faraday1** [comment]
This seems to be a general LoS problem with many mobs around the world, marking it up though due to it being a boss.

**Comment by Kerafyrm** [comment]
Thanks boss!

Kerafyrm <3

**Comment by kamicolo** [comment]
Quick comment: Might be related with https://github.com/scotty0100/wowascension-issues/issues/423
https://github.com/scotty0100/wowascension-issues/issues/44
