### ISSUE TITLE
Paladin Judgement of the Crusader bug

### ISSUE THREAD

**Issue by edgarsabin** [scotty0100/wowascension-issues#302]
Name: Kaisan
Account Name (for vote point rewards): edgarsabin
Map & Area: Any
How to replicate the bug: Use Judgement of the Crusader(Rank 5), then use Consecrate(Rank 1)
What happens: At level 40, on level 40ish mobs, each tick is doing ~70 damage
What should happen: Each tick should only be doing about 14 damage
Located on WoWHead Map (if applicable): N/A
Source (proof, if applicable): 

Extra Information: Judgement of the Crusader on this server is giving WAY too much of a bonus to holy damage, on most paladin abilities.  For instant damage, it should only be giving ~23% of the stated bonus.  It's instead giving a random amount of damage bonus, from 23% to 100% damage bonus... all on instant abilities.

**Comment by scotty0100** [comment]
Where did you get the 23% from?

From the tooltip it says +110 holy damage http://db.wowascension.com/?spell=20302

Consecration Rank 1 did 23 damage without it, with it: 133 damage.

Looks about right to me unless I'm overlooking something?

**Comment by edgarsabin** [comment]
I apologize if my numbers are not correct.  I am going off of really old info here, and from what I can remember, instant spells get 23% of the spell damage co-effiecent, 1 second - 2 second cast time spells get 43% spell damage, 2-3 second cast time spells get 63% spell damage, and 3 second+ get full spell damage on spell. 

Consecration(Rank 1) http://db.wowascension.com/?spell=26573 should do 64(total) damage over 8 seconds by default.  So each tick is 64 divided by eight  = 8 damage per second with no spell damage.  Currently, on a zero spell damage paladin w/o Judgement of the Crusader I'm getting 20 damage per second, for a total of 160 damage over 8 seconds.  With Judgement of the Crusader(rank 5) on the target, I'm getting 74 damage per second, or 592 damage over 8 seconds, for a total of 528 extra damage over the course of the spell.  All on a rank one spell.  

However, I have noticed this has fluctuated due to the level of the mob I was fighting.  It seems to drop 1-2 damage if I am a higher or lower level than the target.

**Comment by kamicolo** [comment]
dmg is correct: http://wowascension.com/forum/showthread.php?tid=741
