### ISSUE TITLE
[H] Shaman - Mana Tide

### ISSUE THREAD

**Issue by Kerafyrm** [scotty0100/wowascension-issues#305]
Name: Kerafyrm
Account Name: Kerafyrm
How to replicate the bug: Level a Shaman to 60.  Spec into Mana Tide Totem (31 Points into Restoration).  Train the skill.  Drain your mana via spells.  Drop Mana Tide.  You will see no mana will be replenished.

Extra Information: Yeah.  Just a talent in the tree that 100% doesn't work.  It's pretty vital for Shaman raiding.  Because most Shamans aren't specc'd into it yet due to population, it's not a big problem but later on it will be a pain.

Also, I don't want Vote Point Donation Point rewards or w/e.  I just want to see stuff be fixed.  I'm just here to help <3

Kerafyrm <3

**Comment by Skylark14** [comment]
This was already reported on Github https://github.com/scotty0100/wowascension-issues/issues/138
