### ISSUE TITLE
[H] NPC Kaja - Can't Repair

### ISSUE THREAD

**Issue by Kerafyrm** [scotty0100/wowascension-issues#306]
Name: Kaja
Account Name (for vote points rewards): Kerafyrm
Map & Area: Orgrimmar - Shop Next to Auction House
How to replicate the bug: Can't repair
What should happen: Kaja should have a repair option
Source (proof, if applicable): 2 years of Vanilla Retail

Extra Information: Kaja was the infamous NPC on Horde everyone would run to to vendor greys, fix their gear, and quickly check the AH.  Just a quick heads up.

**Comment by scotty0100** [comment]
Has been fixed now for a while.
