### ISSUE TITLE
Drop not intended for alliance in Winterspring

### ISSUE THREAD

**Issue by Sarabande01** [scotty0100/wowascension-issues#307]
Name: Twixybeeble
Account Name (for vote points rewards): Maurilioa
Map & Area: Winterspring, near Hidden Gove
How to replicate the bug: 
What happens: Owlbeasts drop Blue-feathered necklace which is a Horde quest starter
What should happen: shouldn't drop for alliance players
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by scotty0100** [comment]
I have checked drop rate for item Blue-feathered Necklace (Item ID: 12558), and it has condition to be Horde only drop. Please re-open this issue if it continues, but DB values are correct.
