### ISSUE TITLE
Casting mobs 50+ doing insane damage

### ISSUE THREAD

**Issue by sanomi78** [scotty0100/wowascension-issues#308]
Name: Sanomi
Account Name (for vote points rewards): sanomi78
Map & Area: Burning Steppes/Western Plaguelands
How to replicate the bug: fight a casting mob (f.i. Black Broodling in Burning Steppes) around your own level (Black Broodling was 52, and i am lvl 54)
What happens: the mob does insane damage, comparable with what they should do when they crit. Recap says a level 52 Black Broodling did 401 average damage with fireball (with 5 hits), another one of those did 353 in 5 hits. A Skeletal Acolyte (55)near Andorhal did 410 avg from 2 hits of shadowbolt.This is not denoted as crit damage, but rather normal damage. I think this should be about half.
What should happen: casting mobs should do less damage
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: This is ruining my questing experience and should, imo, be a level 1 priority. And maybe, in a non related issue, Blighted Zombies (52) at Dalson's tear do 230 damage (11 hits) really fast. May also be too high. wwwwRotting Cadaver (53) in the same field is doing more normal damage (63 avg 5 hits).

**Comment by Tobschinski** [comment]
https://github.com/scotty0100/wowascension-issues/issues/299

**Comment by sanomi78** [comment]
Tob, not exactly the same. The other post is about mobs doing TOO LITTLE damage, this is about TOO MUCH.

**Comment by kamicolo** [comment]
quick comment: Might not be the same but this a reference to that issue cause that table contains the data and needs to be checked
