### ISSUE TITLE
ghaz'ranka massive geysers

### ISSUE THREAD

**Issue by cowshifter** [scotty0100/wowascension-issues#311]
the geysers ghazranka creates also followed me around auto attacking me. this is after they would blow people into the air.

**Comment by Skylark14** [comment]
I can confirm there were small geysers moving around.  According to wowwiki this is not one of the abilities: http://www.wowwiki.com/Gahz'ranka

**Comment by kamicolo** [comment]
closing: https://github.com/scotty0100/wowascension-issues/issues/167
