### ISSUE TITLE
Quest - Waking Legends

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#314]
Name: Skylark
Account Name (for vote points rewards): Kaci
Map & Area: Shrine of Remulos - Moonglade
How to replicate the bug: Try to hand in the quest Waking Legends from the Nightmare Engulfed Object
What happens: Remulos does nothing so you cannot complete it
What should happen: He should complete it so you can get the reward

Located on WoWHead Map (if applicable):
Source (proof, if applicable):
http://imgur.com/u2eYhnD
http://imgur.com/MnRo2nA
http://imgur.com/SVmHzuH
http://imgur.com/PdoYxY9

Extra Information:

**Comment by scotty0100** [comment]
Confirmed needs ScriptDev2 support. Added label.

**Comment by scotty0100** [comment]
Was fixed a while ago but tested today on Starix, working fine. Closing.
