### ISSUE TITLE
OPEN : Fleeing Mobs

### ISSUE THREAD

**Issue by ghost** [scotty0100/wowascension-issues#316]
Name: Antarager
Account Name : Atlen
Map & Area: Multiple areas ( currently tested in Westfall , though reported by others in different locations ) 
How to replicate the bug: Attack any mobs capable of "Fleeing in Terror " 

What happens: Fleeing mobs ignore most if not all movement restricting ( Hamstring etc) , as well as flee prevention skills, spells, etc ( I.E Curse of Recklessness , Judgement of the Righteous).I've personally noticed that Hamstring 40% movement decrease is ignored though the target is still debuffed when the Flee occurs.  I've been told that CoR and JoR are also ignored. Though have not tested personally. This may be as well occurring with other prevention methods. 

What should happen: Fleeing enemies should be affected by the above as well as other prevention methods when the 20% Flee occurs.

EDIT: The Movement impairment of Hamstring seems to take effect if reapplied AFTER the Flee begins. Though the mob is already debuffed. There is also pathing issues ( Ground , walls, opposite directions of shown graphics. ETC ) that seem to occur. Seems the fleeing in itself is apparently the issue.

**Comment by kamicolo** [comment]
CLOSING https://github.com/scotty0100/wowascension-issues/issues/73
