### ISSUE TITLE
Instance - Zul'Farrak (need testing)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#319]
1)  Patrols 
- Any mob that patrols will respawn 15-20 minutes later.  This makes run backs not easy for cloth wearers.
- Most patrols walk at about 200% normal speed
- Many patrols (warrior, shadowcaster even) "can" have a long range charge ability, which can range to about 100 yards or more.  They double hit upon reaching the target, and usually inflict about 800 damage on cloth instantly.  I've only seen this about 20% of the time though.

2)  Antu'Sul
- Does not wait to begin combat before summoning non-Elite / Elite gators one at a time.  Instead, 4-5 non-Elite gators instantly appear at the aggro target, with Antu'Sul still 30 yards from the party, running up to the fight.
- Additional note:  If you move away from your pull position to fight the 4-5 gators, Antu'Sul will reset himself, and go back to his cave.  However, once you kill the gators, you can re-start the fight by pulling him again.  It is important that you engage him with attacks first, along with the gators though.
- Additional note:  Once fight begins, Antu'Sul correctly begins to summon Elite gators to the fight, one at a time, at specific intervals.  This is good.

3)  Shallow graves
- Are spawning not 1 mob, but 2-3 Elite Undead mobs instead. Because of this, the Witch Doctor Zum'Rah becomes much more difficult.
- Shallow graves themselves do not disappear (despawn) after you have defeated the mobs which are brought forth when you walk across them.  The graves should go away.  This is some times done, to make it so that Zum'Rah summoned mobs have to run farther to get to the fight, and that nobody accidentally steps on shallow grave during Zum'Rah combat to bring additional mobs to the fight.

4)  Zum'Rah
- Zum'Rah does not hesitate to summon Elite Undead mobs from the graves.  As soon as engaged, he summons.  Additional summons are about 15-20 seconds apart, which seems about right.
- Because the graves contain 2-3 Elite Undead mons instead of 1, when Zum'Rah summons, you can easily have 3 Elite Undead mob + Boss to deal with instantly.  

Within 15-20 seconds when a second summons is done, you can be looking at a total of 5-6 Elite Undead mobs + Boss.  I've faced this twice.

Note:  None of the party stepped on shallow graves during the fight.
- Skeleton totem.  It is possible that he didn't bring out the totem that summons his skeletons into the fight.  In 3 attempts, I never saw any.  Then again, I was busy trying to tank 5 Undead Elite mobs + Boss.  So, I really wasn't carefully watching.

**Comment by Bilbo79** [comment]
Attaching a link to a screen shot.  This was taken about 30 seconds after the pull. 

There are 4 Elites standing outside the bosses den.  This is where the live ones return to after the fight.  There is 1 additional dead on on the floor in the room.  And the boss.

On the following attempt, he summoned 2 groups of 3 Elites, for a total of 6 Elite mobs + Boss.  

The summoned Elites hit like a truck on 4600 plate armor (level 43) protection warrior.  There is no amount of crowd control I know (Strat Holy water maybe) that makes this fight easier. Most groups are not going to have 4 priests with them for shackles.

The fight is overtuned, and needs some work.  As a comparison, my crew had no issues with stairs event, or Chief Ukorz afterwards.

http://i167.photobucket.com/albums/u132/Bilbo79/Heroic_ZumRah_zpsbd85ae9e.jpg

Also, he does bring out the totem, but none of them seem to summon skeletons.  I've never seen any.

**Comment by kamicolo** [comment]
this needs to be investigated don't just close reports

**Comment by Bilbo79** [comment]
Hello.  

This message is to let you know that I personally closed this report. 

The purpose for closing this report, was to break out each individual issue (listed above), and write it up as a stand alone issue bug report.

This has been done.

Please investigate the individual instance issues instead.  Thank you.

I am closing this.
