### ISSUE TITLE
Gravis Slipknot

### ISSUE THREAD

**Issue by KarlDieter** [scotty0100/wowascension-issues#323]
Name: Dude
Map & Area: Alterac Mountains - Stahnbrad
How to replicate the bug: Have a look at Gravis Slipknot
What happens: The NPC is completely missing a visual model
What should happen: The NPC should have a visiual model
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: 
http://www.wowhead.com/npc=14221/gravis-slipknot
http://www.wowwiki.com/Gravis_Slipknot
Those sides display different models and I suggest wowwiki is correct.

**Comment by Tobschinski** [comment]
![gravis](https://cloud.githubusercontent.com/assets/4753528/3526484/4976a8f6-077c-11e4-8197-3071960775af.png)

I did, but I don't see any problem, except a missing main hand.

**Comment by KarlDieter** [comment]
Shame on me, didn't delete my WDB folder so I'll just assume that's what caused it.
