### ISSUE TITLE
Crucial Fear bug

### ISSUE THREAD

**Issue by KarlDieter** [scotty0100/wowascension-issues#324]
Name: Dude
Account Name (for vote points rewards): Dude
Map & Area: -
How to replicate the bug: Apply fear with warlock(must be mob's target) and taunt with a warrior
What happens: If a mob changes target during fear(most notably with taunt) he will stop his attack and just proceed doing nothing until his attack routine is restarted(after fleeing). This might also apply to other forms of cc. Also the random movement during fear is cancelled.
What should happen: The enemy should attack normally after the end of the fear effect.
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:

**Comment by kamicolo** [comment]
closing: https://github.com/scotty0100/wowascension-issues/issues/73
