### ISSUE TITLE
Quest: Portals if the Legion

### ISSUE THREAD

**Issue by KarlDieter** [scotty0100/wowascension-issues#325]
Name: Dude
Account Name (for vote points rewards): Dude
Map & Area: Desolace / Mannorocs Coven
How to replicate the bug: use the provided item on prtals of the legion
What happens: there is a visual effect on the portals but the actoin won't count towards quest progression
What should happen: guess what
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://www.wowwiki.com/Quest:Portals_of_the_Legion

Extra Information:

**Comment by Skylark14** [comment]
This was already reported on https://github.com/scotty0100/wowascension-issues/issues/144

**Comment by scotty0100** [comment]
Closing as duplicate
