### ISSUE TITLE
Instance - Maraudon (need testing)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#327]
Major Issues ---------------------------

1)  Scepter of Cerebras cannot be obtained. (duplicate issue, already written up).  But since Cerebras does not begin his ritual, no scepter can be obtained.
- No ritual = no Scepter
- No Scepter = no Princess runs

Note:  You can go Princess runs, you just have to clear the Orange or Purple side first, which adds 1/2 an hour to each run;  effectively doubling the effort required to get to Princess.

2)  Creeping Sludge do not creep, they SPRINT.  Moving at roughly 2-300% normal speed, they can easily overtake you running away.  This is major, since they are impossible to melee a pack of 4 of them (as they are encountered on the Orange side).  You can't walk around them.  The proper way to kill them is to kite them.  As it is now, they just run you down and zerg you.  Not fun.  Hope you have a couple of Warlocks in the group.

Minor Issues ---------------------------

1)  Mining nodes, and Ghost mushrooms are all up at once.  Both inside and outside.  5-10x as many as usual.

2)  Noxxion - too many spawns.  Spawns are summoned even when he is up.  I have screen shot of 12 spawns up with him at 75%.  Here it is.  I realize that it is not the most clear, but we wiped for me to get this shot, and it is the best I can do.  But if he is working properly, there should be only 3 spawns up at this time, and he should be self-banished.  The problem is that he stays semi-alive (not self-banished), while the summons are still up.  Throughout the fight, he summons more spawns, even when he is not self-banishing.  We have wiped with as many as 30 or 40 spawns up.  I wish I could have taken a screen shot.

LInk:  http://i167.photobucket.com/albums/u132/Bilbo79/Noxxion_1_million_summons_zps3ef7cee4.jpg

3)  Razorlash has no stacking bleed attack.  This is his signature attack, and without it, he becomes a garden variety plant with just high hit points.

4)  Hydras at bottom on earthsong falls do not Patroll.  Only one pats, and he does not go to the area by the front of the cave entrance.  [ EDIT ] They are OK the way they work.  They actually Blink.  They don't appear to move, but when your party runs by at a safe distance (like 60 yards or so) the Hydra can suddenly teleport to the group, and do their AOE knockback.  Quite un-expected at first really, but a great trade off for proper patrolling.  Once you catch on to this trick you can prepare for it.

Note:  This appears to the be same bug that the patrols in ZF are afflicted by.  Appearance of Blinking or Teleporting long distances to the group.  Perhaps the visual makes it appear they are not moving (pathing) when in fact they really are.  Just not visibly.

5)  Vyletongue Corruption quest object mobs (water elemental looking things) will aggro based on fights with OTHER mobs cleared in the area.  In other words, when the tank cleanses the corrupted flower (thingy), and the water elemental things spawn, they immediately run to the dps and healer.  This is completely unexpected, but easy to duplicate.  How do they have an aggro table when they are spawned?  I have no idea.
- There are 3 elementals in each pack.  I only remember 1-2 Elites, not 3. 

6)  Diemetrodons are not linked properly.  The groups of 3 or 4 do not pull together.  Sometimes none of them are linked.  Some times 2-3 could be.  It should be all of them.

7)  Diemetrodons do NOT have have their AOE silence ability.  This is their signature skill.  Without it, they just become powerless, high hitpoint, speed bumps on the way to Princess.

8)  Behemoths (large giants) just stand around when attacked.  As a matter of fact, if ranged dps opens up on them, they just stand in one place and never attack.  They are like free kills.  I wonder if they even aggro when you walk by?  I did not test this.  But they will melee the tank if initiated by tank.

9)  Landslide does not wait to summon waves of shardlings to help him.  They all get summoned immediately as the fight begins.  Also, only one wave is ever summoned.  I could swear there are supposed to be 2 (at 33% and 66%).

[ EDIT ]  One time (out of 10 attempts) he did summon a second wave.  He was at 5%, and accompanied by the AOE stun, almost wiped the whole party.  Unexpected.

10)  Rock elementals do not Patrol.  They are all supposed to patrol.  This can lead to odd groupings of 2 together.  I have a screen shot of this.  This is 100% reproducible.   On this pull, all rock elementals in this screen shot come together (90% of the time).  In 11 times through, only 1 time did they not.  Hope your group has a Warlock or two.

Link:  http://i167.photobucket.com/albums/u132/Bilbo79/Mara_Rock_Ele_Party_zpscd8b5e94.jpg
- Rock elements already have their shardlings out instead of splitting into shardlings as the fight goes on.  This makes dispatching them trivial.

11)  Rotgrip pathing is not perfect.  He gets hung up on a wall.  We waited 5 minutes for him, and eventually went out and found him bouncing up against a side wall.  He did come off the wall and fight well though when pulled.

That is about it for now.  Everything else works really great.

**Comment by Bilbo79** [comment]
12)  Purple side - stealthed rogue demons (singles).  There are none.  I am pretty sure that there should be some stealthed demons (2-3 in total) which do slowly patrol along a portion of the purple side.  They can ruin your day if you are not prepared for them too.  But we did not see any.

**Comment by kamicolo** [comment]
this needs to be investigated don't just close reports

**Comment by Bilbo79** [comment]
Hello.  

This message is to let you know that I personally closed this report. 

The purpose for closing this report, was to break out each individual issue (listed above), and write it up as a stand alone issue bug report.

This has been done.

Please investigate the individual instance issues instead.  Thank you.

I am closing this.
