### ISSUE TITLE
Quest: Fish in a Bucket

### ISSUE THREAD

**Issue by anduric** [scotty0100/wowascension-issues#329]
Name: Talvos
Account Name (for vote points rewards): Anduric
Map & Area: Shadowprey Village, Desolace
How to replicate the bug: Speak to the NPC Jinar'Zillen, at the docks in Shadowprey Village
What happens: He doesn't hand out the (repeatable) quest, Fish in a Bucket.
What should happen: He should offer the aforementioned quest, which allows you to trade five shellfish for one bloodbelly fish.
Located on WoWHead Map (if applicable): N/A
Source (proof, if applicable): http://www.wowhead.com/quest=5386#. and http://www.wowhead.com/quest=5421

Extra Information: The Bloodbelly fish received from this quest are required to complete another quest in the zone, Catch of the Day, which is given by Nataka Longhorn at Ghostwalker Post.

**Comment by scotty0100** [comment]
This looks to be working as intended.

Nataka offers 'Catch of the Day', which is a pre requirement for the quest 'Fish in a Bucket'.

So going to Nataka first, accepting the quest, then going to Jinar'Zillen you can then get the quest.
