### ISSUE TITLE
Mobs move after death

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#33]
Reported by Dots:

"Name: Dots (Horde)
Area: Everywhere in Tirisfal Glades.
How to replicate that bug: Kill any Scarlet mob, they'll move after death and even aggro
What happens: Mobs die, then move (glide across)
What should happen: Mobs should stay still in one place when dead"

**Comment by scotty0100** [comment]
This has been fixed on a global scale, still happens with Frost Nova & stuns. Which is still open here: https://github.com/scotty0100/wowascension-issues/issues/71
