### ISSUE TITLE
Instance - Sunken Temple (need testing)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#331]
First, let me say that it is amazing how well this whole dungeon is scripted, considering the complexity of the programming in this dungeon.  Great.
- The Undead Spectres which come from the bodies of the trolls killed within Jammal the Prophet's room, do not aggro anyone, follow anyone, or even attack anyone who might be standing in melee range.  I tested this thoroughly.

Not a big complaint since I hate these guys anyway, but it is kind of one of the defining characteristics of this room.
- Morphaz dragon is not linked to the other dragon Hezzaz? (i forget).  So they can be pulled independently.  Not a big deal since they are easy, but it usually gets at least 1 party member killed when they both pull together properly.
- Avatar of Hakkar.  Summons unlimited snakes.  Yes, they are only 2k hp, normal mobs, but at times we had at least 50-75 snakes up.  The summon rate seems high.  

Note:  Our group had 3 mages for AOE, and a Prayer of Healing Priest spamming.  So pulling 20 at a time was not a big deal.  But the final Hakkar pull, he came with 20+ snakes, even though we cleared 3 corners prior, and that was not a easy fight for us.  Normal groups?  I don't know.

Also, the arcane interruptor guys do not path.  1 gets summoned only, and he stands in at the end of the room, unmoving unless pulled.  I _think_ we had to kill these to advance the event, because the 2nd blood carrier did not come out for 5 minutes after the first one died.

Side note:  I can't believe you got this scripted so well.  

Note:  To anyone running ST.  Try not to engage any group while on stairs.  There is a high chance of a mob going behind / underneath steps, being un-seeable, un-targetable, and still able to attack party members.  This happened about 50% of all stair engagements (2-3 times) until I stopped doing it.  Probably a very hard bug to fix.

**Comment by Bilbo79** [comment]
- Also, some of the dragonkin groupings in the large middle room (the one with the bottomless pit in the middle), are not grouped properly, and sometimes do not pull in full groups making it less of a test to pass.  Not a big deal.

**Comment by kamicolo** [comment]
this needs to be investigated don't just close reports

**Comment by Bilbo79** [comment]
Hello.  

This message is to let you know that I personally closed this report. 

The purpose for closing this report, was to break out each individual issue (listed above), and write it up as a stand alone issue bug report.

This has been done.

Please investigate the individual instance issues instead.  Thank you.

I am closing this.
