### ISSUE TITLE
NPC - Rin'wosho

### ISSUE THREAD

**Issue by drisana** [scotty0100/wowascension-issues#332]
Name:Drisana
Account Name (for vote point rewards):drisana
Map & Area:Yo'jamba Isle
How to replicate the bug:Attain honoured rep, and go speak to Rin Wosho the Trader. 
What happens:He has an exclamation above his head, and when you speak to him,, he offers you 10 Essence Mangoes, but when pressing the complete quest button - i get a message saying 'The Item was not found'.
What should happen:He should give me 10 Essence Mangoes
Located on WoWHead Map (if applicable): http://www.wowhead.com/maps
Source (proof, if applicable):http://www.wowhead.com/quest=8196/essence-mangoes

**Comment by Tobschinski** [comment]
You need to have a Zandalar Honor Token in your inventory, the description for that is currently missing.

**Comment by Tobschinski** [comment]
This was fixed a while ago.
