### ISSUE TITLE
Instance - Blackrock Depths (need testing)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#333]
This is probably going to be a long write up.  But we need to get it started now.  Considering the size and complexity of coding in this instance, this could be long.  If you need to break it up, please do so.  If you want me to break it up into individual issues, please let me know, and I will.

MAJOR BUGS---------------------------------
- Secret Safe , can never be opened.  Since the Watchman Doomgrip (who is summoned after you open the 12 coffers) does not drop the key.  That means no loot (good loot too) for opening 12 coffers, and killing 5 [Elites].  This is bad.
- Dark Coffer - Quest - Heart of the Mountain.  Cannot be completed.  Since the Key holder never drops the key, this secret area can never be opened.  The quest item cannot be obtained.
- Burning Essence - which is an element needed to complete "Libram of Resilience"; a really nice +20 FR enchant to Head / Leg slot, also cannot be looted from this, for same reasons.
- Grim Guzzler door - The door works fine, and can be blown open using the ale mug quest, which we did.  The problem is that if you FAIL the Chest of Seven event, then this door closes and locks behind you.  You are forced to hearth (or jump down and fight a bunch of other meaningless mobs to get out).  It is somehow linked to the event.  I think this, because yesterday we only killed Ambassador Flamelash, and a few golem pulls in the room behind him.  But today, we cleared that room, and attempted "The Seven" event a couple of times.  We didn't succeed.  And on the way back out, this door is locked, preventing re-entry to Grim Guzzler.  If you succeed at the event, the door is open.  I've checked.

Note:  Confirmed.  This is linked to the Chest of Seven event.  It is reproducible 100% of the time.
- Shadowforge Flame Keeper room - The respawn on all of the non-elite (we did not live long enough to check out the [elites], mobs is about 15 seconds.  This is about 45 seconds too soon.  In other words, this is a ridiculous respawn rate.  I have no idea how anyone who uses mana completes it to be honest.  60's maybe?  This has to be fixed.  As a matter of fact, if you kill a group and stand over their corpses, you can barely get off a Hearth before they are back up.  Our healer died because he hearthed 5 seconds after the others, and was beaten down by re-spawns.  Unreal.
- Core Fragment - Quest to get access to Molten Core.  The re-spawn on this item apparently either does not happen at all, or exceeds 5 minutes (about as long as we could stand to wait around for).  I could swear the in vanilla there were 5 of these on the wall, one for each party member.  That would be nice if you could put that in.  It doesn't seem right that one party member should get the fragment, and the other 4 should have to do another full BRD run to get a shot at theirs.

Note:  More than one of us needed it on the next run through, so we waited it out.  The timer is actually 10+ minutes.  This is moved up to Major bugs now.  40 minutes is too long for a new party of 5 to wait for everyone to get one.  We actually waited 30 minutes for 3 other people to get theirs.  It was timed.  We used a USA clock, but last time I checked, it worked the same as a UK clock.  :p
- Panzor the Invincible - Does not spawn, ever.  He is supposed to be a Rare that can be found pathing in the Hall of Crafting part of the zone.  But we have never seen him in (11) times through this area.  I will update this number because I am keeping count now, or remove this paragraph as well, if we see him just 1 time.  Too bad, because he has a couple of nice drops. 20% rate should be about right.  Maybe 25%.

MINOR BUGS---------------------------------
- Arena spectators.  You know about it already.  But at least you can walk by the spectators if you have successfully cleared the Arena event.
- Dark Coffer 

a) Dark Keeper portrait.  Does not work.  It shows the same guy every time.  And I cannot find him (the Keeper) in the instance any any of his spots?  Where is he?  Or this is broken.  There is supposed to be 6 random guys, and tells you name and where he is.

b) Coffers (12) each contain no loot.  This is minor deal.
- Hall of Crafting - Some pathing (with the exception of 1 golem mob) is broken.  So groups are in big clumps.  For example, Fineous Darkvire is supposed to path.  Grouping is odd also, with golems standing close to the dwarf miners.
- Arena issues (big and small)

a)  Ok'Thor (arena ogre) is supposed to Polymorph.  He never casts it

b)  Anub'Shiah (thick spider) is supposed to shadowbolt.  But she does not.  She also will never drop the chest piece (Update:  It dropped on the 15 kill.  And she dropped 2 pieces of loot instead of just one.  I am not sure if you put that in there just for me, after reading this, but thanks), but that is RNG for me.  10 boots by the way.

c)  Wiping in the Arena event (and ressing) puts you instantly in combat, as the arena marshal starts the whole event over again with immediately once someone resses.  Not a big issue.  But since you are allowed to res inside the instance here, I am not sure there is an alternative, other than maybe ressing out of range maybe?  I will never try this, since we are over 48 now, and will never die in Arena event again.

d)  The thunder lizard trash are totally wonky.  They appear to be in one place, and can blink to another.  They ignore aggro.  They glide around like a bird, rather than walking.  They have seemingly unlimited distance on their debuff.   Watch these guys.  It is comical.
- Lord Incedius - is supposed to have a knock back ability which he will often use once per fight.  He does not use it.  Too bad, because it is hilarious watching an unprepared tank get punted into the lava.  
- Fireguard Destroyers (elemental) - are supposed to have an AOE instant fireblast ability which hits all members of the party within like 20-25 yards (I forget the range exactly, but ranged dps and healers can stand outside this at 30 yards).  They don't use it.
- General Angerforge - the fight works perfectly really.  The exception is his 4-5 rifleman which stand at his side.  Once the General Angerforge is killed along with these rifleman, and the 4 summons which come in at 20% and the fight is over.  About 20 seconds later his 4-5 rifleman respawn again, in the same spot they start in.  Not a big deal, as most players will be gone.  But we were standing around afterwards checking out loot, and they got one of the clothies; which was kind of a surprise.
- Ribbly Screwspigot - Is friendly.  Cannot be engaged.  The "insult" dialog is available but does not do anything.  He could drop a very nice BS pattern, or a 16 slot bag.  Too bad.

Also, I believe that there is a quest for killing him, which would also be un-attainable.  Update:  There is a quest.  We all did the breadcrumbs to get to him.  But you still can't engage him, even with the quest.  So the quest cannot be completed either.
- Hurley Blackbreath - is not in the Grim Guzzler.  He should be.  And when you break the 3 kegs in the back room, he is supposed to turn hostile, and run over to the room for combat.  He also would have some nice drops.
- The Golem Manufactory - Outside the Golem Lord Argelmach room. Aren't the golems supposed to be targetable or aggro?  I could swear that they were in vanilla.  I am pretty sure of it.  But here, they are not.  Golem Lord seems a bit overtuned.
- Shadowforge Door - Can sometimes close after it has been opened.  It is supposed to stay open.  Not a big deal, but if any party member has to go back out, or if someone new zones in later to join the group, and they do not also have the key, then they cannot get out, nor can they get to the rest of the party.  Someone with the key has to go back and let them out/in.
- Doom'Rel - In the fight with the seven dwarves, if you wipe, and there are any voidwalkers up, then they will return to his side, and respawn as RED color, as soon as the fight is over and he goes back to friendly.  Then, they are un-attackable.  And they remain hostile, and will not despawn.  What this means is that if you try the fight again, when you get to Doom'rel, he will summon an additional 3 voidwalkers and you will be fighting 6 + him.  I have a screen shot with him + 6 voidwalkers if you want.  

Link:  http://i167.photobucket.com/albums/u132/Bilbo79/DoomRel_Voids2_zps0ca06b96.jpg  

Note:  If you wait around about 10 minutes, the VW's will de-spawn.  This is Good.

Note:  The fact that the casters in-game act the way they do; in this fight, it makes it a completely different fight.  They move unpredictably.  Won't LOS properly.  Just stand there not getting any spell off until their target is in LOS or in range, and start nuking.  You have to spend extra time working around them.  On a couple of occasions, they simply bugged the whole fight out for everyone, resetting it.  It is not blizzlike IMO.  But, this is what we got atm.

Warning - Rant:  At the beginning of the 7 fight, without any party member having attacked anything, the first dwarf mob that becomes hostile once the event begins (I forget his name), goes directly for the healer.  No aggro table mind you.  He just does.  Every single time.  I've even let this happen on two occasions to make sure he is hitting the healer first.  This should be fixed.  The first dwarf should aggro the closest target to him if there is no table established.  If the tank does not engage him, he will run right by.  The only way I can see this possible, is if aggro is already existent from a prior fight in another room in the instance?  Of course this is right in line with every single other dwarf in the room after the fight begins, as they all act like sheep; they accumulate healer aggro, and head straight for the healer when it is their turn to come to life.  This makes Doom'Rel (the final dwarf) a real treat.  Essentially the healer tanks the end of this fight (spamming heals to keep themselves and the tank alive).
- Green loot drops - There are practically none in this instance.  On an average run to Emperor, there is often either no green loot drops at all, or 1 or 2 green drop tops (ever) for an entire run, for the whole group to share.  This is completely out of alignment with most all lower level dungeons that you have working right now (use Scarlet Monastery as an example).  And not in alignment at all with vanilla WOW.  It is at best 10-15% of what it should be.  To be honest this was also prevalent in Mauradon also, iirc.  BRD is supposed to be green loot galore for all party members.  In vanilla it is normal for all party members to have 2-3 greens after Greeding on drops during a regular full run.  In 10 times through, we've seen as many blue drops (practically none) as greens.

**Comment by Skylark14** [comment]
"Core Fragment - Quest to get access to Molten Core. The re-spawn on this item apparently either does not happen at all, or exceeds 5 minutes (about as long as we could stand to wait around for). I could swear the in vanilla there were 5 of these on the wall, one for each party member. That would be nice if you could put that in. It doesn't seem right that one party member should get the fragment, and the other 4 should have to do another full BRD run to get a shot at theirs."

There was only ever one core fragment but it was an almost instant respawn on retail.  Currently its set at +5mins which is too long.

**Comment by kamicolo** [comment]
this needs to be investigated don't just close reports

**Comment by Bilbo79** [comment]
Hello.  

This message is to let you know that I personally closed this report. 

The purpose for closing this report, was to break out each individual issue (listed above), and write it up as a stand alone issue bug report.

This has been done.

Please investigate the individual instance issues instead.  Thank you.

I am closing this.
