### ISSUE TITLE
Quest - Ammo For Rumbleshot

### ISSUE THREAD

**Issue by Weeablade** [scotty0100/wowascension-issues#336]
Character Name: Toecrusher
Location: Dun Morogh, northeast of Coldridge Valley
Quest Name: Ammo For Rumbleshot

Quest giver: Loslor Rudge
WHAT HAPPENS: You give the ammo to Hegnar Rumbleshot, quest completes and nothing happens.

WHAT SHOULD HAPPEN:
You hand in the ammo, the quest completes, and a scripted event occurs.
https://www.youtube.com/watch?v=wCe_9PlTKsw.

WHY THIS SHOULD BE FIXED:
A large deal of players come to Ascension for nostalgia, and scenes like this are part of that experience. Enabling old, novel scenes like this will help retention of veteran players.

**Comment by kamicolo** [comment]
Fixed: http://wowascension.com/forum/showthread.php?tid=916
