### ISSUE TITLE
Instance - Stratholme (need testing)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#337]
MAJOR ISSUES ------------------------------------------
- The Unforgiven - Does not exist.  He, and 4 of his undead (non-elite) spectres should spawn in the area between Market Row, and Festival lane.  It is triggered when you walk through the small tunnel between the two areas.  He doesn't.  This is too bad.

MINOR ISSUES ------------------------------------------
- Supply Crate -  We could only find 4 of them that worked.  The other 20 don't.  However they are kind of spread out though, and you can go back to them if you do run out of holy water.  Because they respawn properly.  Note:  This was all areas outside the Live / Dead side.
- Casters can reset themselves.  This is likely due to the bug where they cannot be pulled properly.  Similar issue all other world casters.
- Melee can reset themselves.  This is unrelated to the caster issue.  But I have never seen this before in any instance on this realm (or otherwise).  But several pulls around corners at mid to long distance, a melee mob can (if not engaged in combat at some point), lose interest in chasing you down, reset, and go back to where he started.  This can happen in singles, or multiples.  It is not an "all or none" thing either.  Where some will pull around corners properly, where others decide to not.  It is very unusual.
- Rat traps - The party can walk though them any time they want.  The cages do not drop, and the rats to not come out to attack the party.  
- Large Bound Chest - Between the entrance area to the zone, and the Festival lane, just before the gate (locked) is a chest.  The problem is that it's respwn rate is way too quick.  It is worth noting that the one which is behind where Barthilas runs to, is also respawning too fast.  
- Rockwing Gargoyles / Screechers - The respawn rate is about 5 minutes on them.  Which is way too fast.  This may make up for the fact that we have not seen the Eye of Naxx yet.   I realize this is probably trivial for pro's who have done this at 60 a bunch.  They just zip right by and never look back.  But for 56-57 trying to slowly learn the place, this is kind of odd having these guys continually respawning and flying over 2-3 of their own corpses to hit you up during boss fights.  I have a screen shot of 2 of them (unlooted, hoping that would slow them down).  One killed right before pulling Maleki, and one that appeared right after the kill.  Really odd.

OK, regarding the gargoyles, I got around to marking them up individually.  And after watching them respawn, it appears that there are 4 sets (of two) gargoyles that cycle, and NOT the same gargoyles.  What that means, I think, is that they are in fact on the proper respawn timer.  But there are 4x as many of them as there should be.  If you kill a set, there is a 5 minutes before the next set takes their place.  If you leave them up, then the other sets never spawn.  If you beat down all of them, you will eventually get the ones with the raid markers on them respawning again.  4 sets.  More feedback, after more runs.  But that is all we have for now.

QQ inc - Haha, our group has wiped 6 times in the last 1.5 hours on the dead side, and every single time it was to a gargoyle which we had already killed.  Ha!  We are only now on Maleki, and it feels like we have spent more time going corpse runs than actual instance. Boo hoo!  :)
- Stonespine is on a 45 minute respawn timer.  I am not sure, but I don't think he is supposed to respawn.  I have a screen shot of us killing him the 2nd time, with the rest of slaughter square in the background with corpses.

**Comment by Skylark14** [comment]
Hearthsinger Forresten - Does not exist. There are 3 possible spawn points for him, and he is guaranteed to be up in one of them. We cleared all areas, and he was in none of them. Too bad. He is not hard to kill, but he also has some nice drops.

He does exist, we've killed him several times, he's based in the live part of strat.

Eye of Stratholme - actually called eye of Naxrammas does appear and summons gargoyles

**Comment by Tobschinski** [comment]
Which undead creature shouldn't be there?

**Comment by Bilbo79** [comment]
Well, this is from memory only.  So, I am probably off, in regards to the # of undead mobs.  It is not that I think that there are any UD that are not supposed to be there.  Rather, the groups are composed of more UD than I remember.

Back when Stratholme used to be a raid, I remember a large number of mobs like this.  But it was run by 10 people.  When it was reduced to a 5-man instance, it still remained very difficult.  Especially the 45 minute run part.  But the # of mobs was reduced to be more conducive to a 5-man.  

At least that is what I remember.  Again, I am old so I forget a lot.

**Comment by Tobschinski** [comment]
![gauntlet](https://cloud.githubusercontent.com/assets/4753528/3874479/2e715b98-2142-11e4-8034-c6ef2a0de474.jpg)

and https://www.youtube.com/watch?v=9JGQjpK6PFE taken in BC.

**Comment by Bilbo79** [comment]
Thank you for posting the nice map. 

I should have been more clear with my casual comment that there appear to be more mobs.  I will omit it.

The reason being that I did not mention that our group has only cleared the areas of Stratholme before the DEAD section and before the LIVE section.  In other words, Hearthsinger, Unforgiven, the post boxes, quests, etc.  We don't have experience in the areas covered by this map yet, since we are still 56, and learning the dungeon.

**Comment by Tobschinski** [comment]
About the Gargoyles - there are 7 patrolling routes, each of them will be used by a Gargoyle or a Screecher, at equal chance. Additionally, one can also be used by Stonespine, the rare one. 

The re-spawn time for these is 30 minutes (not for Stonespine though).

Do they really re-spawn too fast? 

EDIT: Yes, they do.

**Comment by kamicolo** [comment]
this needs to be investigated don't just close reports

**Comment by Bilbo79** [comment]
Hello.  

This message is to let you know that I personally closed this report. 

The purpose for closing this report, was to break out each individual issue (listed above), and write it up as a stand alone issue bug report.

This has been done.

Please investigate the individual instance issues instead.  Thank you.

I am closing this.
