### ISSUE TITLE
KoS Issues

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#34]
Reported by Awardis:

"Name: Awardis
Area: Various, Shadowglen
How to replicate the bug: walk near mob
What happens: nothing
What should happen: Grell and Grellkin in Shadowglen should be KoS. I suspect other mobs in the other starter areas should be KoS as well as they were dumbed down sometime after classic to be non-KoS."

**Comment by kamicolo** [comment]
all starting area's are as they suppose to be.
