### ISSUE TITLE
Instance - Zul'Farrak (need testing)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#340]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Zul'Farrak (any part of instance)
How to replicate the bug:  Do a normal ZF run, and you will see some.  After about 15-20 minutes, ride back through cleared parts to see the other behaviors mentioned.
What happens:

a)  Re-spawn timer on all patrols is too quick.  Patrols will re-spawn in only 15-20 minutes later.  This could be upwards of 30 minutes too soon.  

b)  Patrols move at 200% (twice) normal speed.  This is common in other World areas as well as other instances.

c)  Patrols (warrior, shadow caster even) "can" have a long range charge ability, which can range to about 100 yards or more.  You will be walking through a cleared zone, and see a Patrol off in the distance standing still.  Suddenly, they move at a "blink" rate of speed, and appear right on top of your character and get an attack off.  I've only seen this about 20% of the time though.

What should happen:

a)  Re-spawn should be 45 minutes or so, and only on some patrols (moving mobs)
b)  They should move at normal speed
c)  They should always walk, and never blink long distances

Located on WoWHead Map (if applicable):   Inside entire ZF zone.  They all do it.
Source (proof, if applicable):  experience only

Extra Information:

**Comment by kamicolo** [comment]
Respawnrate patrols can be looked into. Regarding the patrol speed this is a core issue regarding view / data load radius. While the patrol starts when your near enough data requiers sync server vs client result could lead to "fast running" NPC's as server sided the patrol might be further then the client had got informed.

**Comment by Bilbo79** [comment]
Hello.  

This message is to let you know that I personally closed this report. 

The purpose for closing this report, was to break out each individual issue (listed above), and write it up as a stand alone issue bug report.

This has been done.

Please investigate the individual instance issues instead.  Thank you.

I am closing this.
