### ISSUE TITLE
Misc. mobs don't flee

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#35]
Reported by aesther:

"Name:Misc mobs
Area:Anywhere
How to replicate the bug:Nearly killing the mob they run away
What happens:They dont run away but you see the text when they are running. eg "Aiieee me run"
What should happen:They should flee

Extra Information:"

orfeas noted:

"This happens with any npc that flees...so i guess we talk for mostof the humanoids except nagas and such vile creatures who dont flee..."

**Comment by scotty0100** [comment]
I'm guessing this is only Kobold Miners in Echo Ridge.

Here is a YouTube video https://www.youtube.com/watch?v=faN11hsdWjE#t=154 of killing miners on Retail (all be it WoTLK), we can see the kobolds saying this on aggro on retail and not fleeing.

So this is 'Blizzlike' - just not logical ;)
