### ISSUE TITLE
Instance - Maraudon - Stealthed demons (Purple side)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#355]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Maraudon, Purple side, on the whole path to Lord Vyletongue
How to replicate the bug:  Progress through the purple side as you normally would
What happens:

a)  Stealthed rogue demons (singles). There are none. I am pretty sure that there should be some stealthed demons (3-4 in total, maybe more) which do slowly patrol along different portions of the purple side. They can ruin your day if you are not prepared for them too. But we did not see any on roughly 10 times through.

What should happen:

a)  They should be there, and pathing.  They can run in to the group at odd times, being invisible.

Located on WoWHead Map (if applicable):   In Mara, on entire length of Purple side
Source (proof, if applicable):  personal experience

Extra Information:

**Comment by Tobschinski** [comment]
They have always been around but not moving. That was fixed.
