### ISSUE TITLE
Dodge & Crit. rates are too low at low level

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#36]
Reported by Composter:

"Account name: Almanekra
Name: Dodge & Crit rates
Problem: Crit & dodge rates are way too low.

Example: rogue starts at like 2% dodge rate, should start at like 25%

Other: The rates will normalize eventually as you gain levels, so it's no biggie"

**Comment by kamicolo** [comment]
Rejecting: http://vanilla-wow.wikia.com/wiki/Rogue pointed stats for class / race did not involve low level bonus or any other adjustments.
