### ISSUE TITLE
Blackrock Depths - Secret Safe

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#362]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Blackrock Depths, in the dark coffer room
How to replicate the bug:  Kill the dark coffer key carrier, or Watchman Doomgrip
What happens:

a)  Secret Safe , can never be opened. Since the Watchman Doomgrip (who is summoned after you open the 12 coffers) does not drop the key. That means no loot (good loot too) for opening 12 coffers, and killing 4 [Elemental Elites]. This is bad.

Note:  This leads to several other issues, which I will document in other bug requests.  Such as not being able to complete quests.

What should happen:

a)  The Watchman is supposed to drop the key.  The Dark Coffer guy should (another bug write up)

Located on WoWHead Map (if applicable):   In BRD, in dark coffer room
Source (proof, if applicable):

Extra Information:

**Comment by Skylark14** [comment]
Reported: https://github.com/scotty0100/wowascension-issues/issues/161
