### ISSUE TITLE
Blackrock Depths - Heart of the Mountain quest

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#363]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Blackrock Depths, in the dark coffer room
How to replicate the bug:  Just try to open the Secret Safe any way possible
What happens:

a)  Dark Coffer - Quest - Heart of the Mountain. Cannot be completed. Since the Key holder never drops the key, this secret area can never be opened. The quest item cannot be obtained.

What should happen:

a)  The object should be located within the Secret Safe, which should be able to be opened using some means or another (Killing Watchman Doomgrip, Killing the dark coffer key holder)

Located on WoWHead Map (if applicable):   In BRD, in dark coffer room
Source (proof, if applicable):  Personal experience

Extra Information:

**Comment by Skylark14** [comment]
Reported: https://github.com/scotty0100/wowascension-issues/issues/161
