### ISSUE TITLE
Blackrock Depths - Grim Guzzler door

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#365]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Blackrock Depths, at the back of the Grim Guzzler
How to replicate the bug:  Open the door using the quest method, where the keg from across the room, blows open the door.  Fail the Doom'Rel (7 dwarves) fight.  Then come back to it.
What happens:

a) Grim Guzzler door - The door works fine, and can be blown open using the ale mug quest, which we did. The problem is that if you FAIL the Chest of Seven event, then this door closes and locks behind you. You are forced to hearth (or jump down and fight a bunch of other meaningless mobs to get out). It is somehow linked to the event. I think this, because yesterday we only killed Ambassador Flamelash, and a few golem pulls in the room behind him. But today, we cleared that room, and attempted "The Seven" event a couple of times. We didn't succeed. And on the way back out, this door is locked, preventing re-entry to Grim Guzzler. If you succeed at the event, the door is open. I've checked.

Note: Confirmed. This is linked to the Chest of Seven event. It is reproducible 100% of the time.

What should happen:

a)  The door should stay open

Located on WoWHead Map (if applicable):   In BRD, within Grim Guzzler bar
Source (proof, if applicable):  Personal Experience

Extra Information:

**Comment by Skylark14** [comment]
Reported on Github https://github.com/scotty0100/wowascension-issues/issues/76

**Comment by Bilbo79** [comment]
Leaving this open.  Not only is this bug documented stand alone (not lumped in with other bugs), it is also more clear in my opinion.  Glad that I am not the only one who noted this.
