### ISSUE TITLE
Blackrock Depths - Dark Coffer portrait / keeper

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#368]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Blackrock Depths, just outside the dark coffer room
How to replicate the bug:  Activate the portrait on the wall, and see what happens
What happens:

a)  The Dark Keeper portrait does not work. It shows the same guy every time. And I cannot find him (the Keeper) in the instance any any of his 6 possible spawn spots.  Two of which are really close by. Where is he? Or this is broken. There is supposed to be 6 random guys, and tells you name and where he is.  We have tried this about a dozen times.

What should happen:

a)  The dark coffer key holder is supposed to spawn in the instance.  Often accompanied by personal guards.

Located on WoWHead Map (if applicable):   In BRD, just outside dark coffer room
Source (proof, if applicable):  Personal Experience

Extra Information:

**Comment by Skylark14** [comment]
Reported on Github https://github.com/scotty0100/wowascension-issues/issues/161
