### ISSUE TITLE
Instance - Blackrock Depths - Hall of Crafting pathing

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#369]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Blackrock Depths, in the Hall of Crafting area
How to replicate the bug:  Just go into this area by any means
What happens:

a)  Some pathing (with the exception of 1 golem mob) is broken. So groups are in big clumps.  Grouping is odd also, with golems standing close to the dwarf miners.

b)  Fineous Darkvire does not path. 

What should happen:

a)  Rock golems should path more.  2-3 of them in total I think.

b)  He should be pathing.  

Located on WoWHead Map (if applicable):   In BRD, inside the Hall of Crafting area
Source (proof, if applicable):  Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
Fineous will move around now. The amount of golems pathing however was  correct.
