### ISSUE TITLE
Instance - Blackrock Depths - Fireguard Destroyers

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#372]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Blackrock Depths, in several locations (between Golum Manufactory & Grim Guzzler, for example) or anywhere else
How to replicate the bug:  Engage one of them for fight
What happens:

a)  Fireguard Destroyers (elemental) - are supposed to have an AOE instant fireblast ability which hits all members of the party within like 20-25 yards (I forget the range exactly, but ranged dps and healers can stand outside this at 30 yards if they are aware of this). They don't use it.

What should happen:

a)  They should have this explosive attack.  It is their signature ability.

Located on WoWHead Map (if applicable):   In BRD, in all areas of dungeon where this mob type can be found
Source (proof, if applicable):  Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
Oh, this got fixed a long time ago. They will use Thrash and a Firebolt Volley.
