### ISSUE TITLE
Blackrock Depths - Ribbly Screwspigot

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#374]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Blackrock Depths, inside the Grim Guzzler
How to replicate the bug:  Try to engage Ribbly any way possible
What happens:

a)  Ribbly Screwspigot - Is friendly. Cannot be engaged. The "insult" dialog is available but does not do anything. He could drop a very nice BS pattern, or a 16 slot bag. Too bad.

b)  There is a quest to kill him also.  It is not possible to complete this quest.  We all did the breadcrumbs to get to him. But you still can't engage him, even with the quest. So the quest cannot be completed either.

What should happen:

a)  You should be able to fight him

b)  You should be able to aggro him and kill him to complete the quest.

Located on WoWHead Map (if applicable):   In BRD, inside the Grim Guzzler
Source (proof, if applicable):  Personal Experience

Extra Information:

**Comment by Skylark14** [comment]
Reported on github https://github.com/scotty0100/wowascension-issues/issues/2

**Comment by scotty0100** [comment]
Closing as duplicate
