### ISSUE TITLE
Blackrock Depths - Hurley Blackbreath

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#375]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Blackrock Depths, within the Grim Guzzler bar
How to replicate the bug:  Try to fight Hurley
What happens:

a)  Hurley Blackbreath - is not in the Grim Guzzler. He should be. 

b)  When you break the 3 kegs in the back room, he is supposed to turn hostile, and run over to the area where you broke the kegs (room) for combat. He also would have some nice drops.

What should happen:

a)  He should exist, and can be summoned properly

b)  He should drop nice loot

Located on WoWHead Map (if applicable):  In BRD, within the Grim Guzzler
Source (proof, if applicable):  Personal Experience

Extra Information:

**Comment by Skylark14** [comment]
Reported on Github https://github.com/scotty0100/wowascension-issues/issues/160
