### ISSUE TITLE
Blackrock Depths - Core Fragment (for quest)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#378]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Blackrock Depths, at the entrance to the Molten Core
How to replicate the bug:  Have more than 1 member of the group, needing a core fragment
What happens:

a)  Core Fragment - Quest to get access to Molten Core. The re-spawn on this item apparently either does not happen at all, or exceeds 5 minutes (about as long as we could stand to wait around for). I could swear the in vanilla there were 5 of these on the wall, one for each party member. That would be nice if you could put that in. It doesn't seem right that one party member should get the fragment, and the other 4 should have to do another full BRD run to get a shot at theirs.

Note:  More than one of us needed it on the next run through, so we waited it out. The timer is actually 10+ minutes. This is moved up to Major bugs now. 40 minutes is too long for a new party of 5 to wait for everyone to get one. We actually waited 30 minutes for 3 other people to get theirs. It was timed. We used a USA clock, but last time I checked, it worked the same as a UK clock. :p

What should happen:

a)  Core Fragment should re-spawn instantly.  

Located on WoWHead Map (if applicable):  In BRD, close to the dark forge
Source (proof, if applicable):  Personal Experience

Extra Information:

**Comment by Skylark14** [comment]
Reported on github: https://github.com/scotty0100/wowascension-issues/issues/76

**Comment by Skylark14** [comment]
There was only ever one core fragment but it was an almost instant respawn on retail. Currently its set at +5mins which is too long.

**Comment by scotty0100** [comment]
Was fixed a month or two ago. Closing.
