### ISSUE TITLE
Stratholme - The Unforgiven

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#381]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Stratholme, in the area between Market Row and Festival lane
How to replicate the bug:  Have you or someone in your group walk into this area
What happens:

a)  The Unforgiven - Does not exist. He, and 4 of his undead (non-elite) spectres should spawn in the area between Market Row, and Festival lane. It is triggered when you walk through the small tunnel between the two areas. He doesn't. This is too bad.

What should happen:

a)  He should spawn with his 4 pals.  It is surprising if you are not prepared for it.  

Located on WoWHead Map (if applicable):  In Stratholme, between Market Row and Festival Lane
Source (proof, if applicable):  Personal Experience

Extra Information:

**Comment by Skylark14** [comment]
alrezady reported on github: https://github.com/scotty0100/wowascension-issues/issues/248

**Comment by Bilbo79** [comment]
Closing this issue then.  Appologize for making a dup.
