### ISSUE TITLE
Stratholme - Rat Traps (gates that close)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#383]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Stratholme, underneath the gates sections found in 2-3 places within instance
How to replicate the bug:  Walk under the gated section
What happens:

a)  The party can walk though them any time they want. The cages (gates) do not drop, and the rats to not come out to attack the party.

What should happen:

a)  The gates should drop, and the rates should come out in waves (3 I think) of 5-6 to attack the group.  It is a trap.

Located on WoWHead Map (if applicable):   Stratholme, in two places in entry section, and one place on the DEAD side.
Source (proof, if applicable):  Personal Experience

Extra Information:

**Comment by Skylark14** [comment]
reported on github https://github.com/scotty0100/wowascension-issues/issues/117

please note: it isn't always rats, as can be cockroaches the trap triggers.

**Comment by Bilbo79** [comment]
That would be cool too!  Thanks for noting this.
