### ISSUE TITLE
Stratholme - Eye of Naxx

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#387]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Stratholme, in all areas that are not the LIVE side
How to replicate the bug: Clear content as you normally would
What happens:

a)  The Eye of Naxx does not appear.  We waited a half dozen or more times to write this to be sure, but after spending a dozen hours on various parts of the instance where the Eye has a chance to spawn, we can confidently say that it does not.  We will remove this if we ever see it.

What should happen:

a)  It should show up, and if not killed fast, should bring Gargoyle elites into the instance (summon).

Located on WoWHead Map (if applicable):   In Stratholme, in all areas of the instance, which are not the LIVE side.
Source (proof, if applicable):  Personal Experience

Extra Information:

**Comment by Skylark14** [comment]
Reported https://github.com/scotty0100/wowascension-issues/issues/117

We have actually seen the Eye of Naxx during runs and killed it and the gargoyles so it is there, just not sure how accurate it is if you say its not appeared during your runs.

**Comment by Bilbo79** [comment]
Perhaps it was a previous patch release?  And perhaps it just got overwritten?  We did 5 runs on Sunday, and didn't see it then either.  Maybe, like "Winter's Chill", it was something that once worked, but got overwritten some how and reverted back by a more recent change patch?  I am just guessing here.

**Comment by Bilbo79** [comment]
OK, ammending this.  The eye is up.  But, it does not appear to be visible.  Then 1 spectre is summoned.  The spectre starts moving in one direction for about 20 - 30 feet, then disappears.  This is the behaviour that we saw twice today.  If you are not paying careful attention, you miss it all together, which seems to be what has happened to us during out previous 15 visits.
