### ISSUE TITLE
Stratholme - Skul (Rare)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#391]
Name: Ocholoco
Account Name: Bilbo79
Map & Area: Stratholme, just on the other side of Kings Square gate (locked), or in the fountain square just next to Fras Siabi and Stratholme Courier location.
How to replicate the bug: Go to either location and look for Skul
What happens:

a) It appears that Skul (Rare) mob found, which has a chance to be found within 1 of 2 possible locations (see above), is does not exist in Stratholme currently.  We have cleared all mobs from Main Entrance to both locations on 5 occasions, and been through these sections on 11 additional occasions, keeping an eye out for this rare.  

Note:  While 16 is not a high sample set, it should be often enough to spawn the rare.  I will update this count as we progress through the instance.  I will also remove this request if we see Skul even one time.

[EDIT]  Skul is spelled with only one "L", and not two as the subject (above) states.

What should happen:

a) Skul should have a chance to be in Stratholme.

Located on WoWHead Map (if applicable): In Stratholme, just on the other side of Kings Square gate (locked), or in the fountain square just next to Fras Siabi and Stratholme Courier location.
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
He exists, added him a few weeks ago.

**Comment by Bilbo79** [comment]
Yep, he can make an appearance.  Closed.
