### ISSUE TITLE
NPC - Duke Hydraxis

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#392]
Name: Skylark
Account Name (for vote points rewards): Skylark19
Map & Area: Azhara
How to replicate the bug: Once completing http://db.wowascension.com/?quest=6824 Speak to the Duke
What happens: nothing
What should happen: at Revered rep he should have the option to give you the Eternal Quintessence, at Honored rep Aqual Quintessance
Located on WoWHead Map (if applicable):
Source (proof, if applicable): http://www.wowhead.com/item=22754/eternal-quintessence#comments

Extra Information: Without this we cannot test further into MC. We currently have 7-8 people at either revered or honored.  Tobinshski was present and said that some script was missing to enable this.

**Comment by Tobschinski** [comment]
I cannot add the gossip option, simply, because I don't know the text that should be displayed. If anyone would be so nice, please let me know.

**Comment by Skylark14** [comment]
Couldn't find the gossip but did find another github post about it: https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/1969

**Comment by Deviastarix** [comment]
This is was fixed a while back, and Eternal Quintessence can be obtained from Duke Hydraxis.
