### ISSUE TITLE
Hunter Pet Training level requirement

### ISSUE THREAD

**Issue by Sylxeria** [scotty0100/wowascension-issues#393]
Name: Sylxeria

Account Name (for vote points rewards):  Akaikosh

Map & Area:  Not applicable

How to replicate the bug: Tame a pet, then try to use Beast Training

What happens:  Growl I learns just fine after a bit of combat. Great Stamina and Natural Resistance both claim the pet is too low of a level, despite both stating that the required level is Lv1. The former requires Five Training Points, and I have eight. The pet I'm trying to train is Lv9.
Both skills show as 'able to be learned' while Growl II is still marked as unable (As it requires level 10, while my crocolisk is level 9) but neither can be learned

What should happen:  If you have enough Training Points to 'purchase' the skill, it should learn automatically. 

Source (proof, if applicable): 

![wowscrnshot_082014_203549](https://cloud.githubusercontent.com/assets/8509454/3991557/ecb06172-28e4-11e4-9892-ef01e867c9b7.jpg)

A screenshot I took of the screen and the skill failing/refusing to be learned.

Extra Information:  As far as I know this hasn't been reported yet (I did a quick search for 'Hunter' and nothing came up pertaining to this specific problem), and I've been in combat with my pet for a while now, and have fed it often... Growl I learned just fine - the other skills, which should be allowed by now, won't learn.

**Comment by Sylxeria** [comment]
Unable to edit the actual issue, but the skills mentioned above can be learned just fine after the pet levels up naturally. I can't remember if it's always been like this or not, but if it has then this "issue" can be closed without any problem (Although it would mean tamed lvl60 pets would be difficult to work with, since they can't level up any more and thus wouldn't be able to learn many skills)

**Comment by kamicolo** [comment]
closing: https://github.com/scotty0100/wowascension-issues/issues/232
