### ISSUE TITLE
Instance - Lower Blackrock Spire - Scarshield Infiltrator / Vaelan

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#399]
Name:  Ocholoco
Account Name:  Bilbo79
Map & Area:  Lower Blackrock Spire, hidden on a ledge, up near the beginning of the instance.
How to replicate the bug:  Approach the Scarshield Infiltrator, while holding the Unadorned Seal of Ascension
What happens:  

a)  The Scarshield Infiltrator is found in the proper place on the map.  But when you, and / or, other party members approach, while carrying the Unadorned Seal of Ascension, he does not turn into Vaelan.

b)  The Quest "Seal of Ascension" can never be started or completed.  UBRS can never be entered.

What should happen:  

a)  He should turn into Vaelan.  

b)  He should give you a quest.  And be avaialble to complete the quest.

Located on WoWHead Map (if applicable):  In LBRS, in this spot.
Source (proof, if applicable):  Personal Experience

Extra Information:  This could be a tricky one to fix permanently.

**Comment by scotty0100** [comment]
Should be fixed as of today, let me know.

**Comment by Bilbo79** [comment]
Note:  As of Nov, 2014 this has been fixed, and Vaelan is working correctly.

Closing this.

**Comment by Bilbo79** [comment]
Note:  As of Dec 24th, 2014 this NPC is broken again.  The scarshield infiltrator no longer turns into Vaelan.

Anyone that is looking to pick up Seal of Ascension, or anyone like me that has the gems to complete the quest now and is looking to get their UBRS key, it will not be possible.

Please put this back on the priority list.  Thank you.

Attached SS:

http://i167.photobucket.com/albums/u132/Bilbo79/Vaelan_broken_zps6dfb0682.jpg

**Comment by Bilbo79** [comment]
Bump.  I am totally in shock that this did not get addressed in the Jan 15, 2014 patch.

Nobody has the key.  

2 players (that are still active) have the gemstones.  But no one can get into UBRS.

**Comment by Bilbo79** [comment]
Update.  In a forum post, Devia states that Quietly was given access to Vaelan somehow, and was able to continue on the quest line.

Is it possible the igrampsl can get the same service?

I know for a fact that only last week Quietly was missing the stone from Voone.  This Github request and my forum post both predate that by almost a month.

Help.

**Comment by scotty0100** [comment]
This should now be fixed in today's patch.
