### ISSUE TITLE
Raewhen's Quest Bugs

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#4]
"Area: Darkshore- Blackwood Den
How to replicate: Chose the quest option to Fight your way out.
What happens: The guy you are escorting teleports forward about ten feet and then appears to walk back towards the cave, repeating the process except each time he teleports farther away.
Also the quest is broken, even if you figure it out and manage to get him all the way safely, he gives the emote that he is safe and you should go claim your reward, the quest is marked as failed."

**Comment by scotty0100** [comment]
Confirmed still bugged.

**Comment by scotty0100** [comment]
This is fixed now.
