### ISSUE TITLE
Invisible / Glitched Mobs

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#40]
Reported by Dots:

"Name: Dots
Account Name (for vote point rewards): joefz2
Map & Area: 1K Needles, Splinthoof Crag and Splinthoof Hold
How to replicate the bug: Go to Splinthoof Hold
What happens: 2 or 3 mobs from the rocks will appear out of nowhere and wreck your face up
What should happen: Mobs to be visible
Located on WoWHead Map (if applicable): http://www.wowhead.com/maps
Source (proof, if applicable):"

**Comment by scotty0100** [comment]
Closing and merging into -> https://github.com/scotty0100/wowascension-issues/issues/423
