### ISSUE TITLE
Dwarf racial Stoneform

### ISSUE THREAD

**Issue by Weeablade** [scotty0100/wowascension-issues#409]
Name: Toecrusher
Account Name (for vote points rewards): Vandalsavant
How to replicate the bug:
Get a disease on a dwarf character, and use Stoneform.

What happens:
When using Stoneform with the intent on purging disease debuffs, it does not.

What should happen:
Using it when debuffed by any disease should remove it.

Source (proof, if applicable):
The racial's tooltip says "While active, grants immunity to Bleed, Poison, and Disease effects. In addition, Armor increased by 10%. Lasts 8 sec." 

Extra Information:
I've only been able to test this with Volatile Infection from Old Murk-Eye, and Spirit Decay from Riverpaw gnolls, but I suspect it doesn't purge any diseases at all. I know it purges poisons fine, but I haven't tested any Bleed effects, and recommend they be subjected to likewise scrutiny as Diseases.

**Comment by Skylark14** [comment]
Reported on Github: https://github.com/scotty0100/wowascension-issues/issues/227

**Comment by scotty0100** [comment]
Duplicate Closing.
