### ISSUE TITLE
Writhing Highborne

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#410]
Name: Tootsie
Account Name (for vote points rewards): Skylark
Map & Area: Ameth'Aran - Darkshore
How to replicate the bug: Engage a Writhing Highborne
What happens: Look at the highborne, they are holding a dagger
What should happen: They should not have a dagger
Located on WoWHead Map (if applicable):
Source (proof, if applicable):http://www.wowhead.com/npc=2177#comments

Extra Information:

**Comment by scotty0100** [comment]
Fixed
