### ISSUE TITLE
Hezrul Bloodmark

### ISSUE THREAD

**Issue by Weeablade** [scotty0100/wowascension-issues#411]
Name: Mojohobo
Account Name: Vandalsavant
Map & Area: Barrens, Lushwater Oasis
How to replicate the bug:
Observe Hezrul Bloodmark.

What happens:
Hezrul and his two linked mobs (Kolkar Bloodchargers) stand still where they spawn.

What should happen:
Hezrul and his two linked mobs (Kolkar Bloodchargers) patrol clockwise around the Lushwater Oasis.

Located on WoWHead Map (if applicable):

Source (proof, if applicable):
http://www.wowhead.com/quest=852#comments:id=1986

**Comment by scotty0100** [comment]
They now patrol the oasis. Thank you
