### ISSUE TITLE
Cenarion Aid

### ISSUE THREAD

**Issue by Kihessa** [scotty0100/wowascension-issues#412]
Cenarion Aid--Priest class quest for ST/horde side for Blessed Prayed Beads,
    Team,
           Is Cenarion Aid working on horde side?  Ur'kyo in Org isn't offering the quest to a 52 level priest with Cenarion Aid being the quest chain start.

**Comment by Skylark14** [comment]
I believe X'yera the Priest Trainer in Valley of the Spirits should offer this quest

**Comment by Kihessa** [comment]
Thanks!  You're correct.

Date: Sat, 30 Aug 2014 16:31:38 -0700
