### ISSUE TITLE
Class - Druid - Spell: Shapeshift

### ISSUE THREAD

**Issue by partheniou** [scotty0100/wowascension-issues#413]
Name: selat
Account Name (for vote points rewards): partheniou
Map & Area: everywhere
How to replicate the bug: while you are in human form just shapeshift to another form and then back to human
What happens: mana pool is dramatically reduced after shifting to human
What should happen: mana pool should stay the same and also the mana you had before
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: When you shapeshift back to human form as I mentioned before your mana pool is reduced. If you apply mark of the wild then the pool comes back but not the actual mana, so you have to regen to full

Thanks

**Comment by abbab** [comment]
Reported on the Ascension site on 06 Aug.  Renders the class essentially unplayable, as you can't eat/use bandages/whatever while shapechanged, and shapeshifting takes so much mana you can't apply much in the way of heals during combat.  My druid hasn't left Darnassus since this began.

**Comment by scotty0100** [comment]
This is now fully fixed as of today's patch - with no delay also.

**Comment by abbab** [comment]
?Thank you, sir!  It does warm the heart to know that thee's actually a team working on this stuff, unlike some other private servers.  I do sometimes complain in an all-too-strident voice, but I do appreciate the work.

Because I love your server!
