### ISSUE TITLE
NPC - Kashoch the Reaver

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#414]
Name: Moh
Account Name (for vote points rewards): Moh
Map & Area: Frostwhisper Gorge - Winterspring
How to replicate the bug: See if he is up
What happens: he is classified as a level 61 elite with health of 19504 and has no rare tag.  
What should happen: According to wowhead he should be classified as level 55 non elite with health of 7842
What happens: nothing
What should happen: the npc
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:
Source (proof, if applicable): 

http://www.wowhead.com/npc=10198/kashoch-the-reaver#drops
http://www.wowdb.com/npcs/10198-kashoch-the-reaver
Extra Information:

**Comment by Tobschinski** [comment]
wowhead is up to date - I think he should be level 60 rare-elite with 9156 HP

**Comment by Skylark14** [comment]
source link says otherwise, checked wowhead and wowdb, both say 55 rare whereas wowhead is the only one that states his health to be 7842.

**Comment by Tobschinski** [comment]
Next batch of DB-updates!
