### ISSUE TITLE
Felwood flowers

### ISSUE THREAD

**Issue by Matten123** [scotty0100/wowascension-issues#418]
Hi,

I tried to farm Whipper Root Tubers for the BS book enchant and they are bugged. You can do the quest to cleanse them.

1) if you do this the flower that should be cleansed isnt disappearing. It can be cleansed again if u have the mats.

2) theres a cleansed flower appearing but if you try to loot it, its written you are doing something else and it disappears.

This has to be fixed or we can never do this book enchants.

Greetings Leonie

**Comment by Skylark14** [comment]
Already reported: https://github.com/scotty0100/wowascension-issues/issues/245

**Comment by scotty0100** [comment]
Closing as duplicate
