### ISSUE TITLE
Gnarled Thistleshrub

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#42]
Reported by Composter:

"Name: Gnarled Thistleshrub armor bug
Account Name: Almanekra
Map & Area: Thistleshrub Valley @ Tanaris
Problem: These certain mobs have too high armor, causing melee characters having problems killing them.

Example: My warrior auto-hits these mobs for 100 damage, normally for 250 damage."

**Comment by scotty0100** [comment]
After talking it over with mangos core developers, we have concluded that it's not a bug. These treants are known to have high armor.
