### ISSUE TITLE
Loot

### ISSUE THREAD

**Issue by Zundrak** [scotty0100/wowascension-issues#421]
Hi 
I have noticed that group loot looks like its on round robin but it actually acts as free for all.
its a real pain when healing and/or ranged dps because you are always the last to loot and everything gets taken.
Changing loot types does nothing.
The coin gets split accordingly though.

Cheers

**Comment by Skylark14** [comment]
reported previously on: https://github.com/scotty0100/wowascension-issues/issues/74

**Comment by scotty0100** [comment]
Closing as duplicate
