### ISSUE TITLE
Goblin Engineering requirement-less

### ISSUE THREAD

**Issue by Sylxeria** [scotty0100/wowascension-issues#424]
Name: Sylxeria

Account Name (for vote points rewards): Akaikosh

Map & Area: Not applicable

How to replicate the bug: Go to Gadgetzan and speak with Nixx Sprocketspring with an Engineering skill of 205+ and _without_ Goblin Engineering skill. The Goblin plans will be available to buy and learn without first becoming a Goblin Engineer.

What should happen: None of these should be available to you until not only level 47 (When you can start the quest to become a Goblin specialist) but until you actually become a Goblin Engineer specialist.

Source (proof, if applicable): 
http://www.wowhead.com/item=10577  (Requires: Goblin Engineer 205+ )

(Additionally, there's something strange going on with the icons. Possibly from the above issue?)
![wowscrnshot_100814_102856](https://cloud.githubusercontent.com/assets/8509454/4563847/9c6e57ce-4f12-11e4-98e3-5812e784b1d9.jpg)

**Comment by kamicolo** [comment]
CLOSING: https://github.com/scotty0100/wowascension-issues/issues/216
