### ISSUE TITLE
Improved Blessing of Might

### ISSUE THREAD

**Issue by Sylxeria** [scotty0100/wowascension-issues#425]
Name: Sylxeria

Account Name (for vote points rewards): Akaikosh

Map & Area: Not applicable

How to replicate the bug: Place at least one point in the Paladin's 'Retribution' tree in the Improved Blessing of Might talent. Cast BoM on yourself or any friendly target.

What should happen: Blessing of Might at Rank 1 provides +20 Melee Attack Power.  With Improved Blessing of Might it should provide +4% more, but it doesn't. I was questing with a paladin friend and I had his character (Only level 9) cast his on me when I dispelled mine, and both of ours - mine with the Improved BoM and his standard -  only provided the same +20 attack power.

Source (proof, if applicable):

**Comment by Skylark14** [comment]
4% of BOM AP rank 1 = 0.8 numbers will not be rounded up instead it's increment based meaning 1 talent point 4% provides 0 AP on rank 1 BOM
