### ISSUE TITLE
Quest: Stranglethorn Feaver 

### ISSUE THREAD

**Issue by Ryzael** [scotty0100/wowascension-issues#431]
Name: Rhayden (Ryzael)
Account Name (for vote points rewards): Hellghost
Map & Area: Stranglethorn Vale
How to replicate the bug: Talk with Witch Doctor Unbagwa with 10 gorilla fangs and complete the quest while already having the quest Stranglethorn Feaver.
What happens: You are able to to complete this quest as many times as you wish to summon the gorillas and each time you do you receive 5,850 exp. 
What should happen: Should only be able to get the experience once, for the first time completing( i have no proof of this but i know many repeatable quests like this usually only reward experience the first time you do the turn in and some times they dont give any experience.) also 5,850 exp seems rather high for this level as well.
Located on WoWHead Map (if applicable): http://db.wowascension.com/?quest=349 (using our data base because the WoWHead map uses the new Stranglethorn Vale map which has different coordinates.) 
Source (proof, if applicable): http://imgur.com/a/gDQr5 

Extra Information: As you seen in the first screen shot i already have Heart of Mokk which is the final gorilla from this part of the quest meaning i already completed the quest beforehand and the second screen shot is me receiving the experience again.

**Comment by Tobschinski** [comment]
Indeed, quest http://www.wowhead.com/quest=349 should not grant any experience at all. I'll correct this. The reward for quest http://www.wowhead.com/quest=348 is correct though.

Thank you for pointing!

**Comment by scotty0100** [comment]
Fixed and will be patched in on Starix tonight.
