### ISSUE TITLE
NPC: Lady Moongazer

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#432]
Account Name: Gwerf
Map & Area: Ameth'Aran, Darkshore (coords: ~43, 61)
NPC info: Lady Moongazer (level 17 rare spawn)
What happens: She hits for about ~150 melee but if you are not in melee range all she does it use her bow, hitting for ~20

Extra information: as it is I was able to autoshot her to death as a level 13 hunter.

**Comment by Skylark14** [comment]
According to Ascension Database: http://db.wowascension.com/?npc=2184 she should hit for 97-124. This is, I assume, whether in melee range or not. Whereas her melee range is actually over what she should hit, it would appear that her ranged is lower.

**Comment by kamicolo** [comment]
Quick Facts
Level: 17
Class: 
React: A H
Faction: Monster
Health: 386
Wealth: 0.0031
Damage: 97 - 124
Armor: 748
- Damage = Melee damage done versus same level

http://db.wowascension.com/?spell=6660
Value: 38 Not mitigated.

Melee seems fine.

Ranged however is very questionable. Currently there is a bug with shoot this might be related not adding in the link untill that one is more investigated.

**Comment by Tobschinski** [comment]
Since she isn't elite, her melee damage was off. She should and will hit for 25-33 anytime soon™.
