### ISSUE TITLE
NPC: Innkeeper Kimlya

### ISSUE THREAD

**Issue by Gwerf** [scotty0100/wowascension-issues#436]
Account Name: Gwerf
Map & Area: Astranaar, Ashenvale (coords 37, 49)
What happens: Innkeeper Kimlya does not give you the option to make Astranaar your home - the vendor tab opens instead.

**Comment by kamicolo** [comment]
Status: Closing issue:

Clear WTF and WDB folder.
On a additional note: Old addons are conflicting with some NPC's Advice to disable addon causing this issue.
