### ISSUE TITLE
[NPC/Escort] Corporal Keeshan

### ISSUE THREAD

**Issue by Gwerf** [scotty0100/wowascension-issues#438]
Name: Volpip
Account Name: Gwerf
Map & Area: Redridge Mountains
What happens: Corporal Keeshan does not get attacked by any hostile mobs on the way from Render's Rock to Lakeshire.
What should happen: Corporal Keeshan should be attacked by any hostile mobs he passes.

![image](https://cloud.githubusercontent.com/assets/9502239/5003324/d3fbe774-69c0-11e4-9987-34c7b6f5066c.png)

![image](https://cloud.githubusercontent.com/assets/9502239/5003328/dd080ac8-69c0-11e4-8026-f4c8a3792094.png)

Additional info: He does, however, attack the mobs if the player initiates combat. The quest name is "Missing in Action".

**Comment by scotty0100** [comment]
Fixed as of today's patch.
