### ISSUE TITLE
Druid run speed bug

### ISSUE THREAD

**Issue by Deviastarix** [scotty0100/wowascension-issues#441]
Name: Devia

What happens:  While in Night Elf form, and outdoors, it appears that the Feline Swiftness talent is active and a run speed increase is applied. It was hard to tell if it was linked to Travel Form (+40% speed), but I checked with another druid who doesn't have the Feline Swiftness talent, and gets no speed increase in Night Elf form. It only happens outdoors (as per the FS +30% speed in Cat Form talent). Another druid queried his run speed in World chat, and also has Feline Swiftness talent, so it's likely that that's where it's coming from.

What should happen: No speed increase should be applied in Night Elf form.

**Comment by kamicolo** [comment]
Rejected: https://github.com/scotty0100/wowascension-issues/issues/338
