### ISSUE TITLE
Idk what just happend

### ISSUE THREAD

**Issue by Somthinghappend** [scotty0100/wowascension-issues#444]
name:deeanddee
area: Hillsbrad Foothills "Durnholde keep"
what happend: I was fighting one of the jailors and a syndicate shadowpriest up the mountain, the shadow priest was able to mind control me for the first time and threw me out of combat, then i decided to go back try to kill them both again. This time i got mind controld, then I TRY to use will of the forsaken " then something weird happend with my addons and then i was freed while the mind controll debuff was on me then i look at chat and their was orange text saying the following.

Error occured while running hooks for: EnhTooltip.AddTooltip
Interface\AddOns\Auctioneer\AucUtil.lua:167: attempt to concatenate local 'factionGroup' (a nil value)
Call Chain:
 (tail call):?
Interface\AddOns\EnhTooltip.Lua:860: in function <Interface\AddOns\EnhTooltip\Tooltip:lua:814>
Interface\AddOns\EnhTooltip.Lua:1058: in function <Interface\AddOns\EnhTooltip\Tooltip:lua1040>
[C]:in function 'pcall'
Interface\AddOns\Stubby\Stubby.lua:271: in function <Interface\AddOns\Stubby\Stubby.lua:242>
(tail call):?
Interface\AddOns\CT_BagMod\CT_BagMod.lua:191:in function 'CT_CCButton_OnEnter'
[String "CT_CCB4Button:OnEnter"]:2: in main chunk

^-----This is what Im having trouble with I have no Idea what I did but it had something to do with addons and probably with my free of movement.

Additional Info
My addons at the occurance of the time
     Active addons
          Atlas Joana's Guide Suite [1.5]
          AtlasLoot [PRE-TBC Edition]
          Auctioneer
          Bag Status Meters
          CT_Allbags
          CT_BagMod
          CT_BarMod
          CT_BottomBar
          CT_Buffmod
          CT_ExpenseHistory
          CT_Hailmod
          CT_ItemBuffs
          CT_Mailmod
          CT_Mapmod
          CT_MasterMod
          CT_MovableParty
          CT_PartyBuffs
          CT_PlayerNotes
          CT_QuestLevels
          CT_RABossMods
          CT_RaidAssist
          CT_ShieldMod
          CT_Tickmod
          CT_Timer
          CT_UnitFrams
          CT_Viewport
          EnhTooltip
          Extended QuestLog 3.6.1
          FilterFix
          Gatherer
          GroupCalendar
          LootTracker
          MEtamap
          MetaMapBKP
          MetamapBLT
          MetamapBWP
          MetamapCVT
          MetamapEXP
          MetamapFWM
          MetamapHLP
         MetamapQST
          MetamapWKB
          MetamapZSM
          OneBag -Ace2-
          Peggle "the game i wished that woked"
          Stubby
          Telo's LootLink - Enchanced
          X-Perl Options
          X-Perl Party Frame
          X-Perl Party Pet Frame
          X-Perl Player Frame
          X-Perl Player pet Frame
          X-Perl Raid Admin
          X-Perl Raid Helper
          X-Perl Target Frame
          X-Perl Target's Target Frame
          X-Perl TeamSpeak Monitor
          X-Perl UnitFrames Core
          XLoot -Ace2-
          FastQuest 2.11
     Disabled addons
          AuctionFilterPlus
          [BSK] WowHead DB
          Optional - LootLink Database Adder
          GMH (GameMaster's Helper) V1.1.0

 I got all these addons in one zip package and forgot where I forgot them, For now Im disabling all addons because I don't know if its effecting the server.

What do I need to do as far as this^?

My regards D&D

**Comment by Somthinghappend** [comment]
UPDATE: it was Jailor Eston and Syndicate Shadow Mage

**Comment by Somthinghappend** [comment]
UPDATE: And it was a charmed spell Not Mind control

**Comment by Bilbo79** [comment]
Note:  I am not a dev @ascension.

But I run a lot of the mods you currently list, successfully.  My advice would be:

a)  Disable / Delete Auctioneer addon.  Reason, is because there is no auction house economy right now, since the player base is too small.  You can re-activate it in the future.

b)  Disable / Delete Stubby addon (support for Auctioneer).  Reason, same.

c)  Disable / Delete CT_BagMod addon.  Reason, you absolutely do not need CTRA to manage your bags for you.  There are a dozen better ones, none of which I can think of off the top of my head.

Do no delete the whole CTRA package.  Just that one portion of it.

Should be good to go.

**Comment by kamicolo** [comment]
Addon malfunction reports do not belong on github.

Greetings,

Kamicolo
