### ISSUE TITLE
Feared monster incorrectly shows its position

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#45]
Reported by Scarlet:

"Name: Scarlet
Map & Area: Any
How to replicate the bug: Cast any fear effect (i.e. Warlock's Fear) on any monster
What happens: Monster flees to the direction behind you. When you turn to face the monster and cast a spell, it fails and says that you are not facing the monster when visually you are. So monster actually flees in the opposite direction than the one the player sees. Also sometimes feared monster relocates to another place (which happens to be the real place where monster should be fleeing to) by quickly running to it (a small quirk).
What should happen: Player should see to where exactly the monster flees."

**Comment by kamicolo** [comment]
closing: https://github.com/scotty0100/wowascension-issues/issues/73
