### ISSUE TITLE
Instance - Dire Maul - East - Alzzin the Wildshaper

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#456]
Name: Ocholoco
Account Name: Bilbo79
Map & Area:  Dire Maul East - Final boss
How to replicate the bug:  Kill Alzzin and see what you can loot
What happens:

a)  Alzzin does not have the 'Whipvine Cord' in his loot table.  Check it out please.

We have killed Alzzin 16 times now.  There is a 10% chance for Whipvine Cord to drop.  That is 32 possible rolls on the 10% chance, since he guarantees two (2) pieces of loot.

There is only a 3.4% chance of not getting this drop.  We have had a 96.6% chance of this dropping.  It is not in his loot table.

I am going to update this with more kills, as time goes on.  But honestly, how long can I continue farming for something that is simply not there.

What should happen:

Whipvine Cord should be in his loot table.

Located on WoWHead Map (if applicable):  DM:E Final boss
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
I am sorry, you were just out of luck here. It drops! (3rd attempt)

![whip](https://cloud.githubusercontent.com/assets/4753528/5513455/5555ddf0-87f5-11e4-9b86-941e00e515b6.png)

**Comment by Bilbo79** [comment]
Hacks!  Oh well.  Good to know it exists.  Thank you for testing.  Closing this.

**Comment by Bilbo79** [comment]
17 kills and counting ...

**Comment by Bilbo79** [comment]
18 kills and counting ....

it is worth noting that the last 4 kills, the same piece of loot was duplicated x2

**Comment by Bilbo79** [comment]
and 19 kills and no drop.

Re-opening.  I question the SS now.

**Comment by Bilbo79** [comment]
I have a screen shot too.

It is of the actual piece of paper that I have been keeping track of Alzzin kills with:

[edit] removed URL link.

**Comment by Bilbo79** [comment]
According to statistics and probability there is a 98.5% chance of it having dropped with 39 independent rolls.

Please check the seed mechanism that sets loot when dungeons are entered.

Please check that this is not set at 1%, instead of 10%, and that your loot was simply luck.

There is only a 0.016423203268260658146231467800709255289% chance of this happening.

**Comment by Bilbo79** [comment]
20 times, was not a charm.  That is a fair sample.  We are done.

Please fix this broken mob for others, who are as hopeful as we were on our first attempt 2 months ago.

Merry Christmas, bye the way.

**Comment by Tobschinski** [comment]
I really don't know what to do here, I went there again and got it on my first attempt. (even 3 times out of 5)

I've checked people's inventories and some were able to obtain the belt.

Here is the reference that is called twice. There is no condition for the Whipvine Cord to not drop for you other than bad luck.

![untitled](https://cloud.githubusercontent.com/assets/4753528/5555184/f757f8fa-8c9f-11e4-9055-1ba9c997f1fa.png)

**Comment by Bilbo79** [comment]
Thank you for testing this.  But I believe that the test conditions (whether it be server, drop rate, instance seed, etc) is not matching the conditions of real game play.

1 drop out of 3,  or
3 drop out of 5,  is so far from

0 drop out of 20,  that

as a statistic that they are not even comparable.  There has to be a difference in the testing conditions in my experience with math.  

20 is a solid sample set.  If you are able to reproduce this 100 times quickly, on starix, then that would be an interesting sample to compare the 20 to.

Thank you again for your help.

**Comment by Bilbo79** [comment]
OK ... it is done.

on attempt #22, we got the belt to drop.  

we had too much to drink tonight, so we thought .. 'hick .. wat tah heck .. hick .. teh belt .. hick'

i don't know if you read old, closed, Github posts, but if you do, then you were right.  it was in his loot table.

But know that we have taken this past 99%.

You might want to check to make sure that this is not a 1% drop, rather than a 10% drop.  That is all.

Thank you for hanging in there with us.

**Comment by Tobschinski** [comment]
Oh I do - I'm glad this was sorted out.
