### ISSUE TITLE
Fear rarely breaks from damage

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#46]
Reported by Scarlet:

"Name: Scarlet
Map & Area: Any
How to replicate the bug: Cast any fear effect (i.e. Warlock's Fear) on any monster, and then attack it with spells
What happens: Fear very often doesn't break from damage caused to feared monster. Breaking only happens around 1 out of 10 times.
What should happen: Fear should break from damage much more easily."

**Comment by kamicolo** [comment]
closing: https://github.com/scotty0100/wowascension-issues/issues/73
