### ISSUE TITLE
Instance - Dire Maul - North - Guard Fengus

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#470]
Name: Ocholoco
Account Name: Bilbo79
Map & Area:   Dire Maul North, Fengus courtyard
How to replicate the bug:   Go there and look for Fengus
What happens:

a)  Guard Fengus is just standing there, not patrolling.  And he is standing right on top of the box that holds the courtyard door key.  

This means you have to get creative about how you are going to get the key (assuming you are doing a tribute run)

What should happen:

a)  Guard Fengus needs to patrol his normal route.  It at least makes it more interesting, and authentic.

Located on WoWHead Map (if applicable):   DM:N, in the Fengus courtyard.
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
About to be pushed ...

**Comment by Bilbo79** [comment]
Note:  The Guard Fengus is now patrolling just fine.  There is a small issue where he can move at warp speed if he is far from you, and you come into his radius (100 yards or so).  But is nothing.  Closing this.
