### ISSUE TITLE
Instance - Dire Maul - North - Eye of Kilrogg

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#472]
Name: Ocholoco
Account Name: Bilbo79
Map & Area:  Dire Maul North, Inside the Courtyard door, and inside the building
How to replicate the bug:  Go through the door and look for Eye of Kilroggs
What happens:

a)  There are 2 Eye of Kilrogg, and neither one patrols.  

What should happen:

a)  They should patrol on routes.  Not stand there.  It makes it harder if they move around.

Located on WoWHead Map (if applicable):   DM:N, just past the Courtyard door.
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
Got this working.
(There were even 4 static spawns, I don't know if this was correct. There won't be more than 2 up now.

**Comment by Bilbo79** [comment]
Awesome.  Will test when patch goes live.

**Comment by Bilbo79** [comment]
Note:  Both of the eyes are working.  They spawn VW's with 9k HP, and they hit at 740 dps, which is way overpowered.  But at least they are pathing now.  Closing this.
