### ISSUE TITLE
Instance - Dire Maul - North - Guard Slip'kick pathing

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#473]
Name: Ocholoco
Account Name: Bilbo79
Map & Area:  Dire Maul North, past the Courtyard door, where Guard Slip'kik is supposed to be
How to replicate the bug:  Go through the door and look for Slip'Kik
What happens:

a)  Guard Slip'Kick is just standing there, chilling with the other ogres, and not pathing like he is supposed to.

This totally eliminates the need to use an ice trap on him.  He is a non factor, unless you are trying to kill him.

If you are trying to kill him then you are in trouble, because he is in proximity aggro to 4 other mobs, that will also pull with him.  Good luck with that one.

What should happen:

a)  Guard Slip'kick should patrol on his normal route.

Located on WoWHead Map (if applicable):   DM:N, in the Slip'Kick area.
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
This was fixed and should go live soon.

**Comment by Bilbo79** [comment]
Note:  Slip'kick is pathing now.  Just at Warp-7 speed.  Closing this, and opening another one.
