### ISSUE TITLE
Instance - Dire Maul - North - Inner Door issues

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#474]
Name: Ocholoco
Account Name: Bilbo79
Map & Area:  Dire Maul North, at the Inner Door
How to replicate the bug:  Open the Inner Door using a key (or not)
What happens:

a)  The Inner Door aparently does not require a key.

b)  The inner Door does not use up your key if you already have one (you get to keep it forever).  This makes things exponentially easier doing a tribute run, since you don't have to kill Mol'Dar over and over hoping for the Inner Door key, and reset.

c)  There should be mobs outside the door, and inside the door.  But there are none and none.  This is like a cake walk.

What should happen:

a)  You should need a key.

b)  You should have your key used up (removed from your keyring) if you open the door.

c)  There should be mobs around this door making it harder.

Located on WoWHead Map (if applicable):  DM:N, at the Inner Door location.
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
I've locked the door and bound the key to the zone.
Nearby NPC are still missing though.

**Comment by Tobschinski** [comment]
Uhm, do you know if the Gordok Shakle Key should be removed as well?

**Comment by Bilbo79** [comment]
Thanks, will test on live, I guess after next patch goes live?

As far as the Shackle key goes, yes, it is a one time use object.  The drop rate is high enough though, to pretty much ensure that this is not a problem.

**Comment by Tobschinski** [comment]
No, I meant something different.

The XYZ Gordok Door Keys are bound to the dungeon. Once you leave the dungeon, they will be removed from your key ring. You cannot zone out with these and have to obtain them during your run which means you cannot save them for your next one.

But I don't know if similar mechanics were present for the Shackle Key.

**Comment by Bilbo79** [comment]
Having the xyz doorkeys bound to the instance is a good idea in principal, but in execution, it is not.  And here is why.

If the "X" key represents the Inner Door key, then it would be impossible to do a perfect Tribute run.

Guard Mol'dar holds the Inner Door key.  You have to kill him to get it.  If you kill Mol'dar, you cannot do a perfect Tribute.  And if the key is bound to the dungeon, as soon as you leave and reset, it will no longer be in your inventory when you come back to start your perfect Tribute run (leaving Mol'dar alive).

[edit]  You could pick-pocket Mol'dar and get it (rogue), or blast the Inner Door open (Engineer), or perhaps pick the lock (rogue, Blacksmith), but honestly, that is not how it is done.  You shouldn't have to need this kind of special player to get a regular old tribute run done.  It is bad enough that you have to make an ice trap, and an ogre suite to properly do the run.

Alternative is to do something non-blizzlike, and have the Inner Door key drop off regular ogres too.

The Shackle key can be bound to the instance if you want.  It drops at a low rate from regular mobs, but usually people farm the guards for it.  And then come back.  I don't think it is blizzlike to bind the Shackle key to the instance.  But it is still a good idea on how to fix the inner door issue.

**Comment by Tobschinski** [comment]
> You could pick-pocket Mol'dar and get it (rogue), or blast the Inner Door open (Engineer), or perhaps pick the lock (rogue, Blacksmith), but honestly, that is not how it is done. 

Actually, it was done like that. This is not my idea, this is Blizzard's.

> Patch 1.5 - The Gordok Courtyard Key and the Gordok Inner Door Key are now zone bound items. These items only exist within the Dire Maul zone instance, and players will lose these keys from their inventory if they leave the zone.

**Comment by Bilbo79** [comment]
Well, if you have the 1.12.1 revision reference manual on this, then you should implement it this way.

I just can't remember back that far honest.

But I do believe that your "fix" for the Inner Door will create more of a problem than it solves right now.

**Comment by Bilbo79** [comment]
Note:  The Inner Door key fixes that have gone into place are working well now.  Closing this.
