### ISSUE TITLE
Hunter Pet Taming

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#48]
Reported by RageCage:

"Name: Vulmenji
Account Name (for vote point rewards): Ragecage
Map & Area: Durotar (Not limited to this zone.)
How to replicate the bug: Start taming a pet, then finish the cast.
What happens: The beast sometimes doesn't get tamed, and will continue attacking you.
What should happen: If you have aggro of the beast you're taming throughout the whole cast, the pet should always be tamed.

Source (proof, if applicable): This happened when I tried taming my first pet."

**Comment by kamicolo** [comment]
tame beast requiers lvl if the beast is at your same level failure could occur if the beast is 1 level below you you will always tame him.
