### ISSUE TITLE
Instance - LBRS - Dragonkin in the house

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#486]
Name: Ocholoco
Account Name: Bilbo79
Map & Area:  LBRS, found in areas before Overlord Wyrmthlak
How to replicate the bug:  Go into this area of the dungeon
What happens:

a)  There are 3 mob types that are not supposed to be in this area.  They are Chromatic Dragonspawn dragonkin, Chromatic Whelps, and Rage Talon Flamescale dragonkin.  These mobs are part of the Warchief Rend Blackhand hall event that takes place in UBRS.  They are not supposed to be in LBRS.  

What should happen:

b)  There should be some orcs up here that have a chance to punt you off the side of the stone bridge.  There should be ogres up here.  There should be some of those big mutant troll looking things up here (kind of like what Wyrmthlak summons at 50%.  There might be more.  I simply don't remember or have a reference exactly.  

Located on WoWHead Map (if applicable):  in LBRS in sections before Wyrmthlak
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
The area was overhauled..
