### ISSUE TITLE
Instance - Dire Maul - LIbrary - Prince chest

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#488]
Name: Ocholoco
Account Name: Bilbo79
Map & Area:   Dire Maul North - Library (under stairs)
How to replicate the bug:   Finish the NELF quest to kill Immol'thar and Prince
What happens:

a) The chest the quest spawns which is under the stairs in DM Library, is still there, after you have chosen to take out your quest item, and finish the quest.

This not a big deal at all, since the chest contains nothing. 

What should happen:

a) Despawn after choosing quest reward.

Located on WoWHead Map (if applicable): DM:N in library
Source (proof, if applicable): Personal Experience

Extra Information:

Here is the SS:

http://i167.photobucket.com/albums/u132/Bilbo79/Prince_Treasure_Forever_zpscddb76f7.jpg

**Comment by Tobschinski** [comment]
I need more input here. 
Why should the chest despawn, it's there to hand in quests and not to take any loot from (if I recall correctly)

**Comment by Bilbo79** [comment]
OK, I have updated the bug report to read properly.  Sorry about the confusion.

You know what.  You are right.  It is the quest chest.  For the NELF on the 2nd floor of DM:W.  It has nothing to do with Prince.

Hmm.

Well, shouldn't the chest go away after you take your reward?  For you personally?  Again, this is no big deal at all.  It can go in the trash can if you want.  I just don't think I have ever seen it sitting there ever again after finishing the quest on another realm.

**Comment by Tobschinski** [comment]
Well you should not be able to interact with this chest at all if you're not on certain quests.

You probably never noticed it because its position is a little bit off, it should be under the stairs, not next to it.

I've checked the chest on the retail servers and it is up forever, without killing anyone, without being on any quests. So I'd assume it has always been like that.

**Comment by Bilbo79** [comment]
OK.  Thanks for checking.  Closing this.
