### ISSUE TITLE
Instance - Dire Maul - North - Library door

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#492]
Jan 5, 2015 report:  It appears that some of the patch went live today on Starix.  Many things are changed in Dire Maul.  I do not see the Changelog post on Forums though.

Name: Ocholoco
Account Name: Bilbo79
Map & Area: Dire Maul North - Mol'dar courtyard
How to replicate the bug:  Try to open the Library door
What happens:

a)  There is no way to open the LIbrary door.  It does not have the 'gear'.  If you are a Crescent key holder or not, it appears the same.

What should happen:

a)  Key should open the door.

Located on WoWHead Map (if applicable): DM:N Mol'dar courtyard
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
You cannot target it, right? That's my mistake, applied a bad  faction.

**Comment by Bilbo79** [comment]
Note:  As of Jan 17, 2014 this door is fixed.  Closing this.
