### ISSUE TITLE
Instance - Dire Maul - North - Guards Mol'dar & Slip'kick DPS

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#493]
Jan 5, 2015 report:  It appears that some of the patch went live today on Starix.  Many things are changed in Dire Maul.  I do not see the Changelog post on Forums though.

Name: Ocholoco
Account Name: Bilbo79
Map & Area: Dire Maul North - Mol'dar courtyard
How to replicate the bug:  Fight Mol'dar
What happens:

a)  He does 70 dps.  See other related bug.  

b)  His call for help now works by they way.  This is not bug, but rather a fix.  He can now call dogs over from a FAR greater distance (50 yards or so).  This might be OK, even though it seems far.

What should happen:

a)  His dps should be WAY higher than this, even though I have no recorded SS of what it used to be.

b)  I like that he can call dogs now.  So this is not a bug.

Located on WoWHead Map (if applicable): DM:N Mol'dar courtyard
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Bilbo79** [comment]
Note:  OK, we tested this on Slip'kick, and he also does 70 dps.

**Comment by Tobschinski** [comment]
i didn't touch the damage yet, I just updated most mobs' ridiculously fast attacking-speed.

**Comment by Bilbo79** [comment]
Note:  Updated, he does the knock back.  Just not often.  This is fine.

But it should be noted that he only did 1 knockback in 6 fights.  That is less than 20% the frequency that he used to do it.  Since I probably have a sample of over 200 fights versus Mol'dar on this server I have a pretty good idea how he works. 

If he does not do much knockback in the next 20 fights, I will put this back on the list.

This problem could be due to the same issue that prevents Kromkrush from using his Fear ability now.  Some timer or latency has been introduced into their special attacks, and they just don't use them much any longer.

**Comment by Tobschinski** [comment]
I've buffed their melee damage, they will hit for 713 - 945 when the next batch of server updates went live.
