### ISSUE TITLE
Instance - Dire Maul - North - Slip'kick patrol speed

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#495]
Jan 5, 2015 report:  It appears that some of the patch went live today on Starix.  Many things are changed in Dire Maul.  I do not see the Changelog post on Forums though.

Name: Ocholoco
Account Name: Bilbo79
Map & Area: Dire Maul North - Slip'Kick patrol route
How to replicate the bug:  Go into this area and watch Slip'kick
What happens:

a)  He is patrolling at about 20 mph currently.  While this is not an issue if you have the ice trap, he WILL come around much faster than expected if you are clearing those mobs by the trap.  This will be interesting, since they are casters, and do not pull properly.

What should happen:

a)  Slip'kick should go slower.

Located on WoWHead Map (if applicable): DM:N Slip'kick patrol route
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Deviastarix** [comment]
Name: Devia

Slip'kik still patrols too fast, and he does not get caught in the trap when it is fixed. Tested on 16/5/15.

**Comment by Tobschinski** [comment]
Will no longer chase Usain Bolt.
