### ISSUE TITLE
Instance - Dire Maul - North - Wandering Eye of Kilrogg  (Respwn)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#496]
Jan 5, 2015 report:  It appears that some of the patch went live today on Starix.  Many things are changed in Dire Maul.  I do not see the Changelog post on Forums though.

Name: Ocholoco
Account Name: Bilbo79
Map & Area: Dire Maul North - Gordok king castle
How to replicate the bug:  Kill an Wandering Eye of Kilrogg, and wait
What happens:

a)  The respwn rate of this mob is currently exactly 10 minutes.  This is way too fast.  It guarantees that if you lose a healer within the next 10 minutes of the run, that he will not make it back alive.  The Eye summons within 5 seconds of combat, and no single player can kill the 3 VW's that come out with 9k HP a piece.

What should happen:

a)  Respwn slower than this

Located on WoWHead Map (if applicable): DM:N King castle part.
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Tobschinski** [comment]
It's actually 900 seconds, it should been something between 900 and 1800 seconds. But that's not possible at the moment.

**Comment by Bilbo79** [comment]
I timed it at 10 minutes on the nose.  600 seconds on my American clock.  

Now, it it were about 2400 seconds, that would be fair.

**Comment by Tobschinski** [comment]
Wandering Eye of Kilrogg's health was significantly lowered, even solo healers should be able to deal with them quickly.
