### ISSUE TITLE
Instance - Dire Maul - North - Tribute Chest issue

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#499]
Jan 5, 2015 report:  It appears that some of the patch went live today on Starix.  Many things are changed in Dire Maul.  I do not see the Changelog post on Forums though.

Note:  I am writing this up in a new bug report, since MANY of the actual Tribute chest bugs were fixed, and it appears that I might close that one(s).

Name: Ocholoco
Account Name: Bilbo79
Map & Area: Dire Maul North - Tribute Chest
How to replicate the bug:   Talk to Mizzle, spawn a chest, fight the King, loot the chest, talk to Mizzle, spawn a chest, loot the chest, rinse, repeat....
What happens:

a)  Unlimited chests.  That is how many you can get if you do the above.  Not sure about normal kill though, because we did this instead.  It can be abused.

SS:  http://i167.photobucket.com/albums/u132/Bilbo79/Tribute_2_Chests_zps0be83003.jpg

OK, we talked to Mizzle, and he spawned a chest before the fight, in the middle of the King area.  This is a big improvement.   Rogue might be able to get to it though.  

We kill the king, leaving Cho'Rush alive, and the fight ends exactly the way it should.  Everyone is happy.

We loot the chest, and get our crappy loot.  It is highlighted.  Is is only a green because we are testing and killed everything except Fengus.

We talk to Mizzle again, and he spawns a new chest for us.  Still crappy loot, but it would be good loot if we did a perfect run.  And basically that is the SS.  We did it a 3rd time to see if it was 'all you can eat Tribute chests', and it was.

What should happen:

a)  One King.  One Chest.

Located on WoWHead Map (if applicable): DM:N  King, Tribute chest
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Deviastarix** [comment]
Name: Devia

No longer an issue. Chest spawns only once. Confirmed 16/5/15

**Comment by scotty0100** [comment]
Thanks for the information - will close the issue.
