### ISSUE TITLE
Instance - LBRS - Highlord Omokk (loot table)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#502]
Name: Ocholoco
Account Name: Bilbo79
Map & Area: LBRS, Highlord Omokk
How to replicate the bug:  Kill Omokk a bunch
What happens:

a) The Skyshroud Leggings do not have the correct drop rate.

This is much like Allzin the Wildshaper in DM:E, who currently has a 1% drop rate on the belt.

Omokk has been killed more than 15 times (I just know by my own notes on other Omokk issues), and we have not seen the legs once.  We have seen the Shaman chest 6 times at least.  

Please confirm that these still drop.  And more importantly, with the correct drop rate.

We would like to know that it is not 1%, like Alzzin's belt.

What should happen:

a) He should have dropped the legs 2-3 times by now.

Located on WoWHead Map (if applicable): LBRS, in Highlord Omokk room
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by Bilbo79** [comment]
0 for 15, and 0 for 16.

Please fix this.

I have a recommendation.  Swap the actual item in Omokks loot table with the 'Plate of the Shaman King" item.  That will drop the plate into oblivion, and make the Skyshroud Leggings available.  After all, we have seen that item 7 times now.

Thank you!

**Comment by Tobschinski** [comment]
Both items have equal chances. I was able to get the item you wanted from Omokk. 
Again, I do not see any issues at all.

**Comment by Tobschinski** [comment]
Pretty sure you will get your item soon, it drops.
