### ISSUE TITLE
Opposite Faction - Follow (ability)

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#504]
Name: Ocholoco
Account Name: Bilbo79
Map & Area:   Anywhere
How to replicate the bug:   Try to "Follow" a member of the opposite faction
What happens:

a)  It does not work.

Please note that is is not really a bug, but rather a request for a feature to be implemented.  

It would be really cool if the opposite faction could follow.  Whether in a group or not.  But ideally both.  If in a group, then great too.

What should happen:

a)  Probably what is happening now.  But it would be nice if follow was possible.

Located on WoWHead Map (if applicable):  Anywhere
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by kamicolo** [comment]
This belongs on the ascension forum as it's an idea and not a bug report.
