### ISSUE TITLE
Ban'ethil Barrow Den

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#51]
Reported by Skylark:

"Name: Skylark
Area: Teldrassil- Ban'ethil Barrow Den

This area's mobs aggro/respawn rate is way off.  You enter and kill the fist couple, have respawn behind you and mobs aggro through walls from somewhere. Fight your way to the first two bridges to get quest items.  By the time you've killed two mobs on the first bridge theres others respawn behind you.  Shamans charge sometimes - this shouldn't happen and they try to get behind you - again this shouldn't happen.  In the end you get so many mobs/respawns its impossible to carry on as you have no mana as a caster and respawn rate makes it impossible to drink/regain mana. Could not even get past the first level after managing to get the first two quest items for the Relics due to the amount of mobs you get on you.  On the first level by the two bridges a gnarlpine defender just appeared instanly beside me while fighting 2 shamans then an Augar appeared, seemingly from below the first level. This was done at level 15 - mobs are 8-9. I would say without a fix this quests here would be impossible at the right level (9).  The quest that sends you there isn't marked as a group quest and not even sure how a group would fare given the respawn/aggro rate atm.   This problem will impact four quests, the initial one that sends you there - The Relics of Wakening, one you get inside which has two parts plus the follow up to the Relics one. 

Will test it again once the fix has been done as atm after several attempts, its not worth trying as it is now."

**Comment by kamicolo** [comment]
closing: https://github.com/scotty0100/wowascension-issues/issues/30
