### ISSUE TITLE
Arathi Basin token hand in

### ISSUE THREAD

**Issue by armyofone** [scotty0100/wowascension-issues#519]
Account name: ash
Area: Orgrimmar/Undercity - Horde Warbringer npc

After the first turn in of Arathi Basin tokens using the quest Conquering Arathi Basin, the quest disappears and cannot be repeated. AB token can only handed in one time.

First handed in in Orgrimmar, but I also checked in Undercity (where I never turned in any tokens) adn the quest also missing there at Horde Warbringer npc. Didnt checked but I assume, its missing in Thunder Bluff too.

It seems the npc itself got this problem. On alliance side, there is no problem with any token turn in quests, they work just fine.

Harley

**Comment by scotty0100** [comment]
This is now fixed. Thank you.
