### ISSUE TITLE
Blackmoss the Fetid

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#52]
Reported by Skylark:

"Name: Skylark
Area: Teldrassil - Wellspring Lake

Level 13, is not marked as elite but hits like one.  Don't remember this as being normal for him once he was made nonelite before 1.12 "

**Comment by scotty0100** [comment]
Blackmoss is now marked as an elite and I have looked through patch notes to see if there was any mention of him not being elite to no luck. Found two YouTube videos of him being an elite dated past 1.12.1 so I imagine he was always an elite. Although he was reduced from level 13 to level 8 later on.
