### ISSUE TITLE
Quest Mail Reward Bug

### ISSUE THREAD

**Issue by unsquishable** [scotty0100/wowascension-issues#522]
Name: Unsquishable
After completing the last quest, A Terrible Purpose (part of The Twilight Mystery chain), Commander Mar'alith is supposed to mail you a reward. I have waited 2 days without a letter from my love.

**Comment by Tobschinski** [comment]
This should happen from now on.

In your case: Please submit a ticket in-game to claim your reward.

**Comment by Roarek** [comment]
Aidspenguin, a guildie of mine, completed the quest since then and has not received a letter over the course of a whole day, the letter is meant to be sent within hours of completing the quest.

**Comment by scotty0100** [comment]
Should be working for you now @Roarek after today's patch.
