### ISSUE TITLE
NPC - Malyfous Darkhammer

### ISSUE THREAD

**Issue by Deviastarix** [scotty0100/wowascension-issues#526]
Name: Devia
Map & Area: Everlook

The NPC Malyfous Darkhammer should give a choice of follow up quests after turning in the quest 'Finkle Einhorn, At Your Service!'

I should be able to choose the quest 'Breastplate Of Bloodthirst' from him, but he gives no quest options.

My rep with Thorium Brotherhood is Friendly, but I think he should give the quests whatever your rep is, even Neutral.

**Comment by Tobschinski** [comment]
There's a [tome](http://www.wowhead.com/object=175927/malyfouss-catalogue) next to him.

**Comment by Deviastarix** [comment]
Thanks Tobs. My bad. Thought he was supposed to offer it rather than an offchance that people click a tome that, if they're as blind as I obviously am, they don't notice.

Got the quest now.
