### ISSUE TITLE
Lake Al'Ameth

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#53]
Reported by Skylark:

"Came across some bugs just outside Oakenscowl's cave.  While clearing the Timberlings outside, a spider (Webwood Venomfang) aggro'ed from the level above the cave on the upper hill.  A Gnarlpine Defender then came out of the cave and proceeded to levitate along the hill then up. Another spider then appeared.  There are also 2 Strigid Owl's flying inside the cave that appear then disappear and a Deer.  This part of the area should only have Timberlings.  When you pull Oakenscowl, the Gnarlpine then reappears and mobs you along with Oakenscowl and another Timberling."

**Comment by scotty0100** [comment]
Closing and merging into -> https://github.com/scotty0100/wowascension-issues/issues/423
