### ISSUE TITLE
Class - Warrior - Spell: Shieldblock (inline - Talent: Improved Shield Block)

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#56]
Reported by Scarlet:

"Warrior's talent "Improved Shield Block" (http://db.valkyrie-wow.com/?spell=12945) doesn't work.
It says that "Shield Block" (http://db.valkyrie-wow.com/?spell=2565) will block 2 attacks instead of 1. This doesn't work - even with talent, Shield Block blocks only 1 attack.
Tested with 3/3 Improved Shield Block.
EDIT: apparently talent works correctly against some low lvl mobs, but I tested with Searing Ghoul (http://db.valkyrie-wow.com/?npc=1795), and my blocks aren't full (blocks only a part of full hit damage)."

**Comment by tardmonkey** [comment]
Up!

This talent still doesn't work and it's quite a shame in Raids :(

**Comment by scotty0100** [comment]
Fixed and will be patched in shortly.

**Comment by scotty0100** [comment]
Closed as fixed.
