### ISSUE TITLE
Wendigo & Frostmane Headhunter

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#58]
Reported by Hundano:

"Wendigos being necrophiliacs... 

Name: Falcerodin
Area: Dun Morogh, The Grizzled Den
How to replicate the bug: get killed by wendigo's during a disconnect/game crash.
What happens: You die, the wendigos corpse-gank you. 
What should happen: You die, the wendigos go back to their usual roaming area.

Extra Information: It happened to me during a client crash(didn't read the error message, so dunno what caused it)"

Frostmane Headhunter missing projectile model. 

Name: Falcerodin
Area: Dun Morogh, Frostmane Hold
How to replicate the bug: Get attacked by a Frostmane headhunter, and look closely on what he throws. 
What happens: The Frostmane Headhunter throws a blue and white box.
What should happen: The Frostmane Headhunter throws a spear."

**Comment by scotty0100** [comment]
First one would be very hard to replicate. Second one has been fixed for a while now.
