### ISSUE TITLE
Fel Rock & other caves/barrows

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#59]
Reported by Skylark:

"Name:
Account Name: Skylark
Map & Area: Teldrassil - Fel Rock
How to replicate the bug: Just enter Fel Rock
What happens: The first sprite reacts normally however on entering the cave the first time, as you move into the cave you then get several sprite aggro at once thus making it impossible to enter the cave.  I tried this a second time, it appeared to react normally then all of a sudden I had several sprites respawn behind me.  However, some of these are ones you encounter further in the cave so shouldnt have been there. You need to do the quest Twisted Hatred in the centre of this cave but the correct level player would find this impossible.
What should happen: The sprites should be spread normally and singularly, respawn timer should be greatly increased.
Located on WoWHead Map (if applicable): http://www.wowhead.com/maps
Source (proof, if applicable):

Also found a similar problem in Ben'ethil Barrow: Shaman charged (they shouldnt do that) also kept trying to go behind me when I was not in aggro range, respawn very quick on some mobs to the point you get overwhelmed."

**Comment by Skylark14** [comment]
Same problem in the Hives in Silithus and Tanaris.  Silithus in particular is extremely bad as they're elites, to the point of where you cannot go in there even with a group.

**Comment by kamicolo** [comment]
CLOSING: https://github.com/scotty0100/wowascension-issues/issues/423
