### ISSUE TITLE
Hypercapacitor Gizmo

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#6]
Reported by Shadow:

"Name: Shadow
Account Name : vivaro
Map & Area: Thousand Needles @ Whitereach Post
NPC quest giver : http://www.aowow.org/?npc=10941
Quest  : http://www.aowow.org/?quest=5151
What happens: Panther is bugged, doesn't attack and it can't be attacked.
What should happen: The panther should attack you / be able to be attacked."

**Comment by scotty0100** [comment]
This has been fixed & VP were added
