### ISSUE TITLE
Innkeepers

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#60]
Reported by yours truly, me:

"A player's hearthstone is a pretty good tool to not walk all the way back to a certain place.
I'm not sure if other people experienced this bug as well, but as far as Dun Morogh innkeepers go, they refuse to give you a home.
Dwarves..

Map & Area: Dun Morogh, possibly everywhere
How to replicate the bug: Talk to an innkeeper.
What happens: Opens the shop.
What should happen: Shows an option screen with clickable options 'Make this inn your home.' and 'I want to browse your goods.'. If applicable, quests are listed as an option too."

**Comment by scotty0100** [comment]
Innkeeper Belm in Dun Morogh offers up the 'Make this inn your home' option now.
