### ISSUE TITLE
Pet Trainer Gossip Menu

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#62]
Reported by Bruescrues:

"Name: Brues
Account Name: Bruescrues
Area: Where Pet Trainers are located
How to replicate the bug: Talk to a Pet Trainer as a hunter
What happens: http://i.imgur.com/Y65P2Mp.png
What should happen: http://i.imgur.com/GstgiX0.png

Extra Information: You can still train pet spells, but you have to click right in the highlighted part."

**Comment by scotty0100** [comment]
Fixed
