### ISSUE TITLE
Hunter Pet Bugs

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#64]
Reported by Holmski:

"There are a couple of bugs I've noticed with my pet:

Name: Holmski
Account Name (for vote point rewards): Holmie
Map & Area: Kinda everywhere
How to replicate the bug: Pet not getting on boat and similar.
What happens: When you get on a boat my pet stays on the dock and when the boat leaves it tries to follow but fall into the water. Also it sometimes doesn't come with you when you HS.
What should happen: Pet should come along on the boat

Name: Holmski
Account Name (for vote point rewards): Holmie
Map & Area: World
How to replicate the bug: Pathfinding bugs for pet
What happens: Sometimes when you send your pet to attack something at a place where it seems to be just to run straight ahead it decides to take a detour and often pull alot of other mobs.
What should happen: Pet should go straight for the target when there is nothing in the way.

Name: Holmski
Account Name (for vote point rewards): Holmie
Map & Area: World
How to replicate the bug: "stay"-commando bugged
What happens: When I tell my pet to stay on a specific location it runs away in full speed in a random direction, and when putting follow again it comes back in super-speed.
What should happen: Pet should just stand still where I put him"

**Comment by kamicolo** [comment]
closing: https://github.com/scotty0100/wowascension-issues/issues/49
https://github.com/scotty0100/wowascension-issues/issues/232
