### ISSUE TITLE
Feral Faerie Fire vanished

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#65]
Reported by Despise:

"Having a weird bug with my talent that disappeared on me! In the Photos you can see how there is a missing point from Feral Faerie Fire, but I have placed one in it 3 lvls earlier. It is still on my bars and usable.

(couldn't upload my pictures as the files are too large)"

Thread: http://wowascension.com/forum/index.php?topic=209.0

**Comment by Skylark14** [comment]
Reported previously https://github.com/scotty0100/wowascension-issues/issues/54

**Comment by kamicolo** [comment]
https://github.com/scotty0100/wowascension-issues/issues/54
