### ISSUE TITLE
Wind Stones

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#66]
Reported by barrotes:

"the lesser windstones in silithus do not work to summon the elementals this bug prevents us from farming green gear to start dungeons i had all the 3 parts of the set and i went talk to the stone nothing no lightning to the head no speech nothing plz fix this fast ty"

**Comment by brues-code** [comment]
Fix is in the core, but the scripts for the Stones weren't put in. Will be fixed asap

**Comment by scotty0100** [comment]
Has been fixed for a while. Closing.
