### ISSUE TITLE
Battlemaster Gossip Menu

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#67]
Reported by Bruescrues:

"Name: Brues
Account Name: Bruescrues
Area: Where battlemasters are located
How to replicate the bug: Talk to a battlemaster
What happens: Says "GOSSIP_OPTION_BATTLEFIELD"
What should happen: They should say "I wish to join the battle!"

UPDATE `gossip_menu_option` SET `option_text`= 'I wish to join the battle!' WHERE `option_text`= 'GOSSIP_OPTION_BATTLEFIELD';

That fixed it on my server"

**Comment by scotty0100** [comment]
Used the fix. Thanks +10 VP :)
