### ISSUE TITLE
Gol'Bar Quarry

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#68]
Reported by Skylark:

"Name: Skylark
Area: Gol'bar Quarry - Dun Morogh

Skullthumpers are too dense.  Sometimes 3-4 very close to each other.  Also respawn very quickly, sometimes dropping down from the roof of the cave along with rabbits!  Also a pig wandering around in the first part."

**Comment by kamicolo** [comment]
CLOSING https://github.com/scotty0100/wowascension-issues/issues/423
