### ISSUE TITLE
Hunter Pet Disappeared

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#69]
Reported by Skylark:

"I logged on my hunter this morning to find my pet had disappeared.  I was on it yesterday, the pets happiness was green so this shouldn't have happened.  If I use call pet, it doesn't say anything but if I try to use revive pet it says I do not have a pet.  Any ideas?"

Thread: http://wowascension.com/forum/index.php?topic=216.0

**Comment by scotty0100** [comment]
This has been fixed since the new server has been implemented.
