### ISSUE TITLE
Quest - A Taste of Flame

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#7]
Reported by Scarlet:

"Quest "A Taste of Flame" doesn't work.
When using Altered Black Dragonflight Molt on killed Bael'Gar, nothing happens, thus making this quest impossible to complete."

**Comment by scotty0100** [comment]
Core Issue:
Nonworking spells invoked by Quest Items with EffectImplicitTargetA=TARGET_SCRIPT and EffectImplicitTargetB=TARGET_SELF do not function.

**Comment by kamicolo** [comment]
https://github.com/scotty0100/wowascension-issues/issues/257
and
https://github.com/scotty0100/wowascension-issues/issues/7

**Comment by scotty0100** [comment]
Now working on Starix after patch 01/07/2015. Tested today.
