### ISSUE TITLE
Frost Nova

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#71]
Reported by yours truly, me:

"Upon killing a mob with Frost Nova, the mob will die and its corpse starts a journey around the world.

Map & Area: N/A
How to replicate the bug: Kill a mob with Frost Nova.
What happens: The mob dies and the corpse starts to move in the direction the mob was running to prior to dying.
What should happen: The mob dies and the body stays at the location of death."

orfeas noted:

"its not only with frost nova...same happens with stun effects!"

**Comment by scotty0100** [comment]
Should be fixed after today's patch, if this is not the case please reopen.
