### ISSUE TITLE
Blackrock Depths

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#76]
Reported by Skylark:

"When you do the Arena, after killing the boss if you go out of the arena back where you came, which we had to do for part of the ony questline, the gate closes again so you don't have access to go further.

Edit: We reset this and the gate was open after, however we did not go back the way we came, just went forward.  Whether returning from where you came bugs the gate out, I'm not sure."

**Comment by Skylark14** [comment]
The ambush in the area where the fire elementals are in the city do not appear.

If anyone shift loots it bugs loot out so no-one can loot the item

Ribley Screwspigot in the Grim Guzzler does not react or aggro when you break the casks.  This also affects the Thunderbrew quest.

**Comment by Skylark14** [comment]
General Angerforge: reservists kept respawning even after the general died.  They shouldn't do that.

Core Fragment for MC attunement takes far too long to respawn.

If you wipe, even though you killed the boss in grim guzzler and Chamber of Enchantment the doors close.  This should not happen.  It suggests that either the reset timer for the instance is too quick or the doors bug out.

Warder Stilgiss should have the rare tag.  He was not made a normal mob until patch 3.0.0.

The Portrait in the vault area does not inform you of the whereabouts of the key keeper as it should - it does nothing.  This affects the Heart of the Mountain quest making it impossible to do.

Also in the vault - when you open the surrounding vaults from the Dark one, the boxes are all empty.  They should contain bags of money and grey junk.

**Comment by Skylark14** [comment]
If the party die, all doors reset, this shouldn't happen.

Also chest after killing bosses in Summoner's Room should be beside the door, atn its at the top of the stairs.

**Comment by kamicolo** [comment]
seem to happen on old server closing now unless needs to be reopend can't replicate it
