### ISSUE TITLE
Skulk Rock

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#77]
Reported by Skylark:

"Name: Skylark
Area: Skulk Rock - Hinterlands

Oozes and sludge are either in groups of 2-3 or some single that when you engage one or more drop from the ceiling when you enter.  They should only be singularly spread out."

**Comment by kamicolo** [comment]
CLOSING: https://github.com/scotty0100/wowascension-issues/issues/423
