### ISSUE TITLE
Dire Maul Bugs

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#79]
Reported by barrotes:

"so let me start making a list on dm east bugs 

1º pushilin will not go trew the entire course when you talk to him on the last waypoint before he bemomes a boss he rans to the place and then resets to the begining not turning into a boss this situation prevents you from getting the key to the other dm areas (west,north) way to fixed for the time being spawn pushilin in is boss form at its place.

2º the following boss is not spawned Lethtendris its not her area here is the wowhead link http://www.wowhead.com/npc=14327 way to fix spawn the npc 

3º we found other minor bugs like aoe agrro the entire instance ironbark being red and not going friendly to open the door but the door can still be open. none of this actually intereferes with gameplay to a point that needs urgent fix 

ty hope its solved soonps: could use a instance bug area for easier consult for either players or devs ty"

**Comment by scotty0100** [comment]
1) Tested and it worked for me, he went around, at the end I talked to him he spawned plants, turned into a boss and I killed him and then he dropped the key. Unless it's timed I don't know why it's not working for you.

Other 2 I will test later on.

**Comment by scotty0100** [comment]
2) She is spawned and at the correct location, wowhead isn't accurate as I think she got moved along the way : http://www.youtube.com/watch?feature=player_detailpage&v=hdU-IWdLZ54#t=131

**Comment by scotty0100** [comment]
However looking at that video, her and Pimgib path around the campfire which they don't do here so I'll add that in soon.
