### ISSUE TITLE
Defenders of Darrowshire

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#8]
Reported by Scarlet:

"Quest "Defenders of Darrowshire" doesn't work.
After you kill a required mob (Cannibal Ghoul, Gibbering Ghoul or Diseased Flayer) nothing happens. These mobs should spawn a spirit (id:11064), to which you have to talk to (15 in total), to get the quest completed. Now the quest is impossible to complete."

**Comment by brues-code** [comment]
Hate Shriekers and Gibbering Ghouls will spawn the spirits now. Not 100% blizzlike but you can complete the quest now

**Comment by scotty0100** [comment]
This wasn't working due to an old Acid database being used at the time.
