### ISSUE TITLE
SuperSteffer's Buglist

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#81]
Reported by SuperSteffer:

"Quest-Related Bugs:

The quest 'Hallowed Scroll' wouldn't be offered to me. I had done the required quest 'The Mindless Ones' (according to the WoW stratagy guide), yet it wasn't offered. Either it isn't avalible at all on this server, or it has an incorect prequest scripted to it. The other very early undead class scroll quests may have the same problem. All those quests should have the same prequest.

The quest 'A Rogues Deal' can't be completed. There's an extra objective that wants you to kill the quest giver, but there should only be 1 objective, asking to defeat the quest giver. Also, upon taking the quest, the nearby elite guards attack the quest giver, which they shouldn't.

The object 'Tirisfal Pumpkin' has too high a respawn time. It must be currently set to around 10 minutes. It should be set to somewhere around 2 minutes. These items are required for the quest 'Fields of Grief'.

The quest 'Hidden Enemies' objective - [Gauge Neeru Fireblade's reaction to you being a member of the Burning Blade] can't be met, as the npc 'Neeru Fireblade' will not offer his speech upon talking to him.

The quest 'Counterattack!' can't be completed, as the quest event cannot be started.

the quest item 'Enchanted Resonite Crystal' summoned 2 Goggeroc instead of 1. Part of the quest 'Earthen Arise'.

The quest 'Torek's Assault' isn't scripted properly. Upon taking the quest, the raider npcs next to Torek are supposed to follow him, & help kill the mobs during the quest event. Currently, Torek leaves his raiders behind.

The quest 'Elixir of Agony' (3) can't be handed in, even though the quest appears complete in the quest log, & all the items required are in my bags. Upon abandoning the quest, Daggerspine Scale & Torn Fin Eye are supposed to be deleted, but stay in your bags after abandoning the quest. The quest items Daggerfin Scale & Torn Fin Eye may be missing data.

The quest 'Gerenzo's Orders' (1) can't be completed, as the quest event that starts upon taking the quest never begins. The objective 'Keep Piznik safe while he mines the mysterious ore' can't be met.

The object 'Serpentbloom' is sometimes empty. It should always contain 1 [Serpentbloom] item. The items are required for the quest 'Serpentbloom'.

Quest item 'Crate of Gost Magnets' doesn't cause 'Magrami Spectre' to spawn. This makes the quest 'Ghost-o-plasm Round Up' not able to be completed.

In the 'Quest of Endurance' quest, you can open up all the food crates in the Roguefeather Den. Allowing you to accidently, or intentionally start the swarms of mobs 3 times at once. When you open 1 food crate, it should open all 3, spawning the waves only once.

Crank Fizzlebub is offering the  quest 'Fool's Stout' before the correct prequests are completed. The prequests that should open up 'Fools Stout' are 'Zanzil's Secret' & 'Back to Booty Bay'. 'Fools Stout' should be repeatable, but should also become unavalible to take after 'Zanzil's Mixture and a Fool's Stout' is completed.

Captain Hecklebury Smotts is offering 2 quests at once, but should only offer one. Currently, he is offering 1 he should not offer. Both quests he offers are called 'The Captain's Chest', but the one with the ID of 8551 should never be offered by him.

The escort quest 'Skinky's Escape' doesn't have the escort event scripted at all. The quest np, "Stinky" Ignatz doesn't move at all upon taking the qest. The quest can't be completed.

The quest-summoned npc 'Manifestation of Water' is currently hostile, & can be attacked. This npc should be friendly. The quest that summons it is 'Seeking Spiritual Aid'. The npc is summoned upon completing the quest.

The horde quest 'Un'Goro Soil' is unable to be taken. Even though the prequest 'Assisting Arch Druid Runetotem' has been completed, the npc 'Arch Druid Hamuul Runetotem' will not allow you to take the quest 'Un'Goro Soil'.

All the repeatable quests offered by the npc 'Maybess Riverbreeze' that begin with 'Salve via', eg. 'Salve via Gathering' rightfully offer the correct exp upon first turning them in, however, the exp should only be offered the first time you turn these quests it. Currently, every time you turn these quests, regardless to having done the quest before, it will always give exp.

Looting the object 'Fathom Stone' in BFD should summon the elite 'Baron Aquanis'. Currently, he doesn't spawn.

The npc 'Firegut Brute' should not drop the quest item 'Pure Un'Goro Sample'.

The quest 'Sweet Serenity' is being offered to me, even though I am not a blacksmith. It should only be offered to blacksmiths with a skill of 250 or higher.

The quest 'Caught!' should have a prequest. The prequest should be 'The Key to Freedom'.

The quest 'Grark Lorkrub' should have a prequest. The prequest should be 'KILL ON SIGHT: High Ranking Dark Iron Officials'.

The objective 'Fully explore Frostmane Hold' for the quest [Frostmane Hold] can't be met, so the quest can't be completed.

The quest 'Deeprun Rat Roundup' can't be completed, as the objective of capturing 5 rats can't be met. Bringing the charmed rats back to Monty does not coplete the objective.

There are 2 'Call of Earth' shaman quest chains. 1 in Mulgore, & 1 in Durotar. The Mulgore one is restricted to tauren, but the Durotar one can be taken by all shaman classes. A tauren doing both chains, results in the second one bugging out, making it ucompleteable, because a character can only hold 1 Earth Totem. This can be fixed by either: Making the Durotar version restricted to Troll, & Orc, or by Making the other chain unavailable to take, if you have already completed one. Another option, thought I'm not sure if possible, is to be able to do both chains, but upon completing the second chain, the Earth Totem from the first chain you did gets deleted, & replaced with the one from the second chain.

The quest 'Your Place In The World' should be able to be taken by all Horde races.

NPC Related-Bugs

The npc 'Cannoneer Whessan' spawned inside a cannon, & can't be attacked.

I feel that the npc 'Scarlet Friar' uses its Lesser Heal spell too often.

I feel that the npc 'Greater Duskbat' uses its ravage ability too often.

The npc 'Razormane Stalker' should be stealthed.

Son of Cenarius spawns 2 Treant Ally instead of 1. One of which isn't classed as Son of Cenarius' minion. The one not classed as minion should never spawn.

Treant Ally attacks for too much damage. They hit like an elite.

Theramore Preserver currently casts no spells. It should cast these spells: Holy Smite, Cure Disease, Renew, Lesser Heal.

The npc 'Deviate Shambler' seems to have a lot of resistance to some, or all schools of magic. It should have no resistance to any school of magic.

The boss 'Verdan the Everliving' currently has a much larger hitbox than it should have.

The npc 'Evolving Ectoplasm' doesn't seem to have the abilities it should. It should have these spells: Evolving Ectoplasm (Blue), Evolving Ectoplasm (Black), Evolving Ectoplasm (Nature), & Evolving Ectoplasm (Red). These abilities give them immunity to 1 school of magic each.

The npc 'Shadowmaw Panther' should be stealthed.

The npc 'Grenka Bloodscreech' hits too hard for a normal mob.

The npc 'Gan'zulah' currently hits for too much damage, & is incorrectly marked as a rare mob. It should be a normal mob, & hit like a normal mob for its level.

The npc 'Zanzil Witch Doctor' currently hits for too much damage.

I feel the npc 'Vicious Owlbeast' used the ability 'Fatal Bite' too often.

I feel the npc 'Thistleshrub Dew Collector' has too much magic resistance.

The rare-elite 'Fingat' currently respawns far too quickly. 

I feel the npc 'Highvale Ranger' is hitting for too much physical damage.

There's too many spawn points for the npcs: 'Young Wendigo' & 'Wendigo'.

The warrior trainer 'Harutt Thunderhorn' always has the gossip of "I can not train you, warrior", even if you are a warrior. Gossip should be set to something different when speaking to him as a warrior.

The warrior trainer 'Krang Stonehoof' always has the gossip of "I can not train you, warrior", even if you are a warrior. Gossip should be set to something different when speaking to him as a warrior.

The shaman trainer 'Meela Dawnstrider' currently has no set gossip.

Overall NPC Bugs:

Many npcs are dropping herbs & ore gathered from the area they are located. They shouldn't drop these.

Npcs are currently aggroing as soon as they respawn, if you are within their aggro radius. I belive there is supposed to be about a 3 second period after they respawn, where they can't be aggroed by being near them.

Vendors that offer quests will not let you use their shop until you complete any quests they have to offer. They should always allow you to use their shop.

Minions of npcs should despawn, if the npc that owns them is killed. Currently, the minions continue to attack, even if their owner is dead, & only despawns if their hp reaches zero.

The drop rate for all of the E'ko in Winterspring is currently far too low. The drop rate should be 20%.

Npcs are able to use the ability 'Backstab' while you are facing them.

None of the low level beasts in starting areas should be able to be skinned. Eg. Mountain Cougar is Red Cloud Mesa.

Ability Bugs:

The priest spell 'Holy Nova' is supposed to cause zero threat. Currently, it causes threat.

The priest ability 'Mind Soothe' causes the mob to aggro. It should not aggro mobs. The ability decreases the aggro radius of a mob, but this effect is useless if it aggros the mob in the first place.

Object Bugs:

Some treasure chests are respawning far too quickly, such as for 3 & 15 minutes.

The object 'Concealed Control Panel' needs to be removed from thousand needles, as it wasn't addeed until TBC.

Activating the object 'Altar of the Deeps' in BFD currently does nothing.

All of the corrupt Felwood plants should despawn after cleansing them. Currently they don't, meaning you can cleanse them over & over. It also makes the cleansed version of the plant very hard to click on, since it spawns on top of them.

All of the cleansed Felwood plants give an error 'Another action is in progress'. They depsawn after the error, & nothing else happens.

Other Bugs:

The rings from Booty Bay vendor, such as Cubic Zirconia Ring, are in treasure chests. I don't think these rings are supposed to appear in treasure chests.

The desciple of Naralex escort in WC works until he reaches Naralex at Dreamer Rock, & starts the waves of mobs. The first wave comes, but after they are defeated, nothing. The event doesn't continue. Also, the mobs spawned in the water of Dreamer's Rock evade unless you're right next to them in the water.

The cost for most spell & profession training is far too high. For example, learning Heavy Runecloth Bandage costs 12g at exalted.

The earth elementals around Kodo Rock in Mulgore should only be visable with the buff hat the item 'Earth Sapta' gives you. Currently, you can always see them."

Thread: http://wowascension.com/forum/index.php?topic=67.0

**Comment by Skylark14** [comment]
"The rings from Booty Bay vendor, such as Cubic Zirconia Ring, are in treasure chests. I don't think these rings are supposed to appear in treasure chests."

http://db.vanillagaming.org/?item=7341#contained-in-object

**Comment by kamicolo** [comment]
Right this player doesn't want to make 1 bug report per 1 case I am not gonna go trough all this for now..... so closing this and label it player report in a single big post
