### ISSUE TITLE
Muck Frenzy at Fray Island

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#84]
A couple of 'Muck Frenzy' fish mobs at Fray Island (Barrens) are wrongly positioned, some are floating above the ground, others are swimming under the ground.

**Comment by scotty0100** [comment]
This is a Z axis issue similar to what happens in caves, core issue which needs further work on Map Z axis.

Closing and keeping one main bug open for this type of issue.

https://github.com/scotty0100/wowascension-issues/issues/423
