### ISSUE TITLE
General - Instance - BRD - Giant Black Gates

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#86]
Upon walking in the passage of the Giant Black Gates, you are being blocked by an invisible wall after triggering the closing of the gates as well as before closing the gates.

However, you walk on thin air while the gates are still open, instead of falling down from the edge.

Confirmed and vote points to Holmski.

**Comment by CravenEsq** [comment]
Confirmed and vote points to Holmski.

**Comment by Tobschinski** [comment]
That's nothing we can fix. The GO is always in place, opened or not.
