### ISSUE TITLE
NPC - Emperor Dagran Thaurissan

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#87]
Name: Dhanae
Account Name Skylark
Map & Area: BRD 
How to replicate the bug: 
What happens: Hits for far too much on his ability Hand of Thaurissan.  Combat log showed it hit for 1146 Fire Damage.
What should happen: Hand of Thaurissan - Inflicts 240 Fire damage to an enemy, stunning it for 5 sec. 
Located on WoWHead Map (if applicable):
Source (proof, if applicable): http://www.wowwiki.com/Dagran_Thaurissan

![ofu7](https://f.cloud.github.com/assets/5263181/1015914/adb931a0-0bea-11e3-830e-31cf3a4606e6.jpg)

**Comment by Tobschinski** [comment]
The spell has attribute SPELL_ATTR_LEVEL_DAMAGE_CALCULATION, the damage is based upon the caster's level.
