### ISSUE TITLE
Tarantula Spider

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#88]
Name: Toots
Account Name: Skylark
Map & Area: Redridge Mountains - Three Corners
How to replicate the bug: Kill Tarantula's
What happens: Some, when they are killed, seem to take a world trip, sliding up the road and up hills when dead. Killed quite a few, this happened on two of them.
What should happen: They should die where they are killed. 
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by scotty0100** [comment]
It probably is a certain type of spell you are using

https://github.com/scotty0100/wowascension-issues/issues/71

Perhaps some sort of movement reducing spell?

**Comment by Skylark14** [comment]
Shes a lock so it was just curse of agony,immolate and shadowbolt.  Had similar on my shadowpriest in wetlands though she does use mindflay.

**Comment by scotty0100** [comment]
Should be fixed after today's patch, if this is not the case please reopen.
