### ISSUE TITLE
Daily Delivery

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#89]
Name: Dhanae
Account Name (for vote points rewards): Skylark 
Map & Area: Menethil Harbor - Wetlands
How to replicate the bug: Hand in the quest Daily Delivery
What happens: Seems to get stuck to completion so you don't get the follow up.
What should happen: You should be offered the follow up quest which leads to another.  Once you close the 'completion window' he doesn't speak to you again.
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by brues-code** [comment]
Are you honored rep with Ironforge? The quest he starts (Young Crocolisk Skins) requires it

**Comment by Skylark14** [comment]
Ahh that maybe the problem.  I remember doing this in vanilla but they may have removed the rep requirement then.
