### ISSUE TITLE
Escort Quests

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#9]
Reported by Scarlet:

"Escort quests are broken.
They are always marked as (Completed) as soon as you pick them up. The escort itself starts normally. Basically you get a free reward."

"Okay, I can clarify that not all escort are broken (because I saw some escort quests that are working quite nicely).
As far as I can remember, these quests are marked as completed once started:
- Missing In Action
- Hints of a New Plague? (id:660)"

**Comment by scotty0100** [comment]
Hints of a new Plague will be fixed next reboot.

**Comment by scotty0100** [comment]
Tested these today and they still auto complete. Fixes found and should be pushed to Starix soon.

**Comment by scotty0100** [comment]
Fixed and live as of now.
