### ISSUE TITLE
NPC Sooty for quest Vyrin's Revenge

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#90]
Name: Breena
Account Name (for vote points rewards): Skylark
Map & Area: Loch Modan
How to replicate the bug: Search for Sooty
What happens: Sooty seems to be missing, searched using track beasts all around the cave area where he lives.
What should happen: He should be in the area surrounding his cave
Located on WoWHead Map (if applicable):
Source (proof, if applicable):

**Comment by kamicolo** [comment]
seems old server issue
