### ISSUE TITLE
Solid Chest Spawn Timers

### ISSUE THREAD

**Issue by CravenEsq** [scotty0100/wowascension-issues#91]
A Solid Chest in Azshara (38,80) is spawning every 3 minutes instead of 2 hours.

Unsure whether this applies to all Solid Chests, could use some further investigation, both database-wise as ingame-wise.

Vote points rewarded to Azrash for notifying me about it.

**Comment by Skylark14** [comment]
Respawn timer is 3mins according to: http://www.aowow.org/?object=153453#contains (scroll over the points to see the timer).  Blasted Lands is set at 15mins.  Other areas area mostly 2 hours.

Also vote points are only awarded if a bug is found to be correct.

**Comment by CravenEsq** [comment]
Thanks for the heads up Skylark, report rejected.
