### ISSUE TITLE
The Missing Diplomat-part 8

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#94]
Name: Breena
Account Name (for vote points rewards): Skylark
Map & Area: Old Town - Stormwind City
How to replicate the bug: Speak to Dashel Stonefist, who you then engage to defeat.
What happens: You engage him, he then calls his friends, one engages straight away, other 2 you have to actually engage them, after killing them Dashel then goes friendly but then doesn't complete the quest.
What should happen: He should complete the quest for you to get the follow up.

Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information:
![missingdiplomat](https://f.cloud.github.com/assets/4540036/1029852/6c21adca-0ea2-11e3-8bec-2d532505ce82.jpg)

**Comment by Skylark14** [comment]
Would like to complete this quest if possible as the quest reward is a nice upgrade .

**Comment by Skylark14** [comment]
Abandoned it and retook it from Dashel, this time it worked ok.

**Comment by Orcozzio** [comment]
Tryed 3 times with my hunter setting traps before speaking with him... on the 1st attempt both adds ran into battle... I started hitting Dashel and he turned friendly before the last blow... finished adds, but was unable to complete the quest. On the 2nd attempt one add didn't moved from his spawning position... killed adds but the quest was still stuck... On the 3rd attempt I moved behind him before speaking with him... this time adds spawned but didn't moved... I "killed" Dashel and he turned friendly but the quest was done... killed both adds after that...

**Comment by kamicolo** [comment]
closing - https://github.com/scotty0100/wowascension-issues/issues/97
