### ISSUE TITLE
Warlock mount - level 40

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#99]
Unable to locate NPC Strahad Farsan in Ratchet.  Can this be fixed asap as there are 2 locks unable to get their mounts as he's not where he should be.

**Comment by brues-code** [comment]
The npc is for some reason flagged for GMs only, but I'm not sure yet what's causing it

**Comment by Skylark14** [comment]
I have seen another lock with their mount so it must have worked at some stage, unless he was automatically given the mount because it wasn't working?

**Comment by scotty0100** [comment]
Fixed now, thanks Brues for the fix. +10VP to Skylark.
